apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:EZ42e8xibg==,iv:amcIc2/gwv4isKzKB9G1mWyaE5QdnEGSxcMUU57CLXQ=,tag:MjY24t0KkKxjh7mjhA1nfg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:z4/VXZDM1g==,iv:7VYHGTHkoE1TwDyumqkJR6gqHfsQ3NQNQjERIZIEppY=,tag:NSqtfM8acDbP6RxbSNa0pg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qvMxe7jSJDjYB0XFZIR7rOWXpw==,iv:ydN+ZiEMilaukUth2+csZ5sUewCbNboWCqdkpkBAps0=,tag:pPGCHdtn3XcDaec4G00Gdw==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:5O30yK4fI300vOKujHN/UlSt4RrVU1Xj6J27JRCQT07Vx/Wmz7BI7AisMYAba1unmZ1iU6behOinnPQj5Wx3RfA3UQ==,iv:hOF3hdDyjsF2Jq9k0rQYOK7moMXyl8/9uN9Gh1DPUAU=,tag:wlhMnFPR00GF9iD3FZaxVQ==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:fiAIoUfkbmHxeA6o0F904qJ5kFDG7fZ1k79TKzDsjcdxoUpbXL00KEBu2fYe3EVFy2e29C/djfyB1qsGUVJlu87fhg==,iv:hf8TJCWU0XotUdifsUjoZInLziMQUA4MO6GJzvAMkV4=,tag:e0ZC6GxCHkfUk5N6LU9t6Q==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:6bsz11mbSg==,iv:E2P5r8F7PsEpaAbo7L2wHjw6if3wGbevQnUrUKheom4=,tag:DkRrps9MuK2RKwDlg11bhw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:/VoxICY9YCfk,iv:UbRJV0/39DkNtC1lD8Ek4BtejwpLOgQm2XvASjy57Js=,tag:Rhr12kIcxYrOAfNeophCcA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:YMS4kXa7DsOm7M1tGz3BDlRnMfRfT7ZFBtcF1lqxS6T27NKl5ZwYpVf52FX7gfuqOOJEPCAEW6EnS9qu1AEyfjW5rIIkXtaFIrt9/Po+NnjM9U//lOjgvJ+ejfbDm9DCiFbkwT0ZnM9O78WyiQCz3ldSJNcYfwK07MF7wFI/8EBikEAoH951TNWNk2a4bT/wqSlk8eZiy2cJe8pnyX1h+d6Yoek=,iv:STmjSmRIyWtT10UXFPMjuUnQecyZfxa6nVnybRxcdmw=,tag:kInP7bsnkur4td9cEVvIqA==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:9odMeLgz/9BkcKnPAaZBxWJ5Pi+F5vRdLGqckBcpXxA4BwA=,iv:9jfCuiMumvNBwiWqTfhgHx0XYpCaUU4wyWIdCZoxUbg=,tag:40olzWLvA8F80QId0Tmajw==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:b9d/0fKZfCW0utNvOdpWN/vqpVhoqLBxAHN+Hogp+UzpL5Pc30CE,iv:CUyjiGxvi0qzHkzpgycZPl0Ky2QmBMFNTFGYzR6iAjE=,tag:6bhmqccBaoeX9yrEt5cmhQ==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:Xm1aeW+zYteQUV5LuOONHPs=,iv:hc9FBBGkwRvvwyMaiV+JisVXsRmvA7SLjAZLR4IEO0g=,tag:AqYD7PTuV3kRLCIAEG1KbA==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YgmDUZoo6EfMLwFPvv/kSeJ5VZs=,iv:777po5DS3eATIcQU9mjmK59iy87MlBwgE/NJBbqkpkE=,tag:BwYMLnQIKQPbOxprySGwYg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EWc+NJGqbjZQPMZvXtLCKPcSnsfODFw2+qmku7oav0/cBzWXomMIbQ==,iv:mtaVPPOwqHmc7OAGntSyekUSWLMUs9UKRqUKvzoNb98=,tag:tW2ZCSRCmj/dC6erYTDDuw==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:DyXxcMv6oyaZ,iv:jRw3jZuhnLDheeGTCftMyp9Gy/7e1GDIe3khdPWhzzQ=,tag:cEp8e/ZdL0suZ7QjvaFrmA==,type:str]
    drop_params: ENC[AES256_GCM,data:TAjkHQ==,iv:NGtblN0IaQRI8jsrthH98vB4JB3RtCT6lbUjBFF9bPY=,tag:886bzHTFFTebNqRBb2fd6w==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:b4lvewRIeoCkgMPBU7PZC4m2pDZEta6gesv2H3TN4w==,iv:s5dRPZVqUy29yOge9uY1VMoMHUYVJ9GCSTbEtOsfQ1k=,tag:VR0TwD4BcW+ZtmZZ83u4vg==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:oHva3oQVmgxzAmphZLFHF4A+10O9Rvr1+oatdiFu/y9g6Sx7Fi0097/oCNVYjiVOrg==,iv:J/DdDopFroD1qU7+zRx8t3b02qj7tReffZQtXXqlOpk=,tag:yQ5KoQbMwuNBqxQDbwtysw==,type:str]
    #ENC[AES256_GCM,data:i0xHTRegum8kTJUk272ebUt++dqAxZHKf/w=,iv:nyRT0CXIl6/xpLVCIn+DF16vjjlHgUgaHs17bp1Dx/s=,tag:ykDbSy2xQ69Mo4XAr2FDdw==,type:comment]
    #ENC[AES256_GCM,data:s02DbuQ46479n53Z3TUrdoBCkmSxjdT2EpJF63/a4rjJKW4W1oFxEgy7L3r5+D4=,iv:Q1QeMJ5nlCLmG/rVW8/vLFINeZV9Nx7WAxWWJCq6CHc=,tag:su6W3IRzGvZNLyf1caURXQ==,type:comment]
    #ENC[AES256_GCM,data:9toMV3ACEtXXIcJqTSx5U23yYSn0meBQinRD+SD4oc55Z1bX0dMK4w7lYcXY1w2edOuGoXI=,iv:6SxfTXjS310mznLmPinvw7kGI9xdc3z4Z1KCRf0OIVw=,tag:LQc37hLGYcQOt54dQ6YteQ==,type:comment]
    #ENC[AES256_GCM,data:RD9JKcgWuRMvKMipRXEDvxSpCvRIBHhip2w=,iv:f+M8Z7ev4hkqVi05jiKJ5AduugrimAIhRe6kUHqgwhk=,tag:qZi9muaXtAR3s9wa1fBD8A==,type:comment]
    #ENC[AES256_GCM,data:p0SXgXHLi2sndg9yowXde3xshYTuuvrxF6qvLeMaqYwY0oJQN2TguSwBIOzlQ97B3YxOdzwvE7bsfxXz,iv:dxxLB4f4+X+5+eLESd9w49asbnb+TiUmvM5YAVV/j9Q=,tag:IyQAPWo6UHdSieE8vBdncA==,type:comment]
    #ENC[AES256_GCM,data:dqsenM1NFrkUPHvOLHMJEhC122lR4PsAUvXLJtXOz69wXsVNcuovWCjPe5IKzL/A2GUhDmQNhJod9Di+BQ11x31IwPyP+rAsjwlQWm3p1MCxvdHQiBfTbmef4ik=,iv:29ILhXIWieWgsr5Yy2+9Qxb58BPlHWNR0BdvfvMLSXk=,tag:Pff8fBu23C2WPSz8gia0NQ==,type:comment]
    #ENC[AES256_GCM,data:Dj0XbCXfc7cb7cCmdaZiwagsDvrUO58chKoBdv2U5EOr+Y5liclck+pmkfJg6fP0TsGPu/M3PePsD4fjlF8ooi0sMlRzJJsKR8KNmQ==,iv:zpaah8wqcC6IUpx16l85o43ggsHL6fxvUvbbdBKDWRw=,tag:5+vLPa7KY05Svh7GquMmNw==,type:comment]
    #ENC[AES256_GCM,data:dodi2coI8QjV9zdqrV+BXsPNvsKNx3iSfZkQjXMOLyRdggnyGP+dav5cbSbSYwc7LHaLcS4pXm6koEj0Zztb8ctol7BkQQv03owYi4Fb49dlKA==,iv:DYaTL3uW9So9x7uNytfH27B87WT0qJakur2dv8iG/CQ=,tag:r5XoQbvu3Y5UYGNv+16d8Q==,type:comment]
    #ENC[AES256_GCM,data:rXTPGU5rpro0bHJJDK5YVWimUrQRyhCWQXovJ5GVFXfZ,iv:EFqo9/rWPZWNxEFi4eYAgDuLbHeIvIet+NYeAvkbzBE=,tag:O3LLC9691yFaC5W9JGgHCw==,type:comment]
    #ENC[AES256_GCM,data:QRqnMUxl8GrJsx0DVkeKpomtpryUonFk+wua9/IOySSKMoPzu/W1DJxngi3gL8R+a6Sd5ZWCbt2YwLLbZl3gHE6CQ/TBHrULFJ/KdVI+Kw4oV+q+pqE=,iv:4ePnsZWyliMoBCF7yhmlkOst+jAcN0kzd6uFt5kG/kc=,tag:VCLrMtkYvJIvugnjfG3Agw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWVRFV1owNFI5QnJLNlY2
            VTVncUVZcDgxV1FORWo1Zi9RSjkxeWNEelh3CkxwSThUb2ovYmdPQkJobXdmTFJy
            OUFaL1htV2JJbXlqMDJmeDlSRlpRT1EKLS0tIGdWZ1duRmhqVXBUSldjWUh3L3NF
            Um9aNUV1a05kT1k1eDVKNGQwOGhNTUEKS6Nmk9ODnadO/ct/5L3dFctzcnZ9t8Qa
            0nyDZCmL38PBjeyXjpukmwUAs5G1HG7ShmRE4KHsp21g8D0W60qP/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T06:18:20Z"
    mac: ENC[AES256_GCM,data:HxX5rjl0p/Ld1ixxFEuIXqymAx+U2JhCPmVf/0vOsvBSUfURPft7skhhDulxORPA9BLG9WIl/OuyJQXP4czIzymguGnfUK1PUP1g5hyb6YEQo4gymqsu1VGHlTuXKoCzlAGwHUQgDii7a/h8gC7wxxAgx5NsERpiKc+iNeU+Qfg=,iv:rb+zuAVySYr2ohFPAPfkbIVuGJJqincZqD92KxtmZYU=,tag:LA/cTKx3+VsjfC4xQ+fHsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
