apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:7WBDDkF1aQ==,iv:LKpjoIPGoMJbwr58NwvOg24twjlXKC23EkkKnJCs5HY=,tag:n18rQBsjXwUl45dXv8CegA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oWofaduajA==,iv:eSrX6qvqMvJv6C5Nxyu9M6JhjZOmHHQX2wm/qvCIp04=,tag:dLSMBsjYVY5NoGVWqhXtYg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EpznWy6J1FEDSDehaq9AWMgjNQ==,iv:yjCOlccRT/ThxdWCbtLXNdpjlfQe8oTM5dia6n9xe4Q=,tag:S3vUfdL6fkfj7vQPdbNyGg==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:ch33AYxgHx+Y5fd2j8rs3faPLD35EE8MKCgj4WwPTL04b/+E1CIffnVFt4A92IFFbOfXfHQ6X99ZEv+GDEpS6shzzQ==,iv:/EAV9nzZuTmuJqNlvV4eRlkyJ5CKdepENXJIS8gca1s=,tag:d/7GEuw66XBgc6MjX6AdCg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:L5A2YSJpA26juM1n116AF8jE/NXHN7pXWJZbphPuE8TH1c6uYC80aofpRysHm/QI6FR0rLvRyCUoutjbggPYxjpmTA==,iv:9iFRnhpOatGP7keAvRPyvV6Q0ySbJOHLTYvLj0PMwkk=,tag:aG4M6lzMuhr3tu8CM44Dvw==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:FXyI1sZ0Vw==,iv:aHFjcWjSm3w431gMvN99XnzmPkikg98P97cS11ONKIk=,tag:+OHurC0IKb0y/puVZlFqGA==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:GXh1VPgkt08G,iv:zO1X0dtmr73UFPzOCxA3E3PI9t7DdoEjH76CEMSsJTk=,tag:DcGGWDfkQPKjuvu5PGR+4w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:6UkZVosNXYNEnJE1qHaSjaL1kGxYZbWPo6lonEEsH8TLTG6UmpjKwR6CzWZ+FTN8TcJpWlks0/w9vbDoLoZrQ3lf/tGlSt+kn/OTXU6edQu+dV1hnIQec4piMzLe5c1wjNhBE7xbneS5rdbd1zE1g+RC/ng17s6ocVSDZjW0GLG2eLwxrUi7aP1yxFCWd3AlkEvxWIUJpROAaT3Wo0uF06zs4Ow=,iv:SVnscgX4n2NEKIv85b0+XJu2L2Nne0bEnvOKUPqC5FI=,tag:RuyoF6D1RISabB4MWRftFA==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:rQuBE52M11cUydJedpxxpj6el5E6bh9I8uheTJOZ5lfYmQY=,iv:OZfyBt7mwj1xJgfbSqYz9DQBFKTalKaildNoS7my08s=,tag:AtPnGRi7h2Siu+UCX0x4Nw==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:8dF4szyW1s25vTb21J871y5BGO3SIpZQ1JNAAv7YVpE+vW8rVgbA,iv:bsJh9FmgFhufaQwJc/rhsEH5rUQpOfX9bAwb8IqLKZo=,tag:PA2qlo0uIXWWEiU4ozYlCg==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:uZ026U0vne+qTXK2h6FyExo=,iv:R/6Gm9Dwm/Dvx5Y4UvPehpAjiM1iWMtNSWhxKOn7XAs=,tag:kSKOLrkhIrc8dDdgs2NU1Q==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5TrMPzpxMtsMyzMp8hoeF0ZlkVw=,iv:+5SM3/1Pi80SZjvOrBkEi64SGGtD2hXyxGe0DzGFTJo=,tag:2uo3ITQ/g4UNrjdJ0NS2KQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Bq/QHyffvCxwLOunhXnIL9NEu80BzuPq7Mi4judqa0r85MOdRFc44Q==,iv:8RXMQmG2c3aLEht7PkOXBUzgh83ZCxXJw8qvzP7e2pM=,tag:7sA6mNoUY9vpJgcNpO1idA==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:0nAGOlh1XRCi,iv:B9p9oeRg61KwKl5BNPm3PA6XRWoT+RvMSJXEcwoP9j0=,tag:nIYC8L/T2sTQNCEUXsvu/w==,type:str]
    drop_params: ENC[AES256_GCM,data:GTO4MQ==,iv:4+SsyufC5AyY7M/nZFhCFJiyEIWmeTcw0RqY2o2XIc0=,tag:nFKomH0GQKwFs3QXssRHkg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:30xKHPjxcsZd613cgbuyM6CkE7HAugEjmQUkSSu3tw==,iv:BIDEiYblyi+WlD6I4156FhtfBctPMntq8W4DJz7yi6A=,tag:tHHe0qLzck7j8DVADQglAA==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:/WTzb8VsIUwDST+JQnj1u4/odmJrkweZ8iG+FVERTZYzU7C259VG8ydgH9FEc5DNtw==,iv:gEmEazW8CC4xNhT7a9fojH/L7VZheTm1Hp8ozbikcPY=,tag:/SnWMvpHQ12eQlpmQ+Namw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWkpQVTBTSUhPb1RmVHBu
            RlpYYzVzR2IrYStiNytGU1ZqU3NGTGFqY2hJCjZlc3lhNnpHNFhVYVh3N3dpRG55
            UU9yWU9PTGdLdW5IZG0xT09vNFJrZWsKLS0tIC9jVzNPaVBrT1JTYkc3ekRHYVZ6
            dHNRMlNxaTZ4N25wdUlqZHVWTUxEamsKOIxSbnKFW8t1/yUGhY0iPRJ87ZtBpDrU
            AMvTD76IFgNzK4aUGR+9ieTkMlQJXYvaRw2zBnPpri7XMfzKNE/eiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T00:13:35Z"
    mac: ENC[AES256_GCM,data:Rd51HkY9W2JRtpIgZa6SWem5fKUk9cnqFzFIF2iOnlGii5jv6gh+p/MCFecMt3QigslZHXV+qrpvNXxSeBmzOrLetPz08/0ty4P4uq/iEmBsePeHbKhdKvOpRqS2jFV7lKn/FFAcu9zJo/jmovgsRwQ98C+HqLeb507PK1Yu1d0=,iv:mNWImJZ7uhqh30i8nPBv3LKxK+XMcW6wNOr9B89OMcY=,tag:tK20VFIvHa2JXr4or9T4Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
