apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:8ow+PbQpWA==,iv:8kuO2sx22TIAfnqVmxYhYJYCcAqQghzFR8OeblgJA1w=,tag:mT9lFrBx+o/tUT7ba2qYsQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:P5stfKkUGw==,iv:YdYBrZImeC6BJSQLGtMi7yEjtVNZ4qWhX+XDc/EEF9Y=,tag:+xjgmpmGVcl8Y+dQUmxzAw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fWbJVeqKgI7EVtyAieOEeYKCyA==,iv:Qtmbx8ae+qhGQGciOp7Z6dD3/XAiYuZiOiAXOidNYy4=,tag:WJ9J9wCLaF8eiFOTKG+Jsw==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:XfPb/4QQk2lYNCW6AUfp5mrBl+sRjAHBMTziM4akNQrsaSbndjRUeCi3iLykIDVPAyoNf0MKHBgywQANsuOVJKNrjA==,iv:RVdsvzZIyUKdoN4OlejsREMkj48/9AixKu/Ajt0xYwU=,tag:3LFnsVI6oOsbqfaLRWTIag==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:+u5s0txHU6oSvuHZVGnH54+aj1DWF1Do043iuZTxB5bCi+rJKikfRpWZ9e/1/dfvb8ZsedFZaRO+eKoZkmYDloB/Mw==,iv:BPX92qncFtnCpBbKdEBUxtSsNeDsmUA492nQaGto8Do=,tag:iECjEDumGLzkL0BlczxzoQ==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:jTjOWShzYg==,iv:NNFiunMb5bK6sOD3b2hQVLZjMHydeh7RBKdUr6FxsF4=,tag:cWNzOjyKF6/lUA42FYPLXw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:s00nMY7eJUZN,iv:ke3iEiYTrM3mptERbXdTbk1KbC+Mk0cVwSfPlrjQ5Pw=,tag:OZmqk508ulLwYCFJkaMK6w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:YZyE394u08ofvlUubDyyqCJ86E7xLjIv2Tr7mZ3xrULBFFXfZVn69qV9vXzskmJleplUD+CJSSMA8Ycd11+p4xww/iN3UD6r14cQO3dsE5WUf/dJwUIDN6H6RUF8NxcVr+4wiAuIu47vofAoQY90+B1PsTWidx90PMqwcJ5X8tzfajiy5lqw8S9GotB8P3lR1zVnKVCTkz3PLF8hbzuMCWZkHas=,iv:U7B1ugezo4qV8/TjlIbLEsQ9mFx4nLwuWhAfEsM9y9Q=,tag:HAagwhOUra8me1ZNBzMi8w==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:ngPGUg4HMH8gSeEi9tXrwXzeW/atNCeSjYEr+hx4wEBdIqk=,iv:o43MOEYCJ23Y1t68N2j0fFc9dB+5ZxQavIiF5086Fw4=,tag:A794SIdWravdrghhFyEh+A==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:I1/5kCrlVTSjrZzP6vAjSUJkunnyiQQ7lwwVbCofVzFNwZGBfUXi,iv:O/eor3gQN8ytSkv8YpnUCv1t6pdEF60vanWwjiuWVaE=,tag:ym+C8eTifI3Oho+7HflFWg==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:5LMAx7l/z5GEX92WUAf8Rpo=,iv:jpiUxZRJ9WErvXvJSWBi18UicUK+3shMll5relb8ekY=,tag:r2S9J+qReXjah8FwfmqseA==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2KcPDVzM+71TzdY1FvEZk3WYoMQ=,iv:/XAJvjk/d+80m6iL1fi+omik9iiWmf3M4xoE/ocgqSw=,tag:Vh3XjIxPyhtrLatwZ6ezng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:C+xY5HMqn4nH61FZjR0kT9N5xf4aVDyTSQ2qKnnhOD0ovFowpBMZKw==,iv:c0ieWBOaSmr8oqYNPpnPy0DW2M1Sw35bYm9J3Nj97Hw=,tag:GQWl8gHHbH5aV+5wMitnrA==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:B3yUxMowEz6B,iv:cYqaqaKvkugkLJitGjCQdsR2gIWIl8nqY4OjaaDCFZo=,tag:esL3pJ8rSYx/UgoBZtCFpQ==,type:str]
    drop_params: ENC[AES256_GCM,data:VbyIgA==,iv:Zaf1VoeiCcIdwRaqK/GTpzRfpfZj/XW6gRIABNkdy1I=,tag:zaDR2VbnuzONbZIiWLRXcw==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:tJQ9pfUTj+YKBp9gEdIEpuZz4z9AxKeRt9aeRzmoUQ==,iv:ebFc1DHaXdqFK6P5DXkwVeX6sXiSYUDWt9il7M4O07o=,tag:XJuSqcoYQ+0dhKbpzAwUuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRlZ5Y3ZoNUlpd1FPYzN2
            VDVNQjJ5YlhVRGxUb3FpTE90SFpNNFkyUlVBCkFjTkFNNHdmdVRmd0JKM3pCclAr
            WE0wU0ZIbEFxb3o3R2orSTlUaEkxdVUKLS0tIERrVk16VmxqV2xpSnNJdW1wQU9r
            SkpnR2xwSnNQN0VsUDU2OWt6Z3lGbTAKbnH1hCVPGzGopsrjvqPwWiTqUsVIZbYG
            pMPRpscs9L2ZHK5ar8BGqF3DNmW9W1IYQHdDb+F9LMOs4Nkt3G4xfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T03:33:17Z"
    mac: ENC[AES256_GCM,data:HHqgkxa/6RmUh4vh23LrxrlLMeZrjZsZf/rhGdTfijDedgpjweGocybSEJBVyb1HDgB4+s45v2GBsPNSEZR74kUO8G5kiGVVF5TwBvj3wN1NWlSVgUbHDrr1jNrFXf5uMVr7jjXjWeCr7fmx8uiBhNto+FLOie+UbpoLkc74I0E=,iv:55Pjrzbd152jiYGJ+a1mU31uNLvyjuGSS5MuJPUAxaM=,tag:Wxbw8pCCn699ZpAKZenMwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
