apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QeyScu55qQ==,iv:TGUyS68iwc3WzRcb8rMJhoyWhhDphNhkFvqmVU7B13I=,tag:j//yd07OohrrW3ImbKL40w==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5VLdFRVnbg==,iv:ivU4Mh1a2HKVdBJuUle3slMy4A6ORXL+XJYFCVHQG1Q=,tag:De/23AFJyIBbXiigcSEP8Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aP/fjq11Luf5zjnvgs4eRn+cTw==,iv:8Ha7ByIksDei5fbgTg7lfe93n3ze6JpHhb1Vh1iOrH8=,tag:QNlyunqxm0k1/ps2CqOq0g==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:jTdE8CIt1srf++E4unswEi0ONz1keQVyXJCYJn6EOtp8kKWBqIEHjnYVJJZE0+jX0za/Pu5WvlW4nnu45eQzt+O51Q==,iv:1szJzlH+VFUlu8yFkvBiv0IAB4RcsYMl2o3FWHLGmsY=,tag:4VA6ylDfbel/5JnnM9EjkA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:knmvWJ2VUgOKqMER4x3R2prtOvHEvX/SJMbPclRSxD5o2p+N3OwS7rMqv2S9r4UGuuOi2Y/k9JrLUJzlJynrFAc94g==,iv:qfEUA2odPO9fE032mQoz7nCiTPt0eRRCWiaVcEjDHr8=,tag:3SPNsRbbOur2deQ53Ke4UA==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:tBpYEYor+Q==,iv:FJGWZwjkRACM2Cm1yG95bpsvF/RfAoda/+fGv4KUSdk=,tag:srqNzFwFjH/8PCnbfor6lg==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:dxHxAo9VfQgK,iv:WIu0V0uQkMQiJuAhr4EZRgQ+9SMrmBOW96YENCQT+uY=,tag:mE9f8ZlfHwcyWr6ZpG+q+w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:H/Bo3+HbE1LQ4ynFXFTnmrTJBw4bbKkb+gmRSL10bqGsg9lTB9v8Gh0EGnqtrOFYlU1j5txKrnzXRQP65zUy///Vp1tu0catQSWezQjNcGGGrGPD/vRKljNmRI0llqhe/0qLcYKEfJgn38Tx65jm+IGO0aaIEGA0G+JAmATe/zLSUfWMIzjr7C8GIfwsJYNblzVnICb55qMSkb+0HCfdl6kEeRY=,iv:0FahWkK2qHlj5iCHue3Jm3uk5+o8Dx9bvX8l3EtmGaw=,tag:10A61xBvUrzs10nyKtEfPQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:eKCXl62tHVbBKw/xpfe/8+/O6nmy8OjIOA8v81SKuPsoRe4=,iv:jiWq3MdOVqvRJi+9r1CbI9eILuc0fGNUOOYsg/5Znmw=,tag:gQLpcKnV7zkWYqqssdTxkQ==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:RHCOxShCTj4KJL5HLFH9OMgoviKYEFzzyu7seo7Qlqy7M/VynGZ6,iv:6HsY2XEJh3IYMOpQ6jDRcJs3qCaJHjZHPSVWgxvw13Q=,tag:YRG7mqqMMwYsvblkBHrm5A==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:dkQDrTf6ISRqoj6Ehy328Lg=,iv:yLvLCSBXfZ5/G5udZTsJ35Hxz0UB/Sl47zGMapNnee8=,tag:XsO4fhnlkfAkAy98/3qt6A==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VFuAl8b0iWAO8xLCtvQzSKk+5Ag=,iv:AovxrAfA8qLrpvz0X2vxmrh50MYZ35LUk8qzKYCz+rU=,tag:NfH9egfd1fu4FHDk/bkpnw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Vy3L4aQlwADYo2x96gjguwtm/OEg1KXo0pc1hoWyKwGWRomHXspJQQ==,iv:Va7zFp20alznnH8lTzw6+idoTPp2iSXjN1EGzppi5m8=,tag:rwVH37IWFqtSt6cgluMqnw==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:LE2kWOqXBtpp,iv:aptPFIlPa8d2U18hoCdoKghYcEevbmtL/UjInIlk8wk=,tag:tddjtJIkJOI94l0xOccgBw==,type:str]
    drop_params: ENC[AES256_GCM,data:pusEkw==,iv:nE9AfFKG0zhjXV0aTKakUtzqe5HoVNoP4dH1j1UBkZw=,tag:nEHs7RHNkv/Rfm2mc+lrIQ==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:YSdCOE5rdyejjz750uScMlzSfUZGpxXzENs07vSapw==,iv:sh6c67ty6+sfkI/QOjat7rgGq/9z9gGDNeQ/b8p8K1Y=,tag:wdU5+JAkcBCwY+tOTMYbLQ==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:CfA1acicmWAuFNmekKJoicDJe2cGHZoiZX53iVB6nrw0/nIKGcXR3z+L8ScHNE3Bxw==,iv:xuzYB8QXiC1oaDXP3C+dzWyJo2g0jajYvMY/pPf7jUo=,tag:CW5h8QYWm904oqZ0/l8TzQ==,type:str]
    #ENC[AES256_GCM,data:bshNuZaP2pcFB8O5vafKaC1jKwkylhQsvg==,iv:71rt2wOOCQEqiDY659SA67w00180sRzJWs382UDpKSM=,tag:9mlcdULhU6Y3WtbUBJuV/w==,type:comment]
    PROXY_BASE_URL: ENC[AES256_GCM,data:7f/cEU3M6VJx5f5nDjuc4/xaZHIi5+4Pd5TwHFjjzg==,iv:/DNtIDlRyYxRlJQjQizX/3AxwWoHmy7mkPKcoB55MTw=,tag:qoeycE2KSdVyXnlMngbogA==,type:str]
    #ENC[AES256_GCM,data:Zqg2o07mbW5gHnBnUbiVBSS5zYQTY64hZGHgZPq0xlHDd1LA6CYuzh44XoGlmJfywx7vxg==,iv:3JD9exk1Ku8ZZctVTgknbNO2W8QH28TE7YxYD8bIzaU=,tag:s6Y4n0THPjjJ2zU2tIKI3A==,type:comment]
    GENERIC_CLIENT_ID: ENC[AES256_GCM,data:FQeuIeSQUw==,iv:audAXIhwbQ4ypxEdcxWtp8JW2eV9Iyc0Xbf0wkJ/vM8=,tag:ZT6o60kWTn7HjoWoIvUmeQ==,type:str]
    GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:a4UITtud3p3fj12f5inqfTVmjjXkWxplvPg045nPuIAX+AikLg==,iv:H3plsbOc0jxo6A01YeFVcCz4fQxLnYPrurNYe2i5BRo=,tag:GqLvPOqe1mxFHtgeRG0dvQ==,type:str]
    GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:jy8zXvbYVcPKBhTyNHF8EHjHvJs/oUBmWxRgrL6sq50m0AjufnNBXPK7Joj6jJgr7MJYo51fr6togSjR,iv:Qz1e0JeiaQob1VGM3XGFJiwvfV9vnWry/SBwenNaUFI=,tag:bb07tEoUk9qI4Hl5kz7kkg==,type:str]
    GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:rDhk4dX3b20uLOjqMNQH/A2+h17L3WF9VeyPb9/Lgk4Dj2CjU3HGD4UhgehES7qpNvA/aw==,iv:ndrw4xeXnQAhxBSIBRPbzbcGbEf+i9cI0aS740WttRE=,tag:9v4pSZqoG5FX/Mmszk1ilw==,type:str]
    GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:F5t53Cb+QjPA0mcZpJvhRv9nqnQISJKIn7NNCqykvAjV5WAjhgW3kohD2byyMnWAhlVYTzhssw==,iv:lc/qBvLHzvcEA3velJirOEPbCNXRHPM6MVu0ot76jko=,tag:+g/+C6cn6zd+4o8q1gB/pw==,type:str]
    #ENC[AES256_GCM,data:lCq2AYl2Wo8rXfKl3UuidfV9+9xV05rwzJJ/JJiR/38=,iv:p/ndvkodGggFvhWkQw3ZPF5Z7w7ozFHBPO7EH/rkxnQ=,tag:Q99uymJOnqcSNF6PmjS3qA==,type:comment]
    GENERIC_CLIENT_STATE: ENC[AES256_GCM,data:mA9enR5sD4dIGg7hxr8EjZRNVUQmh2I0QwkId1UZzZFkhoCe42iKtyk5lBR+/XdX4EdzrjAG9VEU+ixDsFPr1w==,iv:n8E6FJi/YqOidnGQxBNK5Dn6e/30IO/iajEM+mb+P7I=,tag:hKjvCSk+vsjzN1atKslClA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRnhPemlQUUFFZXBkYWV6
            ZEpXeTZTNVh3N2puUlRWcTc1MHVBYzFJbmpzCnhGNlkxWEVwTlZRei9EVDc3anc1
            aGxOdVNuOG9hODlVQ2hkQU0vWlFZb1UKLS0tIDBqYjFBK2dFcWhoQ04xT2lUZmJQ
            Q0NPL1JCcmFPeW13LytlTXcycTdNTVkKJ7PWHwUph/xS1eajmGq/n9ELQ9Hd612Y
            S6aPW5fR3O1tx7vesxa8gwx13XUNNgaNeg7oPh7YDeOB6xLLTmh/qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T02:19:55Z"
    mac: ENC[AES256_GCM,data:iW35t8sgds6U+AwwMF1lXrhT7/DOuH8fQ2/jvoB0JMblV4Ri5QjSuF+f3TtTp7haYoSbTes9O7Ss9acv6yQepr+fisXHiGffc7m3hzxaUfG07wHA/qobpl6xZ1exZkHUS5rObBNV+l5ucDgCUszUKb1IDgZcXjHKr4TcWz+dJg8=,iv:Mn4wMT01+061+DP1fEa2COrQ3bW2OH8c5tCy23yPRew=,tag:vv/JM9pmm54NDjYtJog4oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
