apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:GnQLaksqIA==,iv:uCjRuIV+6D33NS1g4DgmXlMXLtlbX0aH5NplEodaB6Y=,tag:LKSxRwdf+RZaww1t1UxlcA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ovsEetT1ZQ==,iv:/6afIP4ga5dSoUg9wE+4HjzehUEeESIoZGPwxGrmebA=,tag:oPxyo2Gwb0Ycjzhf9U3/RQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:l+MhaYoIBQsGKCVksIYXjPGRYA==,iv:RvrnaO7tWHHDWK6PzmzgTSj76Jj9mv+YafIN5oqmBBI=,tag:RCZpWjZ0q7dOK8TN+XbWtw==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:tklYZ3hULKrx8ezJyuM3tuFWYgupjwkFPp4lY37ZEtM/WD2EfWVGbuFRFzqBpa5pSKm/XNBNvdumqeBOAhc4D7AWeg==,iv:wnHRlAVJKqUfoI+30YRH0pjkHQ1SwhoDNIlkVCziHSE=,tag:Pekl5cuieQ+XKjPAPH0s/A==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:jkWFzkSse0/JGgNumw6U5ET/kstVCB7hGFN/hzvCJr+CNJq615CbpY2iCn0aC/8H+qMmG+s91e8UG0YJdFdEKvjHqw==,iv:vbaSrLwtIPMJK6MUf7rTNq8OFPT+mj53le/hvuWjzJE=,tag:iGfZBNDruLD3SrHTNwGJsA==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:q4N/6Wr/IQ==,iv:F2/iDbIt6+qSLLgFSbKQ0fflGxZCO6KcIfkkj59V7/8=,tag:mnKBifMF7zF0n1/DPpUvUw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:COdDjyStCcgl,iv:LhdWcuvTYz+MaiBEdQf9d/ADjU9rR08/d3xkS7WLuwo=,tag:QfkqN1U9/oerYCt8Ir/TMQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:6mdDqLfsX9ismRirnuG5t6fHeyGzU5EbVm5bRKeo+fQSczZ9GmAn3tNqfyQ4UEhm2MuDWgeU5frXrB9G1w70seEZCHxXGT6s33C9wWu7g1O4sydiC0bDzGjkpGevHoJq3XuJgW0JnFaixRFPcOJMN2OWrRNUZh+UTfn1WPAaLmajngWV2nnF52imo0/IFtqn47s3wdbF9mTirfC80sY64hiSfps=,iv:Xo7V4G3fsIGwTGERYLJmfNV/vx2a5K7k9aBaCoAxqps=,tag:vUDxXV23qgLCgkepTfxwhA==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:Z2TEsqZzpguMVPwkTXeOw14dM7YN6c6SWKb5ums5v0oHiQ0=,iv:9nmKeMEBl9/RJ/3iAYZZORkfZrGNt6gl0EkG5ZfItWY=,tag:E2Nyit/s/LSHN8HCb8Qm1g==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:5khujDFWim2Feev4CWVyeffBfH8/LWlXiaS/Rd6XGnaCWk15GjpM,iv:3ThilzVBGnTQvY+z+uVjbebpo/FL0XHDtpVwHSms17o=,tag:MI0JWf71io/YfcdI75p09A==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:oImek4Pr7yW3N7KvcLG2f8I=,iv:TBghkL0xiBthR6wdVUtZseQM8hgejvsHgCPccZkphTI=,tag:iCQQ2qkVzkFB+VuOdNlZ/g==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k58k4z2l6ypb4jj+0kKArQU3/cI=,iv:hwGUFCVyAaDqVqhqFXMhqZ44J8ywHROdBzBgXZ3DGx0=,tag:dbAwujU3zdSCj7q7JTLXpw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sC6JdgSwztQtepdFPaFUECsEiWfb/3djVTFrk7BYoNeKZEmNV7SGXA==,iv:yrQdf+LqsQKEuihqw3J/j59RU8KwZpnH3IahqWGMiHE=,tag:GMTcOICKc+t36bYnopFxUw==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:lwF3IzZfyViC,iv:7DRBnN7ZdNVmn4nDvAYKuzBYvAuZoUdJRp1CECgQnfc=,tag:PkcBJvqfUo/IY7qzUqX0tg==,type:str]
    drop_params: ENC[AES256_GCM,data:smVmXA==,iv:1Zq3rLlUufbmGDtEdT/WoMIzk1uOelyMrUY5RUimMuY=,tag:BiK4Ly0UxY2PnKGVBBh2uQ==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:t6mOll1b/7DJQPV+yTMlSdSj6gnsaFI3Z+7vvtB7kA==,iv:+IyzMKg4E5jqYVN3woS59zNcc1I0fCsIkpdmIHM1U8o=,tag:sPXn4bTOPzJFyy8ZjvSY1g==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:JefhPNdjJNFWXNNjqx6yKCUNqbBgJvMfqSmsa6tsdiIZfzixGKN+Pe5xHEoaigWNeg==,iv:1tiOeFkvGwOen1YjmMVti8HiOuph3XFPLAebf6/vGs0=,tag:Dj5invB4Nq9/Kj65rcGQuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbVYyOHRqUHVCZ0ZNSysr
            UERxU1BmU0xYU1JSbjhCUEl0bUFXTC81b1gwCmVQWUVhMUw4azZabFlXbHUzMFZU
            aE9uano3SHR5ZExMR0xGSGxPdkFVL2cKLS0tIFVaOEF1SnF0ZzR1VXg0cDkyZ2Z0
            U3NGUWtyeXo5Q255SFlNNnBESGc4NzgKyAJ69sr85CjsCOr8xCuI6JBfKD3WH4YJ
            aI1XrNyNxm6+FV1CwzIhPvYlot+HXK50wKqmyut4UShOR69bUGU0HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T07:23:38Z"
    mac: ENC[AES256_GCM,data:TetP/n4OY6lLmss9/kytLNnywJnncWogyFvoeLaVTJORfFgvZ2A2qX9lRfgGPPHX/Q/bYkT3ZHPK2tLWixoG4d9zy35QC0uXPVm2E14fgvDkD4a7/fx5b3ntsZjSac+P2HbniYAnQPi7fNHqz0qo1BLpEUd2/ButJlN8E3XRfBI=,iv:1Eb3JaemiiWtTUIUgd5Csf/0KkOZoa32aeFzd6xw210=,tag:2wEE9HX7zcLJQXr4uOW75w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
