apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ls26w9RMtw==,iv:vtRDxyh7p+rzWublAsVEK7piOTpz4BxQhxjE1BJmqCA=,tag:zKEueAkQqUJlBFDX1Qw1yg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ipL/7+rTDQ==,iv:t8W9C5bjX4yZyc0/fFpJS4c1xsO+fyWk0jL2yl3aKn0=,tag:vMZtr+FXy/DlxC0LsekZQw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yKC+Fhn+coMNTVr5dpNY60mMvQ==,iv:mMPOhDhYlfH++4BsGIByTIalAmssiAPRg2M0YujjmoA=,tag:zcNT5bwjtzadkxaibxaQiw==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:rHEOs+ybO171sANwaMbpCZ/8iGDcgBNCI/fE1wydkNzYpgoKIHM1h647pwyB8scUWnPqzSQ+scYWKpCfnOzK34IAWw==,iv:7ig7P45fP5gIevas7baWsVMhUkqhSCOMHT3IE1nYdFo=,tag:QPBHOFhp/dY5dx1qxUgXbg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:2jLI7IST9VlKarAzb4NYrA5k2umkbZnAHA7tPXIztNDOvYP1/QAKDF9KYDXHa6dsPM1ZPuAKOw/ShNB+d25zjIeQOg==,iv:WlE2O8/8EomDrpGZwigyI55vtaZi7tdxZ/drE38E0d8=,tag:aIlcqpCYN6dHZKl80GIHaw==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:zfzPB8+NDQ==,iv:1vy6nmkhK7FG8mbeAV8ON/TC5NXkrjIL8MX/dzrcXjI=,tag:kHhbXYb60nT13Bnb+QegBQ==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:ALKe8YhpG2iZ,iv:cxkwXCAy/BGh1SDgt/QE5IzGzEXzyo9a5BmkEIQwAks=,tag:JJRmzEBG6dCdbAwKB4z+Xg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:shGY06vreHMXGIyfzoyIewLMejS/n3boWRYPD7dMRVcINYL3aYDAAQhvvkZeKzQkpuMRYaSPClGuu+m06Rcd0vIBbbA0Njt0uUQpLBHY7e3u13S5tPHtG8uBze8k2Yuue5msaOHhk8mueOLMi6f0ypenMbabCj5jHFKzABq2YxO0ASNwxGsMCtRNaib7DL9bYgBOh39GUQ9Zlj28fxLEy/oN6bg=,iv:gzZEro2FbdPuzMztrSsB6wrh3uVs86MlalOVNTKgLnI=,tag:A/oyc+2Mo90dw21j41BAPQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:FSFRGSJNoVwhA5LqdzK42TGqJvF7FCqR5Cz/rI+ZqWLH7YU=,iv:x5PFZCID8BmQHCcIBq/lfKKFxyXwQBwZqXPRWD+j0gM=,tag:gsw6E4uFKe54IwDB97zcxw==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:WG3fc/g22hpuUCfr0i1jcImpGEF2ce1aUPwNm0WsUQjfDLyfkjHl,iv:Uawv3uNPu/Q/xGEaD1OblpRS09bGHiIt2hZ24FjdCkQ=,tag:4KtpIQk0RTOAV5L86OqxAQ==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:0Wcy5TZbas1TO+XllbYa2E4=,iv:8vem+1xe3G1tC3SpaoHfoXc/V++Bilrj/2g3ZIUPiak=,tag:8iqtjd4lQiaQHgjxN5IBlQ==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RqGqerx/UwCwSVN5ALYeO8c6QfQ=,iv:19x4EdvZ1yS+JoutMoc77322FRQEp1fndTG85P6SDS8=,tag:Jy/fFk12G0clHtIufJGeGA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yyVkgMhePg5C8os9V2VIbQFSYVmJk1I+S/kdHCUX9qh2eNosjlqXYg==,iv:feA7ZVCMQiZItsPqAA/coM0dO6cRR1cil6X19VHj3Z0=,tag:uuoR3/IoNezQZHPRFn89Sw==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:ScHTFdGPUJek,iv:v1gwBJCl3GqdCG6o1k7taMArxO7U78YbSD5vK3CvYLs=,tag:W/gF9nanbOhpEX1pzfvqsw==,type:str]
    drop_params: ENC[AES256_GCM,data:M5xpxw==,iv:y8pekoUwuD+58pIbqlHfwlIFIH5AZnnB1K10xvtKoEw=,tag:mdFkOhteg0PrpkDdJk2olg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:sZy5WzbauWKp6ohbO+5G4RGycgFT9OA0FgS2gflSOQ==,iv:kIzk/cLM6krA87yWJnwDu3JopSxURXK9twjs45QiaCU=,tag:yspEKIJf/UKiZYlUGdKU9w==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:O5+7Fj5UH2A2kB7WuQ7VooWnRzH4bokrzFO4dcLCCFocEsW8WJi1DhofLpUqI4Ea1A==,iv:SwvizM1dAP6NmbQRdy2l8eXM7KDVJC6Osp5qSUTYlFw=,tag:K0KeT4Y7kTMzPXniViYIaw==,type:str]
    #ENC[AES256_GCM,data:YY/QWwph+qAEBBD0ZFKG2Z17b41L0p2Img==,iv:JMw46hwfO7ZXsrfjJZLjy/htMxP+0zk5lasSRhsFbcQ=,tag:VLqg97vnNQKgG38ZNyWjcA==,type:comment]
    PROXY_BASE_URL: ENC[AES256_GCM,data:cR8gfQctmD9Cju3L9RTzAXmHxfiR5D67XsvvmqTqFg==,iv:VNW00BU5+fUkgAYDTpnjBhAcPtssdKWlZ5i+sS7sk54=,tag:mOeL8qWQZnVGrURCe+NzYA==,type:str]
    #ENC[AES256_GCM,data:TAGtGq5BuGVQu13W8ZYuEkwomE8oZaFfaYYaW+5Qw6D2LkiikfHXO26AoMKwQRyg2kuuhg==,iv:rhnFox7f4hy7YbJMGO093X4nw+o/M7/Sqv8W7i6Fy8U=,tag:JBz7TPvgNHrX6ypaXqhXXw==,type:comment]
    GENERIC_CLIENT_ID: ENC[AES256_GCM,data:acLGzZp3cw==,iv:IfQ8SQsCLUDFmKUHKuDbMAfM8KY0qq7Nal2CqWRH1vI=,tag:4/UkgsLYKma8HxgfJhvZWw==,type:str]
    GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:75a29nFAhYs5lZZJueEmcvKZPI5ZPR+a3FK4RofWx0ijRv/hsw==,iv:HuLbYqCpiCu9XtAIQ/okjUMwgm1K814+ZaQb4tSh+Xs=,tag:9hCf/+WBQc2P0AAadKucCA==,type:str]
    GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:Z8jBEwqj/2pQBUQYzBBjQ87frq9ixStvLcFpRTP2SRHU9hSxN5alA5r4RREFP+K/dmUxUS697ciqoVGA,iv:3vkp3ykxoqFz2OQVKyANzbLRtjmaBokVKohQBd/JAR0=,tag:U42v0lzZaetrxZDU8Jk6pA==,type:str]
    GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:UYg8eLiVb6C0HAsE921GjKpWrxk5/+Vtp1OuEaMwNAJ5fPtgB4yaioBmW0KE0UIFemMwnw==,iv:GdEeHCNLF4+Ry1cT6pGnDHXgt+WfXDQGLnVncnkXvw8=,tag:/R2M9t8DAfgTnCoG3jzLDQ==,type:str]
    GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:SH1lDHp4RvlK2n5sVdzjBXavGNreQvWjo2OEdYnb2ddyX1Swb4A5CvlEl7zJ14CPcSzwCzy3kA==,iv:3/23ITiN9wVAPhcFdJOmliUu7F98seLrwCnauq+fpBs=,tag:emr1tpqqbDb3WFZ516utww==,type:str]
    #ENC[AES256_GCM,data:a2grOxl5J74UJ1+tO/IvQYIOfQcPxbMmtiYgETKfu/4=,iv:lLq5hSVAaHeBKm2ZTw8SkS0/4rP2EJauXMCNe4KJ1+0=,tag:K47kSjzkJsLTcTijz93CLw==,type:comment]
    GENERIC_CLIENT_STATE: ENC[AES256_GCM,data:HjEPF7UDTiRpCW1eCXqyreXGjwm+KiOI1HKRoqRLJvW296Vg7TaBHHd3+KSUllDpN39g2GzcTNHUtqmS9gRsnQ==,iv:f8Xj/F3BXgQAAH6p9yCxQPEihijU/4cB0FvUkuiq0m0=,tag:YVG6z210/GA9CL/5mtZIqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSjhNOXpJTnp4UjY5Mi9o
            bVNtMHZJYk9jRkRYTDhDaUNybStHL3dYSjFjCkJkZUxLYVI3ckRhR0ZDeW9yeno3
            emlvdURNNGZ2MnRGZlMrdXBsMUxxWkEKLS0tIC9JcERob05tVndRbWhNbHd3WjVH
            MjFqYTZDTXZ0TFMzeEVLdFVSbzFGMWsKfIp/wuSA6IOVtO/WEtwOIp8MOnWRyssf
            zmHb78v69MhNcfRovyKm2c5OPrsZgPkFrcXox8oZw1h52zaDCBqumA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T02:04:05Z"
    mac: ENC[AES256_GCM,data:Da+EXNRnuE86JF9wDPZ/pqnifXoTFAvVedsGuzCeYF66i94sPN2PXDcUS9lBMROq8EzVHP6edvUB6bgd6cIPqB5hEYFzM8OEgqS2QHy+wNp1PUIPbk5MEkIJUqzgpQXX6K2jiWuRpgyvP7WcdMyXZ2mVkHcrbifJbFuVvmgDHA4=,iv:wlJq5CPWoDWRLUPyUYZj2bwzVXqIPtcDC3xqoEXR2gE=,tag:4sUgdg/kN2ZboIoprNuTeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
