apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:yr+6t29hcg==,iv:RDGv9DfBneYJL7ySzcSEW/JEWPaiNDkImAArDxkR6LA=,tag:j51x3MoYV/uz2XIYp0+eAw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mL38U58Q7w==,iv:kTvPcJA/W8e4KXdbnvrfmPE6IZeUpydCVWSrLQVyUgQ=,tag:wFc9NC6A5IR2LrHHtiwRQA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7yBPGWSZR3yAN/CzxgcP1Xnhuw==,iv:RFnsFEs4YDhBI1ezsx1FBYOFH9+s/zSoo14879REcfI=,tag:fZN1DIVTk10BVaIIOKP41w==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:qAunlLEwWzrqZIq6WoTvRWKBoquvrbxXGpQnzoitYxujK7992ysOMDGufUUk43CHkhNY0b1v9MMOKDZ8COLWzqpO3Q==,iv:w+MVQcjnP/6CR//PBSgm5LWII36nih5e+rEaeT0plPo=,tag:LOKOrXak39lEUaFiEuedvA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:l4NympMi81o60luhGZ3XwlStvmleZO3AsOk0cet06QeYCkaSlOR6p6YJSTSo28EfcFJ5B7xSB1VtQpHj6wOS3NLtTQ==,iv:9P8H6GlVe5/nD5UmIfyQdTEfov2KHU26PaUQUB3nMtk=,tag:TahTU7wg/Cmev1+nQBlF+Q==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:LILPWuXEBw==,iv:7peH1EKCXshcxoSh2UEI9nFc1UE95SN0Bwc2e8uOC4I=,tag:nrYlmNS4QxiV+QDrVTqyRA==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:zTPWcBIfv9ro,iv:4TUYhKhHelHzC88I5vo55o9IvTGz5hUAa33dgQPQzGs=,tag:0oRCYzak06ncXM9aLD/7gg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:CPMGfLCP30IbeLKov/h4R19E5rPjWDl80g9HlEMRDM23rQv6HtGenSTh/wMAjc/zP2D/NRkeZZ5t95eblYBhQa79YNeBpX42lLCeSol/yn27yOCylrn/PR1g+OUI+3W2iEMbop4Y3PCqFEOVUg/kv1ID0yGCEwEy9s2aANB4n0jw7BjhF3PEinpLoGCfpBPYaqJ7qKf14ei15G8FY70aXtyNU3Y=,iv:LOdbCNHtdpxxToSZXufniYkBW/Mf4NZiGGQyeltESKU=,tag:hySeYx38eE1PXJidWXUhVQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:DFd+FlC8V/Y8m8lmjw9j1JpUCn2nXD3R66bf1977Pj4SMuI=,iv:WCm+mr917qLeEa0SHIN9bKT3WAkHdG3se4Z9OFGqmIE=,tag:azKFmkKp1rEitU/nXVywZw==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:3kFaG8+d70RbmqztJjAMM90bsOm04QxPz220ktWDObdhmhyjT6rR,iv:6s1DP5VEyFaYrv6eKtTrqzEf2vcN2PDXyKAcoEDaSQU=,tag:w4VfU4DdwgJskWCBw7zKtg==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:EBii5qcey+LjbuWe6rNIJ3Y=,iv:g8zQ76IxbMvDfd0IkZS4U90sQ/XqDQ3bqrwn04/HL3U=,tag:Df1iZ2bUd8IDXiXy+E9R5Q==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JjflvG7IqppzU4CcNGwr+aihk8o=,iv:7sKAd+UxDeNyM38LFatSXgoE9QNv04vk9D+gciGVBpI=,tag:CyIPi1U0QeKquDNA44iDag==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rm+2Halbwy/r+RsXFNrZBs3FuRVBClvUon9oVFWX1S4bYg8qT409wQ==,iv:3LIFze8vWyoMUZT1uLe/feTB/3d3UaQpqoc+V5J2gV4=,tag:b6f2dyZiN1iF/E+S5DwbgQ==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:h2xbdUXZluIN,iv:QqPbQ7+oXdUQW1T9zI1tPY/2uwWopwBBeJpKa7Gpj3Y=,tag:tm7RyAQvZrT/pnjYbkydKw==,type:str]
    drop_params: ENC[AES256_GCM,data:cuqlkg==,iv:O57chBWkTxLPX8bfZS2dPpmQztqIjnu+M8iF8ftMc/c=,tag:qhrjWl/cKv7ANyPN5+quNg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:mhMrC6rrkj9ZKe98k6FMykz1PI5OFoUGS1P+w17Ozw==,iv:LlMFIoNcGeEhDnYhHbvBRkMlhBFXXoKvYy1+fgvIYXI=,tag:1Ubo/SVYVDdDmzzyKTBfqw==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:tn5nh7JeybeTXLwZ/NUADasLcC1j0wlWhn/hEOqr84Ojl33Kp/e43if/+jyAKBkLFg==,iv:r74pE8ghriBtoiX9P2ZBfFug6n0KCC4EUAsqCPFPypA=,tag:OG6wzGQavB3XkUgfNJuW+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVEZGRWpnbU9PZDRiZnVP
            cDJ6OTY3aDY0VzdBV090LzVlaWFQOFltZjJNCmR2SGF4TnBFQUZDaEtaSW9wWElL
            R3FOVEFYOHd0bWp6ZFBnalBlYU02WVkKLS0tIEVaRXBGUENPNldiQ1VzdjR4ZTBY
            QjN3MjRNZDlVNDVxOXRLY2x0ZHFNWEkKbmb1gVZZcERJeBPtGw/qUa8EVmM8yF0s
            VWghEU9jcK+WfuHwNfwsxKXjqztxJIsvZHfgGuq5PM5f7WQsFAS9NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:39:54Z"
    mac: ENC[AES256_GCM,data:Pq1mdX2IdHrnO8zm0k/EpXGfAnSpbe5ayFpn7+bBALqtnvyoVg6Q5qGupV5GV/A6+6afj0DiOVX25G9froZqL76ZYM8X49zGjBB0QNwXMQRY0pWbcQtvacNxtWJ1pBX0DM4/LK4gW7/BlnjMmXr71fbfZYdQ3OuiHZMizPzSA7o=,iv:Z7qrfR7FjmvFTl8DrFmaPc7IY8IGodpM5BLbyY7jS0M=,tag:vzpuVJuwfVn6lHdjGgU0oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
