apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QUOYLqDmag==,iv:ohjul8mHO5VclfSuIqomcWUXFv1+aAED0q7tycOoHDw=,tag:TklspHXyvFIqxB8v1QJmjw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:dFQ66+kjLw==,iv:8quPRcV07AUB/S1s7Cs1JBOEwFaB7iTXo5OXMogwfeU=,tag:YbuhAtosdKkih6KZgEaBfg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZxX3kJXkukMNrRof8JKZxXrNbw==,iv:pcXEnTDt7z3UtlIY9Bz5bW0v890mczlF0zRXmvBO36E=,tag:NlNBmk6qt5Am7VCWik73GA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:XFzHYtem8lfZlNQlk0iN2gWAXS98s5ZuLJpQ3HTfmZirKqk701A3vtQhZzrDSFY180DrXAW7m/RXqCLDyAhWkawlkg==,iv:Mv8g/QOHsQ3Uv3YppV1vGED/OBXhyJzWX0vGegefTPE=,tag:CWIR4TZ1+HE35t9kw4G75w==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:7pkSuLym6UHC7bIiWwy3Pc2tBM2KPGTPV34irVnPtgO11e+5wYLjFBCnihHEShykQ4ll8ykexf1P3Qxiomjw5cOm6A==,iv:SW78JvwocIEkBSoGmFdsIgxGNtJ2DL4yB/I5TOcIZtQ=,tag:k1yT2ydv2MalqCV2xWQBvA==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:oRbLPwXE9w==,iv:pTjC+y2KSIjBX7DkxM6jB4K2JaIiYwiM/f7KUMrwmTE=,tag:cmfT0jGJu8ca2gafhiRayA==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:WqKH7j15lHbp,iv:DyNCs2SfiSgozpxSBZ+5breYY0Sf0tAuorL5Ths8G/o=,tag:1oqV3o5O+dosiF/pZ1vz/w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:F0ZSoqIIDCGiQQCTnp7mCx9pMaeUJiJiuKOpwmRcNH52yXqcd6U0RSSdDZo7YLSV1HClMPn4yWiqgKkT7MmXL72akAipVZJcJtBqRgiikKENqpZYha7c+Iw18nmNXlhibU7QbRpgKssHko0LsLQj0wRzNOXtxrcJmRuIOotRjQqZq8d4vad3Zu9yZdAMzxV3095/k/VTeUq1iVMumoI66s8R2VQ=,iv:HlqlX39dhLV/oNpLvuOH/2lo7s3nFbz6V7N/0VI9wxo=,tag:a37F+q8iD9TPWAua14fADQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:X8O8krer5d+S1c57kli0B7155m8OpTGhZSJ0PPYd7lgCx9k=,iv:OetMWfMEmCZwa6YZ/8t9pJ/WfAQUq0s+BGLTFH151kk=,tag:gpHB8EU8elbsTQrBTGfHvQ==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:KEdgY2zZOPDTkPa40NH1LSWtWKYwc5C97mXPWNW9oMy/I3uzhEKA,iv:OKM927U9XpbykrptkhrUPnQs29rV4lJ5Ip4l4ablrIo=,tag:gt4NlKGlRJdlTWQFeSpfUw==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:ywI2SBblDQaKFzAHd2hHxS4=,iv:YAIZMVVXJDMrtsd8syzfhZFsbcdnG4mM8ZBO3sZoxls=,tag:nzZ9X5PL7lVQWDxN3OfByg==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gKZ4W9G7SYCHpSOYr4sLyD5bRCw=,iv:xZpwL+B+IStQakSXfIkcKSNk5AP+Em9KEf3r6W/mnDk=,tag:726Cs+cToxMxP7JzvYY2hg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sCDLTeAsZBeqR/FmEj01jDlDIz26jGOwG5ovwiDlHjGkv2BwzV2MQA==,iv:H80wXYn1H8mZcB4ZWyt4B4LR/alafC94gAN6t4ewqQQ=,tag:FhgXK1WTvcFdECkrubLk/Q==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:7fsR61nbJ7Id,iv:KBwaiSpqcbTSnUERNVNJZWJWYNf3on4cskkfC+ds70I=,tag:vJTTKqFENCcU0CM4/E/HXA==,type:str]
    drop_params: ENC[AES256_GCM,data:Kuupjw==,iv:dSJPNaAJBAMfddLRCi9SniXLuUJnv0GXbJZ0VEySU9o=,tag:U9cvQ4mxglxhhbQ58lV9yg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:YVJZxfaoCGO2tNDdetR/JEXMpVMuIy1uwVghhlz8XQ==,iv:iLLpFoyqVZOjcTgpBftti9DnzxP3G21skFu/vf0YBX4=,tag:+IO4oD4h/p9+is/OknDd4g==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:TDGXPj83opIBnMAOgJGU8zEMuGr4U+uN4te+b4mPjdCzApBT3jxutQKtpi/0kFyUZQ==,iv:brEdPPRGvykZ5acwbe2fzfsRlXPDDDaIzavgGwUPvG0=,tag:HagGGdjLjuASnI1ILdsvEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva3VpcGlsVXUvdFBRVWJn
            L0I1bU1sWDVPTFRBVzlUa1FPZHloVVc3VERjCnVSbVJudzJoTlVqS0QwVXBDbmgz
            QVlBNDJUalgxVStwUkR1Smdiam9yZ3cKLS0tIDNZVEFBM3dZSkZLeUs0RWh3L053
            dit6RnJZc3VISG9IUDFPRjRoUjZUcncKQ44VAzGjnFTAG5HdpOYMbjitiGiZzl0D
            N3NIj0ekk6JLkScZJrD5r+uWVowpKeD4r3KDepWIM0MZmy/TiXXLpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T01:17:00Z"
    mac: ENC[AES256_GCM,data:WSEPWvCUojVdtUXo5W8IjT4hmk87jIKMhHqglA2cms5BoyXSi4cy1F9yiGDmrs+kRlInt7x/NUOhUjaUg35gqFJpzGYEIOLRrzDjCOBbol087TIAAlE25Od26sjKzNNZOGTSJVLcr/QLigDvhzWoNKwBHHiClJhuKlS8WMWZEd8=,iv:aIxtwbQFs3/Up6u3El8/XnwXs8bKKdD6w4TMA22hQ0Q=,tag:8WdmZIuEWmz83Vv73t1sZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
