apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Wq/XFCnaIQ==,iv:YTn366c3gBWS9eVt6yd8AheEYhwg9dSEoReuFpsigxw=,tag:at6J6ipT02o6Xtl/IsEd5g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xbpRQENs4g==,iv:voA5dYJFvOY37tIkcvBXI9PNEOAYCnQreR5Ywtk0iJ0=,tag:DHyv0X6hDpBoBQMGIfu17A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:jc7Q24MuHe7JEViqAr0qT2A8qg==,iv:1YeZxHVlMQC12W5yTLtywovCUxEDI+GLPczHnN/m7qo=,tag:Pz0UDR7ffBY/41vkNi4iYg==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:RMUktFaUFTsIuUmsnmjfgxU0lc7fxJH+Y1hJ8XUWpWux1sqmlXg6fOfuzM1NkqBkCCoJkoLRTS87POVocc7ZoZTfNQ==,iv:+gQMX8TfitHM59mCqnppP1LUCRMpC8Dq4vO+ZzhlvQg=,tag:ljLg4r8EXNDuaf2fXe1dUw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:H2HhHmfKiFMNg5u4SvvJNjB120uRmAhY8Gih0SrZKWGPuB0zwJteYOgTnCN8AjBDSzlMiTBO5vyUpOebMy6GSxIwoA==,iv:HmXVhwZdUsxa9GhPmeXWHD/lYsDCPAm2DyfAGzsJ4H0=,tag:RcEZ1f1UGLCC+NvZsIs1TQ==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:tyUgKTd2ZQ==,iv:kD3VdcAvv83LJoiYv7OaMHx0PIOmrDq6RIIX1JddcLM=,tag:PSzPuSeZz+Yh2Q3b1FPJZQ==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:muhVE4oBas9+,iv:QiuXOYKR7e1eYi/NYXi7roWcAK7ZL6ravPRn4oe9z3A=,tag:kGD4CcY+ZqAzp2M2DZiJXA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:AEa2vRegG5MshmRgBRQKfHojKVhZTTuLFg0Oxt1HVkSaz3wzvJgvH1Bv+3bha0KpiutKFi4pSow9luiUHxy9h6BW8EOXRV/zxZp6Y2t73xhemwqj7a7WK6VB+gJBydplKnkW7e6a1eaAuWl4NFddXLr6bq7cHlwExLxuIDTl2XI7ikbGHbK5CVHWaunTWYpN/kRpqcbBkcK4MxbvIx3uIBIFAfI=,iv:CaSFqClvc0Cu5n4NTgcS/1BHUznPSZHRfH5RFYz6aWY=,tag:zMNUNmQx+cEd+yBnb1nJuQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:mdqeJ8ldG64+sUtPj/egV8F+2DBIkjE4ZXONp4gx7qfN9U4=,iv:CYkY6n9fFbfRCwK7v8WcpHjlcaSnO9c7GbXktrhe4kQ=,tag:xV/U0x16Wv8YM61IIIBKvw==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:vAd6Wi0e6IOUAbILtq3KyVVACwIq0pM7yay9kp0iOntoRuBGBOMu,iv:1/3WWJqEGsbRThvQBtsK6UCMTAhR5+Apck88TuXDvDA=,tag:n3HfmOEDkGY/KWx/2tM/lg==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:vFhMNE409GWCDsY8ukYfsKo=,iv:PeDHyh9uMq3BW7pEesCqawAiv1a/D4Nh0+cQ4Q2oy08=,tag:sdRjYPu+L6DsGvxRhBEQ8g==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8XQmRlx/SXiJY7fbty4tzzDpkX8=,iv:RwUkHJTG7PjjDS/1XZyXiW0FRNu1YZ4UgSCoBs1rfnk=,tag:kphRQXRNO9i5mvMSQ1gvsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1+v194HWC+2DvjUuhiuMg04Y9grb6DVMd58r/jbUFCk1emJf5UkL0Q==,iv:z4r7TsMnEw3iOe3KjWMllVfoD93KSzJUyECA2vfJCm8=,tag:IjuEKHzyhaoqVERDtp+Iyw==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:3cUUrHRkIvWg,iv:MVLhi9cK/2Yq+ZgJnmA3h6FlHQNtNJi94lSpQb5rPqg=,tag:kC0lpa35inZQfxfch3ctwQ==,type:str]
    drop_params: ENC[AES256_GCM,data:D4FPyg==,iv:kEDFgRZMv1cy0hfiO9Qmbj8QUU4z1duY3JVurVcPNpo=,tag:g+8Xaw62rN80aP1T38oa9A==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:69B78xywLdnnO4Ei5vlkymrkZhcdGlRgXmxuw4w2ZQ==,iv:1/oMN43v06lx3tEOeFJN12IntqstiPcAgDmhYML+zjw=,tag:9k3zNJOrWKQdB7gGRNs43A==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:rtkw/QPxvQu6Tjn//GkIgj6C6kyFZ+zjnaXySbkBrznNkPiJW9NoA3+T5OYyRJdchQ==,iv:nUXcLrw3WGZ6nemLyEQCaOmlwNOR/8UP75jIAIg8/ug=,tag:l+9IPaFpFqk2UBsacOB4eQ==,type:str]
    #ENC[AES256_GCM,data:l2U7wyz9MdxcXQEPAMibIk9c89yp3GO0sw==,iv:qp4egawktFAW02FjKB1UZhDR0n83F72Fo8w23CtFG1w=,tag:Abk3zsvS4xlAya0uV18xig==,type:comment]
    PROXY_BASE_URL: ENC[AES256_GCM,data:hXJFqgOEWShxLTyjEuxQn+k2R2f1qy2+rXY59qvwtw==,iv:B52kVkza37DD8G3ah9wqe9bH+4aqpO84B3pB3c8fZXE=,tag:cPIQREaeOr0+4F0mTNH0vg==,type:str]
    #ENC[AES256_GCM,data:yh8xTxcINu36DGWIyaUHmcuZDWIp01Y+BgVK+k9mYZ5KmwU3J2EOs/xTUNtsGPFI9GdAPQ==,iv:HyYbM4aE4brpRRT0EZCpLhPrMjMfP7SIqtwDZnJGXI4=,tag:x635E3K3C0pOTTJUc0YL3A==,type:comment]
    GENERIC_CLIENT_ID: ENC[AES256_GCM,data:hkD+Y/O7qg==,iv:PWq86BUJy79xVGxIVkVkCE7UV5Ub00BQ9+vX7kVZPPs=,tag:Dc4nIVypvh6GsBZvgsGulA==,type:str]
    GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:Akp01oFb5ZBNA4sBH2jBGc2fjqj9tXgyuWJSDFL1612QTla40Q==,iv:fPpctm7FVFPPAN3tVgX5jmDRiTz7Pq7RLzdejiGlb2k=,tag:61DJ1DCAGiwEJbQWQVTdbw==,type:str]
    GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:aSBsk8h4xgwoUNQ+k8XYpjUTIW/dEXInKfITL40jpPr1UxPaUwzMOrVYKyzivDvazbSCiWUVDpdd5Ap0,iv:8b1RSthPgEIHGVGkq+bJZl8olllS0D58tI0+dkRnylQ=,tag:J3Ddek9GZw5AskU7YHR8GA==,type:str]
    GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:JHzZMcjtfSh4Z7RrvDtZ02hWTbNTUIKD8tgs44hCZleqmkJ2FYLyCics3UI64ztIH2HttQ==,iv:FBxJNYGTK8XiQKKplIOXty7BKS4lSziePYhkLdcJZGY=,tag:NWs+AYyWJgrgaA1eF5IkCg==,type:str]
    GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:S6S32qAkhD/HnrsrGqKgnnNNDeFoxW8Q5v//M4/9+DKgcnpougLNUhTlah5jMtjlS8I+IvyrIw==,iv:CvHbR9xC2h085xBWiCN8UvkI8St8OtSJ+Q7RfxsN4B0=,tag:iyhSvXsuF7QwUp9lvyUiFQ==,type:str]
    #ENC[AES256_GCM,data:Q8VU6ciOE0FGTN6PVvKA5xK4Q+z396TbpfBaGNSCZRk=,iv:CO6MZ/31tzG7A/SLRG/1EEpuua8/batAZAh+aH3gTE8=,tag:i9f1MMvr0J0xLTVwbfjpEQ==,type:comment]
    GENERIC_CLIENT_STATE: ENC[AES256_GCM,data:pt3IikPc7bWo/ELfuKRpUGvVsxq/odNc65gAgkFYamB6wfZywID8qPoH8NgSDshXRHse6edUzUwLtFs7Vo5Bpg==,iv:YeKLVZM1PcCjU5bb+MruQnIePo2BfCrgEmhiiBLM2uA=,tag:BY21+dJrhjS3UkI0w1PSgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETXpLZ3h2elZIZzVFM2tV
            YnNxZzV2RkFrSWowNFR1RzZDVGlGcW5QZzBjCmIvTUN3YS92SCt1dUwyOGFQbm1N
            RFZJWmNsOEVXRGNEczF5b0NUbkprcU0KLS0tIGRmTk1EZ28rUmlmN2QxeWxrbjRy
            YzdVUjBDZ2tSTEJUek8zOFBkMUZ2SVkKMWUArKPwagtSn3Mu44t6Xc70BuTsIZVj
            D/8W1vqIcGRb/wWD6p3TA7W7zdAEOFT5ma/aX3nmBtCfNscpLIxqZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T07:15:20Z"
    mac: ENC[AES256_GCM,data:G0pHKf+eIBgx3V8oRgtZYe+x8GSiw3PKYRk+J4CXmqzgvQyKvIgx2gnIfnCArMYs9vUHZ3nPklIJy1E7GukBt1CFff/VnB0Uoz4QnKlzcKUl8jU0tFAFS8XlbnAgUpJhjrX1cHbxG7XbIgMY50OG7Zixz/ikQRRygLZC3LGntK0=,iv:p39BszNQxSLc2Ej8+SojWTuM00j47FQoKXkI7JHTR3c=,tag:Exm40HhzshtDZ3Zng3y3rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
