apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:EsLWrG2Lcw==,iv:K/9ga+2x5dSbq+WfK5imMC6PiMFwusp4NiOO7MG48WA=,tag:4tLFjwyFXKnVXKCZdqF67A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Oq2MZkOn6A==,iv:hEpnZQWG8IjUMJfZL0dk4HP1A2H3hIdr+DB0mkGnQkc=,tag:3TTYK+z2urdhH9s1hyeTBw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:s7cOgNRQoJpi2bc4Q08G3++rJg==,iv:pgowKbSWslx6qbcYAzhWl25Ep5BCb9t7S9Dd5+nza3E=,tag:MlVjhwRkgo04gWxe96Rd0Q==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:CqXtqT05+oX/wqKnpARiS70e8ZNKJGKS66pnm6b23fJIt5XXf3nddEjgHUVbPww9/racJPhCdlgQH+SWSyedMha2HQ==,iv:VLPTu8O3FjIk/qZKa4lSA8LiDOXr5ZG8ZmwzD/01yq8=,tag:nVnFGvGq5PBB2jxtmXr+Wg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:EFJon9twW55CR3O6JtPWMR1Lre13CC2W26EN/Fxufm8qIkUK+JYwJDbmoX9EF3+31piRfksdI3bj9LZMz9/xcSy+4A==,iv:4AM1dH5Sh6Z/31mohQlxk5cHPvebftJT7gztJjKWZxY=,tag:D7hlYBsDN3wvubI/MBbB5w==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:lojg00lXKw==,iv:Ms4MlzDfHUI8RxcPObWNkfiYov1WxQZDog97hty7OW8=,tag:1wi41B9E4HIw0fVEMqBYxQ==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:mH6XHJYcggr9,iv:hccrWK+eKKubYY29fXZaP3b4qJtC/A/YhSESc4x/i+s=,tag:NnYaKsEUNSP8dXMNuMcUAA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:ndETRQzo7NMlH0N48S+wVhmKgt4jocmDy1fpqryfa1obgC5y0bPRia4JsnHn/zQwx0gRbjNRO76gz1eBQj5wonbjH8XZrJaXNO+isZvpFPk6w/8bTlKBfREiQTEcLszMw+3k2HXrR7ApJPbOFGJhFdNXJN5GuiNKrVcCSg1V3/470Bcn1qVCCzMqGVowFQd0yg9XSWSGLkRswTaIZLZRUbKxGZ4=,iv:9S+9G0OsBkrEgtL6A9/TJLWyG3BnYD+01jn0Liqs5hk=,tag:G/pnghfEE5+E8ho4AH/ZQQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:+woTDPOmDPowMfr/S5UnCNPyv9KZhNMwv0UD/VP3UnosopI=,iv:3TEEwVHr7kGz0/vX7QwSR95UP7rlQe88HBqCcgkpMjg=,tag:+tFkwybgzntZGk0hMGBTpg==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:vatootEtqqzO3/iKD4aBFDxUGgDn4el+daOwHoRxxIZAA3jnyEZ+,iv:8BeXSguLrQGirldjjMNeAHy6LCZAdO/TgtTxmK/VhvM=,tag:lgNNlX7VMHeap0ioK1XiBw==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:ld5qK3kzA+allgeXVafReUI=,iv:8Pj7SaKH/cXqU33GHFIZc2W7QxzApe5jZ7kU4kj+maU=,tag:9perOeXLsf7rv+5zCe1RTg==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lTgbs16kLq1bNGV5LJWC6jXrcMc=,iv:2ONvcuh6ftEqQYiCqs9NnWSyCaecBXr/6YwtGCZP/jg=,tag:4hcgYQE1R+MNM/2HrNpmXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rL9QFKK8m7I1A6qnCIE/Dsp+XyQURRpz9iELoqqI0FfpFwzH9yjuhw==,iv:AbJCNwnpNZhTOTWAZ9ODf2XDu2nRN4StLQMbITdudGw=,tag:TXI9E71QtW8FPwrbVAIM9Q==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:jnASIAYo41OZ,iv:9XSDmtqG5kLNPRvhhiJF1CXNC5NonkFtK9R8Jcv54O4=,tag:4JbnxWFAgI6Kp6lRQeTktw==,type:str]
    drop_params: ENC[AES256_GCM,data:UZSSEQ==,iv:r+71B97FqnFYAMChr7DLmrJd55V9RF5/pYplYCgizi0=,tag:vyNp7Rsk40/Ein5m6mwCng==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:onLZl7kL4Zaklc1qFZPgnylUKXYeqJRtn6y5rstrAA==,iv:adKAVK9qcM/uF8aC5PnblEfOMtnUCD18RVOmKc4PD2w=,tag:lojffI0EMuKFxLyBH89Jow==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:WJNrA3LHaRYt+LXi4orzEvVdTzlzybJ5eeu+YejJIQg8vcTGW+f6vKLy0WIUGaZesA==,iv:x8amgs6GlK77tmSJcUtjzUdSaJMbTTDHiy8CgxpJ1so=,tag:RgUTXUqc0SVoY8Cr4VyPiQ==,type:str]
    #ENC[AES256_GCM,data:gBp4B9YCsVketQXEPsy93wuJYLmXPLUBlhk=,iv:PxZ0tQa6CNwrNw5WdamP8ywUv9rMcKt1q4jpn2rEXjY=,tag:/29LfQzPezVu3q7IxVzFsA==,type:comment]
    #ENC[AES256_GCM,data:ffVGkY6q93nnIPVdrAaSns+ERx+Uv322ri6prz4EBYGYc4+xZz76ROAdifxnQr8=,iv:I7KrLLSi07n5DwTqw3w7EjijwFlFDxpnrU2gtJ8qMyI=,tag:2i9xi39MsJuqlGcG2lDrlw==,type:comment]
    #ENC[AES256_GCM,data:voxJ8Dn741Wl/QLRKwEdu6O/w6qGYU6RYNKRuvzwMd56OwINV/idwGUAa2U8stffu6mNpqU=,iv:Ln0E0ywfS5nxhx7YFFoWTrYWUGqsGJkdG9pZBfrONAo=,tag:+Zir1QriZ1veJAR1eO7j3w==,type:comment]
    #ENC[AES256_GCM,data:GyctxUWUNSgdW/DY3VozxMH+z0P4obboprs=,iv:5HaGPDjktRKlSl+LzSXi+8yEEIajzUKF7Eb4JnuYXgE=,tag:xqsKHSvgyNgr3CNBDggZRw==,type:comment]
    #ENC[AES256_GCM,data:Tawh1gu5qcqaWG1Y3gl3joYGUfmB1hWHz9TZkM24du+clFmexQGkCqjU0sHMQh0S0hjasENHoPBklAYA,iv:bzvOIgdAsC6yddf+6LiCE/5C7grIrG9BfzreZdjuowI=,tag:c000PotfqYYWZpONHqf+qw==,type:comment]
    #ENC[AES256_GCM,data:cv46m5nJXmTX+MsI9N1z3wGudBvRGwNxE0Zf8DXqSIvuYZmeCJk9cgHwcR5k7zJPTotXuxHE8WnCrWfHeTubySXU3DsY+FhlE1DvwCYUuX7Y1xMt271GUoyyU8w=,iv:tBu7wIVKO6Swa5zH3nR2oOH3tbPF6bKCNJOdvlBw0eA=,tag:KvETetZLW8f9BrDkbrMG4w==,type:comment]
    #ENC[AES256_GCM,data:owjrxo9ci6LbJUEPU3vvaZHVWJ67VqFq6AdsxlFtYeoW5AI1/KmK9LdCTx//hxWgh/EKPppTKDL79iVO7vwkgq7sVFCnq22VXRsgMA==,iv:XTqKEIVpIsZ/zwdr0ICQTPPXPvfbqjQqKr3OKoa5mf0=,tag:AP484zkeDIZNIf0Y+DtkXg==,type:comment]
    #ENC[AES256_GCM,data:o+5Ny5jukgOXe6tOrRGrRFE7Y8xzlK+UhvMKHMGyjpFWOWglSHvO0PaRnPCyHzkQgtWj670XHeuc/GtSW8O0ovyNgNYPCzzg+Fh2zOcTLfOMGA==,iv:VblLeJ/Dp/eD9m7Cdvu6PBafdtllW2+9mj7mWLgFvfQ=,tag:9ncIr0p9bCotIi5NTvxeOQ==,type:comment]
    #ENC[AES256_GCM,data:uJvyl1d0XW55VxqHHhyL+oquBVqyudiqPbToJCTyHHLC,iv:kxeo/85q8WJa8KSSp2x6KLFEYcBecYVSF85T5+K/uP4=,tag:iRz3wVVmr/5sKCAKOFmhWQ==,type:comment]
    #ENC[AES256_GCM,data:pSPAJgL359be39unaYTmDax6mv2G6j0VTFDxbG+LiqjyrHmcCAq0oR5DPTkiA2EzysprzwiSvTPjE7l59sYGrI9TOkxwEw/+njL2kU3Jtw5YkiG3s1s=,iv:QS5mIIAHhFvo9bZ0l6nJJtV7TVhE6JPmCBsIQ6k2yHo=,tag:IUPNx8qU1vqxiqeMlU8LsA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdUtWZDRHYnFHaktGTm1q
            TUNBOXlqTmk0NFFQd1crKytvaGhidXd2d3hvCnFRWnFQWEVnQVVHOUtDb2hXT3Bq
            bkYyVHJaOXRMSFYzN240VlJ1ZGtwKzAKLS0tIFhBdGFwME1Za1pVUmIxbmgxMTd1
            emI3T3k0Tm9kZnJnMzZudGxOeXU1N28KBaAgMooQbm3WX/xonIJQJTSG36BTETtB
            5UJ5Y/1a5cZQ5K4xDPSeQlM3Avple2//gNi8ZsCvAbowXFKUE65ZOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T02:24:26Z"
    mac: ENC[AES256_GCM,data:CyCrgOscLH4uitDW/nVfHvFh3WHYyJT0jjNUh5AVpC47kEkRUOdH1Ai/lDYw0tdLBUXgMty/XgaLZudw/uxiuiSE8wJKhaJXA0Z03mPp5dglML5HP5KZp/YktCz8JGuNCd4YttuQ7DYip5ysDF1gspGPChKou4/vEoN9C+SBuUs=,iv:fsdmp1xqi8PDHTQ7irpD48zEXggHGjZHDvvMA34J9ec=,tag:Pc9qTdxm/zlDvxAth5Qh0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
