apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UjXUPmAvlQ==,iv:H/QAeVfpXsqtu2CFpNJYy05o2pqc6Uvi9hhHmGipEZc=,tag:A+MSlGvJh0qbDhrOX06jZA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:NxmxWViZuw==,iv:RV5YkhaYra2jepB22bLgJ9FaiENHg+fygnxLaFYPNGk=,tag:cZKlBmcONrQ1zzRlRD5I5g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:I2IihBYK7N9UrL9zT5c4SoK40g==,iv:jDBK18g45JyiLBIeZ5DRO+vEjGVIJUINDpFFiTV2mbs=,tag:k2ioa9CMiDbZ5NeMaIbbyA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:QlcIgnGwxrunGzg7vUtsMKKZgREAeggtMDvoYxYYHI4Pg/Hhy1VXgCb0imIicrCpZ0Ow2GdH4w7DMWAyuP1oOGZbIw==,iv:J5x/1MVbDx79xxhukDTBucBdK0/vC3mTIzrJL1LeyJw=,tag:lG/g2PMlfY8rcEnImyMWkA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:j5T7af9a2V5TlXsFaej71eG6v1NLUzYL1C+q/Ab+nTgJZsKMEi3dmbQpbc7jy9ZG2JWFzZsrcpRBezU0BW1riVO5ew==,iv:vMIjZecfBlh/Pu5XjeJwnbMmTJ3HSUfCbm3mBDLciJQ=,tag:morbn8n3U08OLY/z36kLWQ==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:LGwhWj27Aw==,iv:fzOIACoHmwXaXvkrocdxaTOpooXtbVh9FxOJ96sx0y0=,tag:0r/Pn/KQmPXpCVe4D5+nNg==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:rAdjyihW3MEq,iv:SbXgqQ+cgQ2hU8yhv0/OVqVV3FlojMR0pcPuOXy5W28=,tag:CdU3uhHQzFfizUvGK13YNw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:MCxZHG+CtIwH0RkKSTpmbhGUd+1e+cWSObVb9MwJh/wnX2TtbG2xhykBRS1FPJLum5FDsaZ4SW3MZ+jGGtA5JnOOqHNqvn58eQ2Db5iy9ZUH7lJp6aj1CU4gm1Umo8EOrw/P2CrVgxbKfwjwYBd8VfkmwRrucZrQ5Md8CJmAc5DL3EaQOSNKAmZ5M5p/I6qZlv8rZDqHGA8MYmZVaGZsRkyIBaM=,iv:cuLSzuJp+G315dMPfN4pSIS1xyE5yW9axlQQBY91NlM=,tag:0l07EWsV/DN1wcNUxxq72A==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:vL57X92atAaMoYZpHijLZbsqK9uzQsL20r72WqDQ3i/+n04=,iv:B7O1fROHeQjFXWB+053QfWTJ7O41bQc3NarhtDh5lCY=,tag:ezhx+Iey53RI2d3S6aDdqQ==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:JN7oUK5De60h2aj05gevaFsjjPNCVS/AvShdJtiBDucuKdsBY/tm,iv:C6bWdx0kp5EqqBWVT7y3qHzmtWAca/hhL03/mB+RykQ=,tag:4pp6STWEb7MO15s2wTHkwg==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:HmIRMgZX3AHwmd/jl8/R1Uk=,iv:8V73p5L/gfZjre+vb6tPwFXLgqdb2Knrw5GaAVKuuog=,tag:JjPzcNTNyAWZJ7SVG4vkVg==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:48SVXcDuYgAugTujf7STJy5sgm8=,iv:E4Q4quHsaXEnO1UTeaugAcYfnkjNLrPiln8liKary2I=,tag:xBof0MeOfVLNtzfny1kdzw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jgvUdJ6FlJOA7+L/KSArewfnDWlH6gYaiqIL/CMBxnpzSf4kC35Hwg==,iv:ojq/h2wOoF41G58d8ZtjCTOfvmKQpuzzFsRPE6XHLis=,tag:/2OHgQECe4UdauF2dtsCrQ==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:Mt0UzpAVGmik,iv:tM4qTzG+cGq/l072CRVecYdrqXsVM1WpAUATo3qqoEg=,tag:un95Cab1bixjhDYr982mJg==,type:str]
    drop_params: ENC[AES256_GCM,data:G9+Ghg==,iv:+aWZU9w//wXF5f3z9CkA3V2+OJDM1kmwyK5IwnumAK8=,tag:yHxU2OxB+HBkf9iJ/IwD6g==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:3FvidYI7Yd8amBQlggAzcx1FmywuXITs4kKY1O/x7w==,iv:rDlAEO3+Is+d2qITfVE+9PHQIenpYlhwnI48/mKBzqs=,tag:MJDlR9mHUiGjOgqehNtB6A==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:BhHZOb1/DN7g9kZi8RNpE0zQJg8TnR5wnitEgkx8hSco/vs8RErKOdzLdb1ep0yq+w==,iv:LEBN3+VIyaCDzdT6zSbSXkia5NiBD/tt+xmjLZdXkbs=,tag:mtQ51hO3NOYkczYKrntfxQ==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:QbVumV9ec8Aozz4cifkO3gVhahtk0q/Rr89p15bUAZdJeqQev7WGROdKQhfeVK8m5ToQ5SvdRHfcDDrG7HcTtg==,iv:iorHLIONc5vgviSuDvBHTHJUzEjmVjcNTfkkmyl4n4c=,tag:Y5FeT2aeuQhuqhfE3GkfXg==,type:str]
    #ENC[AES256_GCM,data:Wv5QblTWa3Sb0VY6aWMzAT9A4JdmMVadgKs=,iv:8eJHfRWf3cpwgThRJGwY9rkRNL30W3GIlHrGvcxEp3c=,tag:Q8AuNELCsRv2Q8t+3Eyz4g==,type:comment]
    #ENC[AES256_GCM,data:3f8CQtDkU2FTOCfnihgHm9VLNUxSSqoZ6FOZgT10kXUvjs7jHVqMfnRVtujHEeE=,iv:/9PTp5Nsl56Lewtc/ld+M84qGI8WY2inSERTV1DqKPI=,tag:IiTNZ4Hwniyz0enetZIleA==,type:comment]
    #ENC[AES256_GCM,data:lwnSz2Drx3VW9H4UZ1lwH4s0tazD1jT6NCUugTTVMg2T+ygfwYkymk7KIZiEy2omUw+KMJY=,iv:99AfPhSONTqhbMgiAYEZEQ45VYQl5vy4+QSryfXrOIM=,tag:50z6ot91RQK7L/QnrhTpmg==,type:comment]
    #ENC[AES256_GCM,data:5iIHhzJiZu8caqcjPNRlkhIu/QwDre4TgZw=,iv:r+zauWqemFAWOkI52SDxBLs1uIbdu4vLBTMHd9+QynQ=,tag:+cTAu4dhIN8aGmCrhiLmAQ==,type:comment]
    #ENC[AES256_GCM,data:jfEirjXackdg9IDP23qFCwT9dRMW9nT6LEYgbfXlOCeaSsPm8uZbsKnIOYRfs9wGl49RkA11UzDrUeh3,iv:Z2OtyY5LSoMfBRcQ6/AgcuCzyrFyhwC6VL8TwMokrs0=,tag:HKwEeEu0i0dAieKAgtOZDw==,type:comment]
    #ENC[AES256_GCM,data:dTcdeX85+8PPhdkjMH3ho+mtaeLbGx9bDwifSTdIbx5hBL4DmwpoXGKhQipo54rir1aOKmpiFzBp9Jq4GfwjrEjVeXApHC8eczBjvWEJDgxwkARBw5KmEjsguYM=,iv:GCbTQY8oW55TfiJw1p8Di+I0wgWLsmvW243Gmje8src=,tag:7DSL0/Pkh1bMHGiklE/MVw==,type:comment]
    #ENC[AES256_GCM,data:esrrRp5FWIxBXEhnIWynJZaRDsxuE8zP1vmWbdXB/LYUPkr0YPRjCTmkXYiveSSBZUZsAnwkDfHQVJdejBQGofFCmVfHeewtr4PDkA==,iv:RB6xWV57+oMiVZKHH10GBSqYDLel+OBgMl6DLLfGIsw=,tag:Qo0Rla67anJIaI5LiQR0kg==,type:comment]
    #ENC[AES256_GCM,data:rgrZ2OF+pw2E3mPocip+kSaAtBItmUC35DxV6vxQPfugFtJdMcrsUd1pJKNlthINLltUUaCti6TVhh6gJHDytnSZ90pQulwHeq3PHXf2ve17eg==,iv:+47Ig6s+rNpbhQRPMH8nCBcaucFBAHSDzI9eU6fxVV4=,tag:TD4dwX0T69Q3VsSLK6ReDQ==,type:comment]
    #ENC[AES256_GCM,data:vNoTcgOKPyKFaGIDpyWLufZUvtk9MXUb0qKCxPNFdMZD,iv:Tty43o0yJ5tcsdHe+XzAuPDcIhj1Vi7APEgyFDRQdXU=,tag:mjRDVSxWTIoBMD28f1/yJA==,type:comment]
    #ENC[AES256_GCM,data:OUguAHbwY2I8vLPyxCgF9yTmU4O2txrCgGnvqBM6Q2hXvHcLcCygVZniXYgBj9/jiTlOI4yPGeQZjrN3eMYKZjp0qLJwOHBPGkUZZq/NTQPK7TEE3dY=,iv:EV5e7yqus44mKStwqj6bZ3tGZGQ1n9Emx2MatAVZoeo=,tag:UcdVmd6YrfItvcpomwoO5Q==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWEdjdFdzUzAvNnI3YlUw
            SDgzZHpjZ2Z2VTJZcGhqMm5UM1NqNmdxKzNrCk1oSFRvY1B4SXdVNnE5T0RKRWFS
            M0hjN3N3Wm5Yd1R2U0FBUzh6emtIbGMKLS0tIEkyaGVQbkNZNmlubE41VldsMlgz
            UlVIbFA2WmtNYzBJSkhXWGoxWTRwS3MK8XwbwHGVYMYIWKcws65F8yWVB7kGCvCV
            zHzDO2BgsjBLONuGehvARYbBtNzsDq0ZnEOC9SLaK/U6VUEFF6YkcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T06:05:54Z"
    mac: ENC[AES256_GCM,data:adw3jWFF9jtjr+QNEwmseI3qXTbd9qZoibdfGFavJ91pU9+4jtXzdhpGQKGyvTvju3/4vMnwe2NMRPogA4PQ4FY2ObAofnn+oyuy1zUGNWRTFkOHtJKPu3yNOVKT4vefOqTEzUJPjvYKDeI6YDh/BjROpK3S5ZYtkHFrgdJsERk=,iv:I9ifQAIeLbdQw/4o+MYSxDj13YdpTx4YPzeIAPOba+0=,tag:Jp5v5JzF3jPUIEypt1F5tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
