---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./plex/ks.yaml
  - ./outline/ks.yaml
  - ./bazarr/ks.yaml
    #- ./calibre/ks.yaml
  - ./ersatztv/ks.yaml
  - ./imaginary/ks.yaml
    #- ./invidious/ks.yaml
  - ./jellyfin/ks.yaml
  - ./mediarequests/ks.yaml
  - ./metube/ks.yaml
  - ./nzbget/ks.yaml
  - ./nzbhydra2/ks.yaml
    #- ./plexmetamanager/ks.yaml
  - ./radarr/ks.yaml
    #- ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
    #- ./subgen/ks.yaml
  - ./tautulli/ks.yaml
  - ./transmission/ks.yaml
    #- ./komga/ks.yaml
  - ./fmd2/ks.yaml
