---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./openldap/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./vaultwarden-ldap/ks.yaml
    #- ./uptimekuma/ks.yaml
  - ./smokeping/ks.yaml
  - ./changedetection/ks.yaml
  - ./librespeed/ks.yaml
  - ./guacamole/ks.yaml
  - ./pgadmin/ks.yaml
  - ./phpmyadmin/ks.yaml
  - ./podinfo/ks.yaml
  - ./echo-server/ks.yaml
  - ./brother-ql-web/ks.yaml
  - ./it-tools/ks.yaml
  #- ./k8sgpt/ks.yaml
