---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia-shadow
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authelia-shadow.local`)
      kind: Rule
      services:
        - name: authelia-shadow
          port: 80
      middlewares:
        - name: middlewares-secure-headers-shadow
          namespace: default
  tls: {}