---
apiVersion: v1
kind: Service
metadata:
  name: authelia-shadow
  namespace: default
  labels:
    app.kubernetes.io/instance: authelia-shadow
    app.kubernetes.io/name: authelia-shadow
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 9959
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: authelia-shadow
    app.kubernetes.io/name: authelia