# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: subgen
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:W2vb0wGbq7luagnqX3gVSLNgnFY=,iv:Fhp8CbDuB4idblnp/uFjgWYI43u10Bx2n6GVdTNYDP4=,tag:Kye7Mt+iTGsQZswkmHfVXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMjBmSFg3dWpicFh4c0xK
            dGRoY1hBc0VGdUVrb3dhek9uWW1zK0ZnVkNVCnBra2VYbkxWMWZ4a2dQMXdtU3c4
            Q0NEY3F4c2d3VDFjaGNFWkJMUVB0K2sKLS0tIDBCSkhSYWQ1KzJFZTNRNnJVdzN1
            WGdTYVVBa0NudGVYZmZ4ME83ekRHWXMKwpWpnime98rbfpaNNjTi2hyeyLweyPqC
            27cn/KVKVEbj//NnwBcPqMHL9cBaBR2Jl/HwIsABZPwtXW5xo6HeCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T14:15:07Z"
    mac: ENC[AES256_GCM,data:Wext67QuuFnWpl8L/X7q1SXO5FHpTC2zuV03F4EriMKx/D6aPaEKHZzcH0WaTZeIXGUeBKcqCVwTfyYgF55eIuSILRMlDwI4w6S8M7MCSgPdGoTL8tP2QwaD1n+aDEcXVDiUc5RdEWA3UQ91hFu6eqtIBl9XrjQF4Z+gE/+MvPI=,iv:4lfGF4sQzi4E0iOXX1poetV2SVMjZbjAN3+v7HLeOwc=,tag:LOCtxP0xDhRtjG8wwlfpGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
