---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml

  ## My Charts
  - angelnu.yaml
  - authelia-charts.yaml
  - backube.yaml
  - bitnami-charts.yaml
  - cloudnative-pg-charts.yaml
  - mariadb-operator-charts.yaml
  - csi-driver-nfs-charts.yaml
  - descheduler-charts.yaml
  - ealenn-charts.yaml
  - external-dns.yaml
  - fission-charts.yaml
  - go-skynet-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - influxdata-charts.yaml
  - intel.yaml
  - jetstack-charts.yaml
  - k8sgpt-charts.yaml
  - kubereboot.yaml
  - kyverno-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minio-charts.yaml
  - nextcloud-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - nginx.yaml
  - nicholaswilde-charts.yaml
  - node-feature-discovery-charts.yaml
  - nvidia.yaml
  - piraeus.yaml
  - podinfo-charts.yaml
  - skater-charts.yaml
  - spotahome-redis-operator-charts.yaml
  - timescale-charts.yaml
  - traefik-charts.yaml
  - vmware-tanzu-charts.yaml
