apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-rotation
resources:
  - namespace.yaml
  - rbac.yaml
  - configmaps.yaml
  - cronjob.yaml
images:
  - name: siderolabs/talosctl
    newTag: v1.10.5