apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:Psy/AoFx0qE+8qvBdXJQitvCVgTnJPcs7a+pit3Q3OkB20XNAL+NB9mBuPV+T8udBm2dd7thq08+kCGCmCvCh8LiACHoR/1su/Ih2CpiFl0MrwP5e7i8A5FLhA1jsOBRiQHLkzRz+T25c8hGoOmfrICeLfrOpBZxR3hrOlIH+KInD36vDUAm9UtbynP5mM54HYMGhcZbINIhrBzaVz9f5WJMujpZzldrqlclQjGCtLA7vj9KwFDvdIxwfWEbo7AjnHz8Rf97qh5fl7PfQkLPFMDpmPaptbmJoHJho8a3mX5wFGAYYcjT/gjy2lfH2IYefx8SLt9QvmyvvOZnjj+0vdvfKTwdgtJI2wBKvphPm1UjI/kxvMpIZbKgBO849Ob35t0CbniwhKj4So9/VulcjGTOt1oG05I+tiS4WFoZ56cBhTK+yCaTRTk/4I5Xap9Qv5Pp5mx5G97AmbVrGaZvGUazQcb2aGQ0fyEqnyyAxK8dmQKtz9fij5BbsLEjaFTMLADJNB40qcfJ5f3yPWRkDQra5KfCx+jwuIOv07S9LY43C+ENFdsN8hu9YYAZCVTJhDbosT/iShx7svnesGQvjgLkfBCF4sGPRkLXR8vAQhQ9kmlp9vGCiF85x+wmI9i6dv6JWJLxib7yU9QX+5n5YFUl4ToITNYmrbkXFCJLDPvZWBOZ1qaI7iAeFghLnkOtBxzjhMgTlSVx0WS0HqUqeEtJMYOaHn72Z2vnjgrxQYrQ0UJfgC+t6Qo/GMBITkGbKOC+8/6W/m53UfK2u7Kt6RKDdixOsjeXThNHY41HyPDVL6TPc/lEnbjgeRmlkzxLHcvGUFk/3w2EWgjINHnNsbnp+RigXSxvczK9E0eSH1vPgRHem8wRUt4we1vV3IJcFKsKVwXk+O8OCJebWzUQfJPO0eKjUJM4bCjD8IqE5gjj380Ncmo9a9gCQJJ0+FNlFzfDg56CMlim72oWp1gMWg98ITw7gYbXrV40fI6U5fvmgoaVCIWiWkpZBWZnGLJoyTNF93hpWMId4KJNoaC0ErV86/xk5mx09JSKRGN1Ag==,iv:vJRljXRGviAdw0hpncYbVXpQbM2FGbgOkluFWMiWsn8=,tag:hKm3W0ZckGmuOMtpwcgEiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY25IN2JROVdNUkYwT3VB
            WHVVWElYdUVkUllCMG83bHNDdGJVOGNvTFRrCkFqMUJnWTE4SXJIbzBPRkpyTHNE
            RGplU1liQmU1KzlHVW41VmhHSkNRWU0KLS0tIDloc0NoRVJaZmV3UzVRb3Yyd0E3
            d2pkTC9HUUd5a3diK3A3aDhWb3FKc00K9AuNQkcwEtRAgwlwUFnUt4AEcjuC/JZ0
            GskfMVaR1UWIdZVu1lUM8HxM9Mlp/C1Gb/vJZDrRMjzn8jkCi/HblA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:34:11Z"
    mac: ENC[AES256_GCM,data:8fvmaJIpMKOHALxcaM5zBumgewAK3fpz4HA20a+RUAVYTwzK04arw6huPGLgUPeSYhvOEDnlYO8L70m/Hww7neE8tbT7LkGctqM9YMd4tFSI3lD3LSNuXHnQtIFs5pN+WYkpJiNGyUGIa5Q6AENZgkEU8e5grGd+HdHVcq4A9N0=,iv:yw0RXLE63lnPao72hgj7ePGiNRTe0SsFtK6D5MbYjs8=,tag:+atdTfPs72hOadW6bNySIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
