apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:0DMUA6U1sJ8EeRCEVydM5ZVFwYzQ/KCTzg1qyvd8n83g/BuxqWf4FEw08TAuzrRWlfWmY7TJz3CdZHCrsHg0LRG1l6/UA02NnDx5I1cOEZNeUJ4A6jL5qQHfEzjv768w4vb5fPclpR7FPyoIeJKV5LvQp40ANG/HgOSDlSuJSg0KZGkFLNf/HarZdTjusuI0gE3saD0KhEM0kxYDKcYxnQkr4mJczHrEb8t+GjtpKapp9uKB9vH+u9k6IlU/dMQBpraJqxG7T/a5EADUSZr4G5VWWAkesM02qFGWolMgv7PYmx3KdyDLRj1apxlJmaUCnD+ny6oyrtaNDcTlKmdxZY//qibp110/WVXFhDyBn8spyxkmGr+beYZSdSoIK8uw12Mkgvd2yh0hI8jj9TQUoeEDh9TL5FRgVJILz2iYlEFC6FvW3a6qQyz34mHVfTcRzrTAl4j1RC3E3JUmHKXR0rZ0OWBCH0002pRvfSRe7ISo6oSUoZiS3i/0VMZZARN/3IAmbSGQpQiQUqYq/h62DMgrZEXSV5YG1fZjiSzOuSAprujIM6ha+0Yulu8yKsbS43MrNvCuSJ+0LpGxN4QYcESg4vNBmHQyMj9YwQcwqGH/N/yPh/YReCFqD1HztE/kr7XsxDVE1yT5gsFW7e0sak1ORWveZYOYnMfcMkDcAcs2sxjQXNzbCgUppmyAxc8AyANiWkvw6xY61djw/rD9esdFiHB3DOkgznkS1IKNCFwGcim+XmkOdQBsOA7aBFlRnNrnQHWDULk2CRRmyi3S9V7LCOpGY59ui2B2MnuZxRJfOthdqOKv9Mtr0+kz0J6XJPCPXPcxnOOXXgl3941L3Mx2U5uuDp470c/fE/3iZHKyIi0MDea6r+H6pP+mbPHhjCpWX+MeMXBMILNSO08J5v5KzG+At1zSvXmduTpAK78+f+PztikJbVVInagt476V9myGm6Ngfb+2GPxGdDxrSPMNJjMW8D3V0j6f5tEDOxK8jVlh+rClTyEbxZf7,iv:5rujNkWWRozEkoanC+IO8UoGyoxpOmP0DJH3sKaoAwk=,tag:NeED4EKEAJI/PE8Vr8BqfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZHgyalBpdEh4LzBSTjla
            QTN2UVBybmdBV2x4MGp1Y1k0QzZmUUo4cjJvCitFY0xPRkk0cjlqeTRIYjhuSHFU
            SVkzbkU0VXRScXNDY3VPRkdCaVljdzQKLS0tIDcvbUZUb1dvTXNXNlpnTGZPVkpW
            SVBEanNXNks4Rm16YmlWWmJ5ejgrdnMKz7tKm1M5DF8RiPgyKBuRS8aHGti6T/4O
            hDcw6GgO2BT426W6wIr8qYfMnuTNoWGhKXV3G4d1TcpmDKau+iJr/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T16:23:29Z"
    mac: ENC[AES256_GCM,data:SzLOjsPjGlc+LLPswk5jlCqTy32n+DUHPvekyc+ZPZeO29Rhi3UBPyDyYIE2lOe89TSGwxFyxiagPEc/bWsezghMrN67hrnFKUGLARLsa5+PlS8RPDjI1FkLmqEuXZ4eoKbkLVXRRbTRPhJ3vYb+e2lp9KAc4UpUNPRJT5WkQzo=,iv:NtxXZKpttGk+DBZTq+IEx1cvI8IAUIHKoBW0VSteXeQ=,tag:XsiBkjIGPZBtpxF6AVifxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
