apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:2uDRnEF8Dg1bGz1yqlzJDoDj3OugrT8V6kuKttJSeNSd/CUkvr8Fz0NlQ9C3PXLuDv+alGgYzDLIHmRh8U2RNyx8A9ZrwDFJizgQQeQA4cY6PvLZlWP4mQ6lhLJfAddn3vd9afYOA7eOz4vvYTwuLqndLXvAgk1ItBYm1NlS/mHQq+8Vy2F/0cloGAubPwoibpCe5BMKM6SkrjCa9bITCIYRo1AzNigF5tb2l+1RGJsA/rN09a0bM2s8OeQznx0TUsEyRQfyjRiF7Giy2G57j9JWWvGcZ9lUcuvN1/7t7jBGSHpPCmqXEIVJI1G3oY4Kwkbd7MW2uUmoJJlhXcdV/6kWJXVMdybfI8NqexM5APfpIe1kyit9TB87xyeDQO66N/yoW/iwidoSafHhcGN5ktBWQx1+CHy8I6TWjJ1+MS1WHruntwuIAJRsVNUon1bi2j0WE9vVqmsEOmq/aGoPMs+eC7YgLHSu/Zq2xQ2ssbd7t9EtQmdtRHIwDIzEQ5UtisI/2OCD4BVylIbplF5Y0CYGMZHO99RNR28eYluT7avEJNTlQYatW+DIbSszuZ1s8axNoXZw3jj0UgMITxaE8srcxkagorCUkxzGMDYNA5RoZbvoToXBxTV1O8duYzIHwsOYXulGUCFhv8nRJZW2y8WZx8KzQh2g4K7rsDZZOjFfxseBu2+YtAUaL5VgHr4cm2yY04MR8amNMp9pfsOpewqeUfjyNhf+TKyY+2BwfsAW8693uiw2SQGVYfUO7Fgzvx6UjyeKmSOJ2Yz8oNckhQCAoZ1aXbnj2Xa2cGBy1c18b5bO0Gc/5NvwxdeFhvelXo0uo3XjQB2WlzQ+Tq32gtaGLmQax5jbAdO+Jq2bWYiuSXStZymcqzH52i0a31C8gef61XlVpj9+fLcQ2L7554T3TmdRVcJA35ANiQA/mok7E54WrtzcXx2gtl8vuzB7,iv:xpUOlw5GqeSZNl1RbT0gp9lpnyTUT2OHPvgjwOYLTVQ=,tag:UknmjqmGYNTy13Uc7j19Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUjh6OUozS0lyOFhCOTNQ
            ZkJxejBiU1RKK0dRSGN0R1kyRnZoZkR6VDFZCisyaDFuMVFMNm5nY3N5Sk5LZG1x
            UEJld0tJbVRMMXBLRi9vNEVIWXlQWG8KLS0tIFRrTzZScVg2cm9TWjQyODllM2Ev
            aTIwb1VrTXhxVGI4UFpaN25lMVB3Y0UKaJBCJ/Ybc6vkpGKhYgu1eW6fOprQch/G
            7AGD6+PRXHnx6NLAmKRdnge3LuOrqcm/t902N7QH/5MJqmeMe/0CrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:20:21Z"
    mac: ENC[AES256_GCM,data:hlEjW119SjB+bSi991+3pnYINiHa0x2X1YrmMYyBLQPvQW8nPOPf1TU4wReoA7mpQKFTxCX5ZxMehmm7Q6SAXUoc9ab1AfWV1FQP1K+mUQkEfytv2HWI/h8u4R4h3b3Id79TGldOXJugY7vG6YYo3hRLFChPLekUhIw0Jwo5mAg=,iv:KymW6vX9/V35nWPgyY748pX5sUZvPv+sLCsdcDuD3O8=,tag:LA7UbiZXsNn+/8lK+pngCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
