apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:SXereHQ5H3ZM20LI+30jtTVo+8X6eiedODLObFr7hkwepF3kOWmsBr1yOgY69VLVfF5fZXaydWEQHgf+P4JVlNqa42eAzrvZ+Ynrf8DOn1Ga9eGo6xlVn2ANSN9ybamjTn7kkJYpwwNnhTeqRcHlf/EZEkLpWtyhYbXTHWbpoyZGtIVXnM0SlyvsUvAyCXcL95b9JEeKnEgZfl8/D39ILvv9DP2vdwytGBPLiZM5YZ2dxKJZk+IMGFBWVvtanj20Dot5icJMhspBu0NC+wwNy4u3YF8DTo6KUzoaYojsTh+1Qd3nsuh+aOg2T+UuGWElmqHv+T0x1T1Ie99qe2PCnI3nyHBYCUEdX2DShyW59zp7I3S7+7YLOwEGffq0YFbckaa0ahQgyTl5+sjGcXE5itKx1dGKrsNriCdxWIGH0dyLSdU+xp5EDumsLLWE0ikOrHxFv6hulEFCjtUMHKzZUg4qz0N+L3S9hI8yOgW/RL1NgsWGSiKzBczVYFLmu0ipad02J9uyGG+ZuP3eD3OTG6K7xokwAf9O7A9eJz4VhCVrUedUey/LouK6FPJOxoyygwyntvHYY0jnvFGktthIOmBOuazBVf50vrB/VlT+/CiXv2v2wQUBrnbj/9FzultFwzpL3++jv9Yt+iV5Bl9rCP8fyGni2+RR24bl277s+Z97VjYO+Of85qtejJzfOtoJRMLDjdg1LeIH8jkF28CgfLkkdYGNh5lp/qXaSatC9+yqaxpGFeNZOxd6yzFI/R9cm5A6wQh5wDPui6jnOAGAybM3/Gb0mfJc9YW6z4AJmbOCm9X6Oacr0azDaGUzadQot4h5Au2kNUK8RdP+wBCjCAPZ9Vzyw8lTH+Yw/C8fIIyOLimwC4TvAOMTWOtMxutmsiPNRdE120EH635fNBsJ/x3eJzxGIC3c4vpWGmw/wQkGxwf+W0/ZkFL/ZmpdKOo=,iv:gPNmkLLYPZjizmnUk0vtmfyRCaCnnBRSOefHKlp5iTI=,tag:WbFh5GgmNq3tcK6nrrK6CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cUpKdGl6K2tWR3NGRkxV
            NzhpcVVMdE1VZitEMUM4MWE4NnpwZUhCVW1zCnZFdzlmenNha0tuZXRoUEFPTU1n
            SmU5ZTRSR2tBNmZoN3pwVGJLUlAxdXMKLS0tIGlUcXNKcEpISlg3OWNUNnA3STEv
            alhteUFzdXU4WWZjbzlERDBQUTNFOUUK/fEXdF4JWNz1aupG1ndp5TW9/I/vgazs
            vD7wGLmxlsRFK80EDhY1VGqiHGr6lcd8+5XFTYgbRIX4sD8aTHr6cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:50:57Z"
    mac: ENC[AES256_GCM,data:f7nJ/kxH4LKuuQPM4ogHbnEXA77IfLlNl/viSzJUM9o4FrUIOjY2o3YUuCVpkzeelKGVXfD1uoadj7L69/ajWkl+U+ofWMWuRwpQRH92duQCR5ATAleygOZOp3EUMpZ5kGyg5NQJ75eO2E1POOCqu86KjphsNNxRqVm+Z5+gU9A=,iv:py94Sy0J1AqQty4vEIfW6x23y6otmgjfimLl6XnwI+8=,tag:sWCXXmRfKFyoKV9GAwk1Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
