apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:AkRA2/iebI66yF0aZkIqomlP9aspsngommNp9WXZzZ6IW31ll62ku7/d/d3lOLLWQKDBEuk/OpnYxwOHKt5KvPbci4AQ008zHZcbMgIf1B4VILyKi479D8rH/aK5XhDiCMPCeb3Ain9fv/B0WFN+YE79N+HEIHrqNSwb1MLtHPfKo2V+ifogTR2PbpW+xmh90Hcu1fsjsIlsVAsYQS7vIZ9vkyf/R/78pfpSf53RxR5owDaLtSzDLI/8jdZSdroOsqPGac7/OoAA2A2JeEQxm/ToTW8ayYYgS3yNMk90zy3PBOf0H6nDq1UJggf7O87L//pT1PeVpqkMeWqCPVVY2cwcAWQNH/Ea23EeyLaUwS79VFYf6XDZOwDCfU8+gzv8ziMtFCH5wOC5JBPJHt3y7v9m6Qn64uD1XuXxramDQYm6oBp+K+Mdi3ojdJtPGTy6f47M6gmWOaF3JKDBsV/xO848zQbJUH4enTx/yVHMUr/a2zmKj8h19Xi85uD6dq/4thD1HmgZjIm3n/4GlRXrH7t/SuByu/hLNzVBrIiRyc2302gd8WShFC/942Hx7jnp/VxQzgpCTwxfwMPur+ccaGLA5aT04h2akZdZ9Scm9NSftNnaraAqFURTMMi4uzzHV0f+SYuFLMw9SYQvCjChiQ7gWe0IV9yCKf9/HpHn2Be9x3d550yaHLyUAK1aIVR4EbjL/LcVCH48GO3lb+8yHxSflO8oiODZ5wNVgywSayS/mHnmRVxAsvUOuqm6JxQURW9jaBkzlQPzadlBLKcJr/9+iVmzWOpzeRu4kzDOZWoeRCrf2NSBMoVoTldiabHvNRuk05iyBR7cQ+ODvSI/eS/zdsMWb81mWviFJRcoY1kMlofHMXTSG7OKNODzkA366QtU5Nrof2tl4HARBlIGzw746Yk4xW5zI7K6t0HsyrqH71dTv19k+bLp9i/2CL8hg9iYXgHb5nxYsUyrbVcl2sWBc5UOIlwfSaHetAfKzgbv9kj6Z7dzX9K5PH6XF+4WLFTXFdB4sRaFVJSPq2iD4gGHOnMS6oMJjIEEsLidjYkDVDu75u5NOiHJcQ==,iv:nHv8kUKAEapfQ1vtHBihEEJ2hXYdgQhMhy6ssvTuxf4=,tag:YTY8U0jhuk7THG967ffgzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YTcvRHFSb0lZcVJwazhR
            MDNXY3JuQnV1YmdoNEU2c2VEVGFFdHBONnlBCjBjTEppZWNUZUZwVGRqTFc3anZW
            Mll3NUloaG9ma3ZESnE4bEszVFc5a00KLS0tIFREUUVnY1hoY3BWWkNwa1RnRnB2
            MW8vMFZSeHdjYkppS1JYL2tnQ1hSemcKxoejoDLienPcgOTcC6CqJ4ae1+q2FetV
            5fipMmoYC0dX/OQYXYx4cXxG5r/qbcwaiKR+ow9pqXJGCjP7H+MrtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T16:30:29Z"
    mac: ENC[AES256_GCM,data:aNEhX5boBI8V5yzZTx1XbLv6o9SbsALENu8KUWuzwi3/UDlaasO/m2OKuGaxiqP0KSYZpRxOaEK2vEAvoIii1kp1MIoTXDD/eJa9gpa8mjwVcI4DNQgKkWxhnWednzOlv0dfLHpQ7nd4udZ5h03nj7387l8dZJtWDvETGDHFSTw=,iv:HzzaWs3Z/B5vlWWuII9I+qYmAlpnobSAEGKCQ5LlZdI=,tag:dcxNlykNJ8OfeDBKGsKJFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
