apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:CusfegtK2Tn+bsJ8kznW2G1dm2HjC657hK163mfPbBL42dE2a3wnEV1N7rF/qvx1l21QTjr9p7+RkW1zaa5TufdMBBt2MrusYVISK/4b6vMjPWaY6rrbGVDjZwWS6V2F+GpaWHxwD536evVIklpJkHp5+N8tDe0sfqc3uLkCZuHIKFWZEdqc7+bsfeeyJel9r0clAD1aP5CqwMjdzEHujtJfewYJ5QiF+rEgBv7uBJ6BSsoj9SRseBQ+2U66ueE9WWQ1s1eINaY1g6klHwhGGy5q1c2FNGhJFT8WrUkPHgu2ubDEZ35ptsxcxfikIVFwV3A/9P7PFLQxfhT1LzvEU9C13NhQ+4isCNrf3OnGSORlFGmxM+yizsAYS3bLMi39P0hSj9coNBuq+5ygOogRK0vFOHlQU4zXQGM+tuKmGKysEduWXSCszZbnexkP7mqn4HTn6jaPgpbjuQXm/5nPPDzPRGNoBY6pnRa5DMcc4c3MPmnUirNKHNqN7mZCqIQCRl9f/3IzraAAKFlLATe0j5FDK/uaoE+PokjZvcFibDj+LSCuxEvI4XqyEOzSBx6zwlF98+60GColAYABGcnbPNcWzxhRGJdT6Gt8V9S81C6RIABF8KAiAnXsIbHoaKne0cPsiTtGKheurPKUt+vzGBO2fGCBMkhdZaKO1tDBeJFly45TC2NQJ0lm2Xrn2Osml46tbvX/V8gww+aY8Q7CMfRN96ad53r+aU5q9nCJPQbxv8P6igIhvCQ4YCRfjeSTY8fdgJC6jI1dAwVAUyqwvhYJzMwT7wfhzFoW/0nKphC0l5PgBDUPZ6DFdRTQfHrAVHPmE75qxTA8kv70K2hEgB8BM5fmSwpCYnnHieJN+gcVRsdICBw33MPBcJ3sX2bT/F3mc/0PYQoRkiiq69wI2kooaYhFilt43K/J61IHZN5MTpK2biYqR35SI7+nWE67d9IQq2c5QL0P0G2a0xqamku0RSs4WX8bCMvMzSsGNZ1gvG+ESD5qmgpRcmq+sb4mrbgkqUKN9ToHiYAa/0dzCtbiao2iTOHtuOhwBwWiBR7mHUNdnOWovhg4jTrgal/2lAncyTc0gjdMTjm5+uQVA+lu2jWvWmUoHv8atWe2K+9OpTKh8rkS2tAEev8W/W1bdxJWWC0jpKB3ZGgISHDyUYFytUCI/jBPz1I6,iv:S/UmE0lhqvNRV2PUTrDzEdigM8g+cV/q74ZbdspG2xo=,tag:l/EkfiW85H6pSKNon/dUYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU0Y4bXNvZ0xhNy9JYzFt
            Tm5PR1lCbVJXUkNqVDdteVFqMHJTWGhoVmhvCitBczlWUTdrYWR4M3NuR2REbkRM
            RW0xc3FQS1Z6T3M1T3hFMlh3VGdXRjgKLS0tIDcwNFM1N09BbTBsWkNPeHQrS0Q0
            a2doZVJQekRlakRoUGQvMU5BRzlWTVUKO8P4rBhbQNYn4cNaLgOrjBnmIiG2zP0K
            3ON2a1kMTnclyDrpamvfTLz7GChlMbwK+dBYlV8xvSwNxmISiJ8hUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T01:10:31Z"
    mac: ENC[AES256_GCM,data:2oIYwCwngMULMhrrdl2z4A/UZY3RKF5Oi2OH1BBxnB//pjsK4Yw2qMHrKhZmAAPccAiGwnFoloydpAUAdAtPo6a4fnXCrzxT1z6Em4r4SEYq+5u6oqjIxacHEOyhJtbeqtDhAROSWdP0fYQ4dwIZgankqqlQaR8S/twqZKKMgZY=,iv:nVbeKRlIyJqj3baGm7V+W4aORsFxeczeXhGYC+BFlIw=,tag:Jn80CU4pT0n329ToNuuRWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
