apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:sMEl4Eninnf5/LwVfubVumqVoQaYrE7diq0Avkt2iu5R6ymdm7al+m9QxSkfTYI7N7mlM2+GmBpuXvDaHTErU+8727oDAeOhQTCiLxtJNzE819AHgZvRmriGxivZ0BoJALcRiP0xpj0mHNvfq8as9tvEB5lOIBA04SrPtms7w1T0TQNhQDB0ZxuDVEOkW2ULg+53qG6uRkBzHaQVI/yoXgodWvJ52hXYe6UOO7Ok6HtltcI9nJm8P+qX0SdSoePhISD273uHmDe8q1VHy3kg0wyhIs+vxmQO3KB5NpsY6NbVbOSxJRX1lTpwSeXVBgMmXQQqIRaQCW53X2+okPwj9OF7WEw+dwH/uY2Fy8npiSIVXrCdkk5dCxQcvwmkYY0vteR0c9v3F5Rd4akrLE76p67ObnkwExqL8u7AIc0GK52O77EBYCpYxw6eUJD14ksKyC89ibqYrSuGHOpEHSI9UWP3qzwlHXOokFmHGPK57FQb5dNQj3c8kSdX/5NHYRULLLqGIvInckNpJvpwpyvXWV/1RE8CoyH6glpjew/v3bgmMANm8dIlsX+xcJg3a+PlqIcpVQjfOvOC3qkVnuq/rN8Wdu+XVjDLu35BtuOp200+63rGGGjb7BGykezPOJzZhqoS2wjX6egEf7pcgSRdkcil3fpgzQe1c8oQ1VgA+KB/GPTdiXTwVobC4zBJR/OtD0CSarlo0QLsLsuu0S0YjmsRqerrhb3+3akxKSUEUiwiYxUmu/z5IeRX29mBkkwesjSS5xu4BhrbDbqCsL8abASQAAtx7YHpSs2s5RedVs20AdnQDl3QWWQR0RmUmxLd655fJJkfildkR7SS6xfOJ0mMqWc+i9gVFa+9tY/E4bsXdeuf0y4Ug9pdngCkO00UKzEGNj+FTVeqLbJyXOPPhhk/B/UvUzF1kIHuajG3Lr0Lex4dcxoRhMT66M3+/RuBgB1Pf4HRcISz7yACuXhEt/XQ1UTScdDnNTa8n/98zRhW/Z3JgtdCzD8WoIt+6dOTKqI/h9rbp4iPdVH7e4LhEfDumaA=,iv:KmtO/GueotGJcRmB66ta7GaJwUpJ9V4/BCVg9wMyppc=,tag:PN7pik+H9EUYC/3gOoKv+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM25BWk9UMFU4ZXgvVWZS
            VWZDS3FsLzIrSWlSeFo2YVAwNWpCZllhWmdrCkNUWUpRN1ltY0hMMWVzSTUySXJp
            V29RZnoyd1hlbHJqWklGYUtaS2FIRG8KLS0tIDBRY0lmRXMrRGZLSExxNkY3MCtn
            TTJVQVJ1SkhnS0NlcUIvUEEzOENoRU0KOfXN0Csnf9IRvYVglQ/dAfVYlcs9jtGU
            eMp8E0f4Ab6pb6aC/Ouv4LQIgd4HNg9rF8ZdJsVcykImag/0x8esGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T16:46:24Z"
    mac: ENC[AES256_GCM,data:KZf9L0NwIqkfpWDSPrCQavxLiy/hqBlZylmnuWai9lPyDBqPI/5bs7MoOi5DMGUQwjlc/ZDtvcwXYtmGGKd8dY68MmS6MmHSYG0n4musRaOPnWSJSMHg32YMpCdk6xKXTGZWj7PHraGlBbH1mIL03pommSKPyjbJoS/GjI6c8YQ=,iv:x8mvDqM9cuyvpbfX+dolxCr804pHiAypgNjqNC/+eIk=,tag:mqqu23IyG16fvmEA+b2yFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
