---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
patches:
  - path: ./patches/geoip.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: vector-aggregator
configMapGenerator:
  - name: vector-aggregator-configmap
    files:
      - vector.yaml=./config/vector.yaml
generatorOptions:
  disableNameSuffixHash: true
