apiVersion: v1
kind: Secret
metadata:
    name: k8sgpt
stringData:
    litellm-api-key: ENC[AES256_GCM,data:fHLGyI6xx+M1PwrDklQ9CWXzexTTZS8U3g==,iv:2naig1GOl9t+XMS7Nay5Nwzn0Abpo0p4+ihjEcH9aQs=,tag:DFEvnUIqLWrbaBp6T7Nt/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TkdxQnNXd1g4SHFJOWI5
            dUxlN0wxOUF1WUhGN2oyYnV6Y1l5UXFtdjAwCjcvay80bUhXS2t4Zjl5Z090ajVy
            TGtKbGFkajUvWlRNZ3lBNXM4YVlpK2sKLS0tIDJCYkQ0bUxCR3psNnVMd2Y1Qzdy
            ck5aWGJLRm1kOHVnTXpJbFFBTHJwbGMKOX7iYJ7o7bJZeSuG3OnwW/lXPG5vCj7n
            60xm89uEoaH+UB2x4/gTYnQTtnFPbZwMw8JG/hKvyVEVM6T4YervjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T07:36:09Z"
    mac: ENC[AES256_GCM,data:9kEqtCH/Kn8fKMM87UEtReOiPbAdGpEsjn/IQYt7/qwYp8YzU+aWxHo0q4mvGO0Nqgrrw2ZW7N6lMbzAmLqG4GwWX7zJsJqq+7Z9qcKyNmOEAetwu+Sx2xV5E4vRIpsveApEEuQ2UxX1HRkUgc1FPFERY1U3Pw2l53aUGECJQ1Q=,iv:33kQ/Avw9UZnzVcVQKeXXBR0HVQxHdXHwgYpzueGX1o=,tag:bZV+Pu51cyqYrq7o0lyb2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
