apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app forgejo
  app.kubernetes.io/instance: *app
resources:
  - config-pvc.yaml
  - helm-release-new.yaml
  - secret.sops.yaml
  - admin-secret.sops.yaml
