apiVersion: v1
kind: Secret
metadata:
    name: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BQ12HrVE4h5hMCtCkxiBIH7tVFwBgenMxeS8V2KWGFeN4w==,iv:W4Gxsa6JtWerH86TRYufTrt5hVDz5SnXy5pmdbvRFD4=,tag:ehFkB+8nfX6G/yff9s6tKw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xvQds9gH2Q==,iv:Ij0qQJnYpzyhm0wX6oQlCOXk2TIBSQJlWrIRSciJah0=,tag:iGfvpMfzIzW+V19j4prSsw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:VWt0OkIIoYNOHVFCpq1pLjVV96yIQPXFdh+OnF7gSVBLp02CTi4Mbw==,iv:o0egbD1plDc0W0EqH+EoFI0oPcwUZodcMEaCkzNC42w=,tag:NtrHwfsnsQVXNkhqeioUWg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:U03UJZaPYA==,iv:jEbteJw7x5JF6rq3CDdEbbLchsfQwdHIyED6IomnHY0=,tag:/NFkW49h1uaITnMSyrK/rA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yOU9fDnn+q8/w7Mv3OVz6x9cHV4202iVrZAtfDPHjXUgpMkWazH1FGwblxU=,iv:srV1hd2hdXxGG70+KopXEx7Blu4pwK3qCFeRF4zKFSs=,tag:nd/WX/315wqS0Xs76m0iBA==,type:str]
    #ENC[AES256_GCM,data:Ph29fKVU+Sk4ggvPQUmWgtdaWBT1TSeEej66HOuP0SuR,iv:KSGNUCrGOqHdOmAiK7H9G0fdoUxYPXc3A66Ne8a0cGA=,tag:RE4UHUYjnvBk22ZWBGqC9A==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0LYTT+GH6RdgtG/jVeifsUMkG1s=,iv:D4Mh+LCUqD4ICSuBcnduu1y8hdKeXnVKlhTHwIYXsAI=,tag:lbArKtgKyGJgoTJHn9HUKQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MuCANFigL9HXhmPAD9EJ89diyDCocj+AWo2x+i2zsd0mkbK13rO6dQ==,iv:cSeEsLqgT3fuy7T5EtCJB/+r+9wEvtmPFlBYjeip0Ng=,tag:YspQ8FvWwO6RvxSW7zXzgg==,type:str]
    #ENC[AES256_GCM,data:uukUOZBBrJ6t2nUP7gTEbYb4Nvl06Y5sA+l3QS9VYA==,iv:JcXRBKSu2GalcJ62jYDnE6G+puUaH2LvoW6n1Tbjfi8=,tag:0CCS37wHWfFGUOgEIyQD7A==,type:comment]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:nmtcARR+orW/lmXQfzyMFsXokNEiDgjQo2BpWmorFxtA3wLMa8g54EJQz/c=,iv:xHcoQZgeJknm6g+pyWdFPUyLRhrQiSCA28aAAI0/sUI=,tag:Kjf1KgvN6Z8+P7otijwqtw==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:Qg2ra+eFRaCgAlaTMaYEn0nS/UQXwUEMddCm5ZDdKNNxSpf1vzY/gquxCq8=,iv:A5HT6faYAMV4Qu8NdbD3g7X00deahTK6i9BdCPL+vpw=,tag:Slbbek7V/lnCqp29GRay0A==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:q/J5h1w9ZWnN3Irm8MfA2gw0wID8aGUSb79J5oAVa7wKVK4ZwrvVLBkwNc0=,iv:zfcumXZ4sRbZ7NKWFeIRij6MSQWQiiwx3LWDHjAC0gs=,tag:GD5WnCcxeEZYjoBolOz0VA==,type:str]
    #ENC[AES256_GCM,data:KgUAYzMHfApOVzrMT6buC0b3xZK6uLmvRsGvBNqTTQ7d6ZSzI8q+XmZIz8vBm9GZJXNIa6mIQw9E,iv:c5qBVKz7ivI8OY0g0IaBF1MzPTBDI1Qds34F3nmhQPI=,tag:x6OyLmP1D1j/g2nbXtJQvw==,type:comment]
    FORGEJO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xuuzSt5uEHJR/WqkB/vziyty72viy2lq6pdbfucfMCA8hlrzuA==,iv:tYrpBpYYpsOTZtl4ZIZRtvkG4nuUXhl2WqQ6GF8TWFI=,tag:1MdvJs73BoEJFS8RHq8V/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMGFuWWpHZWFSdm5ZNFlQ
            aDBZU1JlSnNYTVZKa292R1dPQi95bWtxU1VBClVGZ3VxR3d3OTRRbnlNdnJkUTBp
            ckRJaEp1L0FzYlFLRzlGemErWDJjc0UKLS0tIFZHR1llQWtJbVdwNG9sbFE4WVhz
            TTNscjlUaytHeTJVVmEwdkNGNDE0VVUKt8SHVqfGxixzzXNPCSDhg7HBY+tEnD6a
            o/NfMxLS4QaDH+YWPpi3tVUEeA/rFT6ya4XW6v8i3mBLzynqYEf42A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T08:18:19Z"
    mac: ENC[AES256_GCM,data:2XkSS9Zcz40bqV/XLGHAqHsbwWXOG0883J7HHbmvjjxlcGQz4RsJoTRGZkzwHzvJyG/Y7JyFcMRgpQ1vypRlDBMDMzeBvNurzaCJJTIbigHwLuIdzZaaHttVK07oIxoWXefkiwD3wn0x4Gq8bTgxYSM5KdyRgA+gImKoDSN4kTI=,iv:9N7kMKL2/h9/sW4W9F/B8NhNU4Ut3ucO74gyfzDv8p0=,tag:/cs0NBvhKOepQtsqUZ9yMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mDDa1dL+Wz4OjnsiqvOpShhJHjJfCmu5Qi/jIB10sJXgkHw/bolzRb0Rg1PGr2u1xqs=,iv:G7Qpf8R+Qo1ApPuk5OORb/nSvZltSg7x2JZCLYutpiQ=,tag:dniwT/R9haRCpGVAZHQmZw==,type:comment]
    username: ENC[AES256_GCM,data:9ciQaCk=,iv:dcfmvLKQkVs5MEjB4xXWqUlQTcFY1Cnkuk9rqBj+X/Q=,tag:FIbILu3Py6vbopfSCdiETg==,type:str]
    password: ENC[AES256_GCM,data:4sNPh+jlkyUO8Q==,iv:Fy7dbOZ2k94nQTXzejtphlQacLuKaB9/U1h5Kq4SmlY=,tag:L7zFtjizImV+ZyrkIIpKsQ==,type:str]
    email: ENC[AES256_GCM,data:sIfx/cE2iWGSt9HuOn6jOaK75Kiti4Y/kbg=,iv:sCj1KRDzM/w2qwkcDGBTHLjyzW3pnlfP/tu5rPsyO3M=,tag:u4x1eBPQebDw6lEKuJsn2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMGFuWWpHZWFSdm5ZNFlQ
            aDBZU1JlSnNYTVZKa292R1dPQi95bWtxU1VBClVGZ3VxR3d3OTRRbnlNdnJkUTBp
            ckRJaEp1L0FzYlFLRzlGemErWDJjc0UKLS0tIFZHR1llQWtJbVdwNG9sbFE4WVhz
            TTNscjlUaytHeTJVVmEwdkNGNDE0VVUKt8SHVqfGxixzzXNPCSDhg7HBY+tEnD6a
            o/NfMxLS4QaDH+YWPpi3tVUEeA/rFT6ya4XW6v8i3mBLzynqYEf42A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T08:18:19Z"
    mac: ENC[AES256_GCM,data:2XkSS9Zcz40bqV/XLGHAqHsbwWXOG0883J7HHbmvjjxlcGQz4RsJoTRGZkzwHzvJyG/Y7JyFcMRgpQ1vypRlDBMDMzeBvNurzaCJJTIbigHwLuIdzZaaHttVK07oIxoWXefkiwD3wn0x4Gq8bTgxYSM5KdyRgA+gImKoDSN4kTI=,iv:9N7kMKL2/h9/sW4W9F/B8NhNU4Ut3ucO74gyfzDv8p0=,tag:/cs0NBvhKOepQtsqUZ9yMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
