apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VXBMjL3AhZjkP55XikiiiVeC,iv:FBcRtsCyce+JO+xJwPR7eGm7e+ipApm/sc6p4H9XSQ0=,tag:N7cKAJlKJFyP/tL4b6WFFg==,type:comment]
    username: ENC[AES256_GCM,data:79GUqx18fg==,iv:R+rZcbGNbjvAjWOjV18maW+YgT1QI9YYFLqCs89Dmdk=,tag:JgI14rTjvLw7+wMPiB93UA==,type:str]
    password: ENC[AES256_GCM,data:DnPlaC9e2JFPg0K5X3U=,iv:l5NKgUMTMCWDh0WHGDYHZ5i72yr6MREp5/1b3llVhxE=,tag:bAxdAdM3BECLA9SxNweZng==,type:str]
    email: ENC[AES256_GCM,data:zbpbw0o+9Qx2so/PPqej,iv:rPbYNqrou9PgAyFNe3GSH5PTYzCPQtzrQcGRa0PyEzk=,tag:i0Ak4+HTvT3M0flga709LQ==,type:str]
    #ENC[AES256_GCM,data:xnUSiofautvx8XBPwgvafXhhcoYnM3g=,iv:ilwwEVxJp4xME2KW15brW0OCEfh8HSRR6AeOU2ih3m8=,tag:vJmsqTnjnS4y+meU2AISdg==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:7Q5uLlevcw==,iv:2dcpwPb8CeAK9z7yVa/lRplddwqqnr5SHWX5etrAUDM=,tag:8pEk60mIUypxwu2v/B/jwg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rSKU4uze3Q==,iv:1bBu8yF5p9SvB0YD4hW0PydrlwYC9Trvm49PbXHy7tQ=,tag:j7+5FoMbp34ZJEJh2dBCAQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5XAdGkrRc+D1VTEmTICxMCjrug==,iv:56Ufji+6pyjENydivlxMRjtz1cgZwnRezVi3tNTaRm0=,tag:JjotdsppUs1tZJsWooroxA==,type:str]
    #ENC[AES256_GCM,data:+Rt53QuPcU+6AGuDpAJxdwZZvocHHl5AhD4QYK0tFCY=,iv:dpq1lgUg2ZUK4HEun3JeUJ/WmRXMzhprnmM3EuKG3bM=,tag:FNrXnnkleDk9ZcIUd6rnqg==,type:comment]
    #ENC[AES256_GCM,data:DQOQlohcn4l/I2U2jXWhnvITN4L0VrVj6K15pwm7eyTDnQctjo+3cAD8Fsu5p8GrhEWmuw==,iv:UInG+MLy6XQxsWhbHdOL5LhcHtl9JhaJ5qVMif4QH90=,tag:PZShz4n+anqfeV4FspRGpw==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:fcAvg0/B9O5sDZ5DjgoR8CneZSEqisPl8gpiveJ0V3wk47ozmvU/icZORhePvEuz+AO1c+45nHonjol2ZoZzaK5azBwy5qlxpExmfzurQGmM5iSn3kcZrw==,iv:/KXDFMbXCmd15S6a88c50p/ECS2fpwa1r6FzRGkfdIM=,tag:mdAm6HmxXXd+wgew81zEUA==,type:str]
    #ENC[AES256_GCM,data:kDmny5ZX7FecQDCGmFqmJxOb3am8jjvgKGiLeW3PaY3WlVWW3GebiAPO1VLBgxOVEXcDlwp3,iv:/Dp4RnLMzTg8isO+kIu6Y+Sy/wwWydr1fMbnExZtfns=,tag:+50fQj7+7catuJDX00UHxw==,type:comment]
    #ENC[AES256_GCM,data:jrdMNU3Aj2NSCKyYrjeZcfvBrxQIG49D9iVodH0UcqPqxwXyM/MxfHJQObjJDw==,iv:yxpIF7YNq/DRAbpoggyDCAhS2dd/YDH+CfoRl5+lEd8=,tag:YrNdNQ/eOeTH78IdT28qNA==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:8bR2gTW+XFbHQUXbOQcAv8kqg7XWTYWtSS7WCNuV69LG1jzm0anchq+fN0ZmEx9+fd9o16IeWEA25DKhsRY0D2mVcz1TFGbLbQtmCgvKBScnMfxygP8uuGWXleTqDpn4HGws0qQbRZ5co4RIY03A73Co0Q76BQSjxvWcibptdUgRP48cFcL5bqmr428=,iv:D6WpTvH4j+8OzFVZvvAVHERDUJDJug1SlwQIH76uraY=,tag:mDq4brVoMRs4tJsx5OsQtw==,type:str]
    #ENC[AES256_GCM,data:v0uS9TAy2iiGUiLNH/eUKf71+YRj,iv:qEqd4fGsaxjs3v6fx0BH3lFgmr67raOe1yZ9wqkqge8=,tag:6JAni7DgzEQX5+VPTPA5fg==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:8XfaD22ytA1/Y3wdnZt0krOB1HU=,iv:WpqZFjkwlmXlyUoCTU7Ipt6OzU7k6y19IgWFs8bP6nA=,tag:UO9vLOf4wrsiWixMQvqqHA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:avtoeZm38XUw4eKMBkME+4tNp6lPrmnofGVfdOAmg3llr2TOJS9RqA==,iv:arOOzRle0dGXngw31bYkUAZBc8yr5iUwaCEb77SddNg=,tag:l1MXMvl23ToT0XPO2tu+SA==,type:str]
    #ENC[AES256_GCM,data:fPDnw/N6v3ey9MR/ttMPbBL9W1nTMEPTMtAtERFNfuZhmLiY,iv:MyQ0GQSBXa1Z/MZZoNnZwz/dqd+eS1v/zb4Abtvj0aM=,tag:sN/Jzj5jtPnmN516ndgw4g==,type:comment]
    key: ENC[AES256_GCM,data:GPdveqTFVw==,iv:kJsqsWWHtJubWLuHQGcKxCxYYZ4WuOOEFNzmxulyKIY=,tag:1lrsJ4ZE7YYJx4yvDpSnjw==,type:str]
    secret: ENC[AES256_GCM,data:1HoI91tFLNFGZ/zvmCKfqo85giZBcxCfe0FRD3eZiVCsbC/WBw==,iv:dI3Ts+HJiNs1dw/E2KyVwZIuiChyupV/dkzx02CLFsI=,tag:UDO3XPPlbTJhF8H17rtVrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMDNwSllLdVkzSEluaFk0
            S1RKT3MyWTUyYlhSYU1EaW15NnlRZ0k3VVRnCkExa3FTOWpLemZKM1lLUVJOY0Fx
            RnRLV3FmeS9UMXZPSEx0NFFYaDRLTFUKLS0tIHNNNVVMNndKMDRicXh4c0crZGJ1
            cVBOQjBkL1BmcG9CZHUwUTQvYW52S1UK+FxEd+Ra0BOKPQvext+RI4E2AuWcbaYA
            4Hvb5saOoWwvjozkw/GJry7p/wNRP0Gge1NLWol7Qje+pjoil5bKsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T02:20:26Z"
    mac: ENC[AES256_GCM,data:cb9qmYr/SLV9JMEu2Hp2HfkRSHblVQIjlWmraRNv7jTWRicPoirPSUdTcSQnCImFgcB8bhPh97CPi6zkfmoFVkjIhYammmixfU+xhcfL2mjjQyzb+QiIwz+ALDSLE/tg6us+lqnjHC2rvjVfMwiN2Cb09BVx5GYFMwz8johiJJ8=,iv:Y1YOThuw9I6LfMIm/dJIrOaYj0mRMOG0C3odrdlHRJo=,tag:p33lhpcFAjhXWL/ejV7+zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
