apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:E6/n9TLhkqJio4oellMhFWfh,iv:caHGlSlhpfuk19rujeVE0aDNTrzMBVZWfBPxpd1ZLHA=,tag:BgXvBa/uqZViXNJ2jVz+Pg==,type:comment]
    username: ENC[AES256_GCM,data:OudYNh4=,iv:iNL2tjy3T5Z+BDZ4YjhXGBL81bu91RxTHAKMRVviXJI=,tag:Cqykjs9FGqU02sH+3VuFkw==,type:str]
    password: ENC[AES256_GCM,data:uugWDSlr+2iSlg==,iv:dpkbb+po6XJlyviIkYMneOyjRNEd5kR1KPfB9aeAtpg=,tag:uqahKrgLDYBReoVX2yEuvw==,type:str]
    email: ENC[AES256_GCM,data:Cbwxsgqx3hZSc50mHeNx,iv:46R+GxOpfdkWB1oNFQZp2bLghdrW7FWuBTTnBeVbKzI=,tag:dhXQ6Dc3gn5dsf+o7LPNNQ==,type:str]
    #ENC[AES256_GCM,data:hpBgZS6dr7LNIVoB0lztNyJjlqqU9fM=,iv:TzZKNzBkDDWAYA3XUnGB0S3PPU7ODaHw/hAxMu40jNo=,tag:ZC19vriCnBBjkQSL0P5q1g==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:MDNabZowKA==,iv:mdlki2jr00V+sreTIL+rMukHsiA8dOeaXW+9cHN5DGQ=,tag:DqiC/M7NRHkFasN/EMD8OA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6Tt/V4Etnw==,iv:3x33TlNxgbHM9MruyAoyji6FHbJYQxjQdY6FN71CRdg=,tag:P/nh5J2N75sujhbjtzi7yw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EWE7rC0mlQpfHsUgTYB/xYaHzw==,iv:h9mTrNJq2CLXi/JURlNEEVOb1VS7yQHcZaOyiebjBf4=,tag:4DUmOclA+IpvIqwU41wGpg==,type:str]
    #ENC[AES256_GCM,data:3td7l/jR1kNezWFMreZg+StmK0tZgEdSWTnlxpYOH7g=,iv:o3mc0pG1Eku8jCv16mDJtsaiTwXT120T//qV7GFSam8=,tag:QgXJfJgUn/ld+w/IAp89fA==,type:comment]
    #ENC[AES256_GCM,data:J5EFNlLqFM1H2uu2oqClBT/HtVjWRtEeSreuUn3ob2dm4JstBhVn3/wJIT+ims5aZ29t+w==,iv:QB2Mqs9qyMHv0da/Lntt84brWcYEAg79aQwj7QuVO7Q=,tag:ou0yXcjJgkH11a4Ewy/veA==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:RihtEq0tHGT20KGFBapx9tQWWEkHQq4K5tMvVq9X9pKnxTuzAI26OTU2O11/NJCGkyjIZ1f1irmYTN48RyQQ5saTnF5BpdCX731u6fQ5TwWFN3QdhmJKag==,iv:TL5NoPJ1nS2hbGa2C5cPmdvaVQNc9CelMxH6/j1KbFA=,tag:qfbuUq7OXYiI+bHZAE5mKQ==,type:str]
    #ENC[AES256_GCM,data:54YOifS4G6n/7YeAoNC3o0+M6dXDFYGRHZu6WiKmtSTpo8GgUBbUaNythoWuLS7bhF4a1D3L,iv:uLb5q3IGiZJOAXMWaSX0sRVWPaXwjSRnuExbT729N0M=,tag:EK1pb8XSFPR+f/TzNEzA4A==,type:comment]
    #ENC[AES256_GCM,data:o5KWSTJKvEOi5yYDiQsdjLtvKgRJ7obZFmWZ1kAikVzUeoR1jQZ1QleoQJugIQ==,iv:sDbIZcECET7KajXLl5THfNtTSekfu57eTLJ3Y0XUrLc=,tag:1OfCd9wdaM1zIP+0yEz/JA==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:jPt/xIWsOmnSDtvsRv8C3W0OkBHwTT0MMR9PrmSqM4FjcaK0sDLCJ3FIZmNJGZqQ7wE3fgE5ETpzE5NrGCxspIJvDC4ossfN6hrM2c9iIN9B4EjyJHq7n2K311m9xLiSlKpCBZCZk1+kbshbIoUeTHvhawfr/MZQjUB6aZCjZ99OFSeb32X7Icer5uk=,iv:6tZ8gxgDWI1risahWxM7PHDqx63Rvvky67ONOKtFhnQ=,tag:a5mRbCGkpVQaQ4EMQ9r+Dw==,type:str]
    #ENC[AES256_GCM,data:mwF2TEQkfUD2UTZjC7IV0OA3fnhI,iv:y79gwX1kFEmgRngkW/fk057XQ42DE96pD5aoXEuU3RE=,tag:RTDrSkDGTnb/XjruAJ9xmw==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:PiO/GZ/463M1aIMBf/tx/ovO2Bs=,iv:8YtizX0TAUQwa0Uuyx7IoANvApnKvmfToMTfvWXjKvE=,tag:wkLAKhjXodRQlhSiLXm3gg==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dbcjd8By5lstVdhI5MH02Fei64EOYUdUo3gVtOWWRj+XlkDK140QKw==,iv:CIyzexWZkCPlnHKTctewIiAI/HkWmKOAucgd8PVUftg=,tag:o1o4iLO7Ommj/beE26XAKQ==,type:str]
    #ENC[AES256_GCM,data:5t1+hlFuaYvx2cKZTLWe5RU7BjUebf0A84ZM1yYqJUck0Lth,iv:E0YIra4AMqX8x9FHPWqHIkkH8MMAUKEAyjkn/q1Oxtw=,tag:rHeVBpy0YjS5Jp3HC2WiRQ==,type:comment]
    oauth-secret: ENC[AES256_GCM,data:CHpiWxfqBx1LJYhOifz/d84U/9Q7kyD/kaGXy8UeG8HCP68i8Q==,iv:zaG6vsTEhk0XFtmb8zpVSOtxo3FkgIhr9liuUgbjxIs=,tag:gXnam1cf8csfShXNRcQBvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTDFmaE1EbTJKdHl4MDA3
            UkVBbEJKYVVNTld6ZmRCZkdyUDJQZE5xeW00CmMyMlIyKzcwcXcvV0o1ZmJRclFp
            VnJXUVJWMzR4aVhSMW1VSE1vSng0S3MKLS0tICtxOVlwMEdDVFk1V3F4WCtla0h5
            bmg0NDdZU09yNjR1N0Z0eE9qemZjNDAKyWKnWrln9U2meco03h9YVtSuQ3DgwTG/
            VDLmoTNNS1gZdJgyuh4Psm2Hf1kLbHUGKExhYWfwGGyqmlv5KqIrNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:46:28Z"
    mac: ENC[AES256_GCM,data:C29e3+88z0+my3HCpl1tKrBXdBYtKNgkWXfsJ+zVdJwD/eKfVmt7WINl2aqcSUMctcljwskSmegm05Wdr13X2BWx73a7NOnr6njz9PdQgXPEcXiV8o/hkFAApwDb9C8CgkjV4SHbb8verzoJNRY6ARg1lPIDdUprm6Pseevqf54=,iv:oeWNv3/c8xf7683PRiI1XH4Vlb+S6KZVU/OLpBRvUb8=,tag:goo2AtrQ/+5dV4s7xCikIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
