apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0XE8s3I+Jeh3GMKVh9fAxJXN,iv:37P72g1CdXO3HfbVNIUD+lDVU/Gp7icWKToZlZfJI50=,tag:OLWbjYYb1kMqiOj1XMTlNw==,type:comment]
    username: ENC[AES256_GCM,data:fS5NCj1Z7Q==,iv:B0Ru6Yb5x3ri5j4H4lm6WWzm8T0WQYfhaLtZ1yJ/rV8=,tag:fV3IsFbnibJepYksbrv9Rw==,type:str]
    password: ENC[AES256_GCM,data:AVQooqDE6OYJkyraEic=,iv:IRhu7L+DlZ9O0Hx97X90TXPaTgRtkO/zLiy0xoOlzDc=,tag:bYOU2w0RBGNoKUYV8soDuw==,type:str]
    email: ENC[AES256_GCM,data:GAW2C4Hc87mCMt4UM8vk,iv:REuie9zDJbZzKh2fZdyCYM78SzsMIGhIRNBgtnxisLw=,tag:/7qb5PFcdUhSl+1pDNoiYA==,type:str]
    #ENC[AES256_GCM,data:dWH/IvA9dvuY79YvG7ehv51ebmqkONA=,iv:2GxgZ5EdCinPmNsDWJ5AWomzutItM/4Y811yTQhVYvE=,tag:b+WeY4OmQ1cWHuQqzX27Uw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:+Jz5sNssCg==,iv:OSoPe4IbCkyBdsqDj/w18ZfJG4XF3ZItsgS6Lbnp4rQ=,tag:CjIKGEcb5aUraz0mJ1bnZg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:zRcz/WjwmA==,iv:l3NyxriuQ1nga+FaRqTpOS41OK5PAdynA8SxdNVkmjM=,tag:C0OArxESOfrPQ/lUCIm4OA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IbHMzTlSVr6225Gib19bIu3Gqw==,iv:v+K89TXYyiCyR3wUr45NxxlDoUAzZXOgZKO7JT1Dh/c=,tag:jRNJwz/jwcg4oYLCvbsGlA==,type:str]
    #ENC[AES256_GCM,data:xzlItwUTd5izSqEebAG+5Qn5F62NkGkx9EjgzcH4BDg=,iv:Q8XFJ7Ask/JqPcvB39GYXLvbdDvr5fLDUwPVdgMVbz4=,tag:+azPuvNf6csohZYq3w5hcQ==,type:comment]
    #ENC[AES256_GCM,data:YDmky02Pmx5eoAbIOZCYV2iy8T9qP0Smw/7eZWknsr5JXfEF/jM1us1w6o/YTBZ+wPxmVg==,iv:nXOjd4A+9gJU/Ot/P28KXLX3X0ZcfW3qDMP1RqRyCUw=,tag:hYy+rpQnIFbFR7+J7qX9Hw==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:gPUW7KIQibnjH0LAN0lOH9DakKqWlKEofXzJDIWugkb4HRTfjSHuobsJksh+AwCwbqTTRhviKhX2dp8e2hpjdVTKVPSdnTVvPHXb6q1o0YL5C0R3Gf46fg==,iv:nuq1mou0DTYEJJe7qEFSrvF+gWstLSa6MitiOUbbz9g=,tag:E90ikULZrP5IMbhnWgupBw==,type:str]
    #ENC[AES256_GCM,data:LJErPb7tqNHXH/f1p4MAplB0Cca7u9d8g35rHpQtujF5aDJE/WGg4B1mF7X2cQ6xU2yL1zZp,iv:Xvkw7qwBMqIKZUnawGYjWrjDKhyHPklEaIBm8X3Cjlo=,tag:8uNGzkxQu8FeYwjbzsz8jw==,type:comment]
    #ENC[AES256_GCM,data:wPk8cumAMcoYIHrxxpDEy2FZVEBGyEZVX9YNCpTr1Jk7/hyHQxKB+afcKG+3ww==,iv:6ftoUJAuAU/bcr5K6t7Z4LTFbHYVj5CE0lKKnzqTYr8=,tag:beYdI88dlmW991sz0hN8Lg==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:fj9NMDMcmTDmrTtIK8Mmd28yulLngCV+v7Lqbh6poODzCfjGlvhZvZKXwz3ZWrLUhKZI0vDttOYAD2wj/REJ0NGrWTlkUI8KNAAqj1afQoh881bWWtoXqsim8FpGqKiRFbJRnfJYId/f2fBBv+Z06jHmEckUJEwkSOFHKtUj7KqA/PmD2G3oWrQ6Y38=,iv:oF72sJJqibZEvQraS04XLwrY4Dfwt5wo0/gx4JUyJh4=,tag:X39VTIdeVjJ45wgu659F3w==,type:str]
    #ENC[AES256_GCM,data:gD+LJmxknvSi3gKBjN9hfqGIg7G8,iv:HbHso7wuSsWU6MrBbm8Nd3/fe815vMwWFBOfaofu8AU=,tag:lIItjIs9WZ4qTt/IpATFhg==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:mLho8SL9GuF/erfMDtU0hEjPcEs=,iv:tj/jrpqgvrX+hxBLPtayeIBQ/y8VGkkRspcUwPVMN8I=,tag:LrfKw900gOIvW9HnaXETNA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ncX5Lt9Suy7cQYn9ov1wLHgi7/jp+yphTP4qNH8KoMfFvnXOHd7ORw==,iv:esYNgCgcuQ3vDt7y+LCQL17x00XmH1NiVrLQt18iPfQ=,tag:ouHZKMv6nk6gwaqxd/gsKA==,type:str]
    #ENC[AES256_GCM,data:4pJgRCp1GEoSKj48BPxLA3lidgDbyirJM6S/bEEc3B05Z97c,iv:l/A4Ow2ddSZyn5rp47sAjFuyeUJwegWuN4ECDfQEs5o=,tag:A93CVnhbnOE9bdJQao+ypg==,type:comment]
    key: ENC[AES256_GCM,data:HQk8JUxLTQ==,iv:+hoOkDg8SE79ELskZA5k1f0qqmBgFYVbEktW4VnOZUE=,tag:A56aiR6IuY/EFEAJycUvNQ==,type:str]
    secret: ENC[AES256_GCM,data:18dpWurXmAro7SpPoQlp5sIUq3ltPsOqVTZ6TBJ0MFWT2hgSNg==,iv:f/TWXxc1PTug3V/Ud/lUneW5CabDFSJKNh6SS2WhpTk=,tag:jjtBCrQ6WIjFgp60tIBipg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVXh6MjdaVXYxcWNRZ1kz
            dGRFZjlzU0JDOENLWEJOK1grVHBhdHJQUDE0CktSSWVoOFAwQ3FWSXN3d29UOTJp
            T3BwMXNSK0xrOXpmdlNST3NyYWRiMlkKLS0tIC92NWJPbjduazdheTFwdmdMVXZO
            Y20xWGkyWjRGR20xY2xVSGxTN2FuTGsKDn7Eeo6XVWTEMYaAfITKgOlEDRn/0SRN
            bXMHIiCMAKLb8WgvAO/wljmaeArQJBGfGYHzJWXlWF49iC+g79kmCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:51:06Z"
    mac: ENC[AES256_GCM,data:AiBc/mrcghItdTmbeKpD9eUkMZQokwmWUYCjK+sSODOZxtqk4HP/ToixQTh4wapuj5jynUOBNXysdrOR0j1jamqe3YQiBdnW30vbhQ+TDmvmDXQhs7VnR3t0T5+RIDsXpErhTl9g1E/RbwUZflpCHBJE2a5U1OGNeK3cRnWzuNA=,iv:8KcRSMbpJWvDOCb/6KRneXjdVy8LMK0i4D9iil2xdqY=,tag:rEPbrqHPgVQsam0Jo65uGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
