apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:n4q+MFPyIyTui2KafXb72iWg,iv:qJEFkPH+7FEudZlzUn8+IW7FAEyHa9aLDGYECO6PNoY=,tag:V6/A8IR8kmR84YuiYtcj1g==,type:comment]
    username: ENC[AES256_GCM,data:A4hIbpw=,iv:xBfKMSjyZcZbfP7mUqyJeOKU0DT7xywDbWhoeIUICtc=,tag:E7GRT0gNx7UO+q08Lg7G8w==,type:str]
    password: ENC[AES256_GCM,data:J3f+Mr4muhFAuQ==,iv:K4O3yfAlZePoxOy610LD5OdY59xhncHuEEhTfre9FrU=,tag:PBNl0C41vS3EiFwwMZ9koQ==,type:str]
    email: ENC[AES256_GCM,data:Wuz6+4LlzYtTdTlrQvFY,iv:G0IcpV01z5+Zxts/l3ByuqVACHxWCic1v8lz/bNyS9Q=,tag:XDGwm88aAqDPtKjXWt4N1A==,type:str]
    #ENC[AES256_GCM,data:HQAkDmtw2CPXmGPsSL35voe4KX03PlI=,iv:hRG+54sxB/+KCXnimbrv6j6cwxRFAYOlbR6oRURAqXQ=,tag:TRta4G3Eg9+lxQZiwxLqJA==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:5FTEeMFiiA==,iv:cjAAjnSSZTcgR646x0F52HDSTqmL2SxQMPyfpP0bHQ8=,tag:Tq0z8jgwQ9AigFdrFPrijw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vKoWAsHR6g==,iv:rBX3WqRtS8+gNBmKtLz+a8k1qn/MlibYDmyq252sCcA=,tag:IX5EAS7+eUKoec84reIdjg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2UgS2uiew/r64wXRa3pJI5gZXw==,iv:Y7Zgpg6+sUyeCJNLoz07t0uNopBykbZByC9ULfwg2oI=,tag:rN0FXG9q1szgjAIS4fjlaw==,type:str]
    #ENC[AES256_GCM,data:yWBYvrktg7FTuMfdT+RG+OIjkmPnAW2l00DH3KA2Dj8=,iv:aqMGP6D0tgFZxnRaGE8gPs5bgMwo/YtXjiljDakRHd4=,tag:M24UL9Xmlxvxmobnb6AWfA==,type:comment]
    #ENC[AES256_GCM,data:1n5Fl99/eI/mAOTrvhsMuz4/l2Jh0Eh76cMGQGqADgfr67RjnCTZRjD1yzBIQ2Jwx1eAsw==,iv:SVBM//f33NXPEjT0XMhN9ndYLYdwOE257UEZ6+r5HBY=,tag:WHhEgZ40Agjtb1hHBK8/wA==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:/SOUpC9fS+aAtFZcziQQTcLPjG2kY2ibCJ1tHRh2JWhB/UGIKaMsl3sM5QjgbE6mpoKg6onaY+t73tKzLwo/cyPSrESks2TIey1hi2nBaqD0lPm227K5eg==,iv:F1jvswcPHr/SSoA6RjxnI/iUdkCB2iUVYF5koNGE92I=,tag:0c2diIbwV92tUUM8V+mClw==,type:str]
    #ENC[AES256_GCM,data:0wwZH94YtwkfiAZDpmx/E/vFOZyQsjwATB06mMvfVlCRCZ7et3zHYn1tBZwIBnZ6Rv/8x1I1,iv:s1dy5CWqWjLbgAMBQ8QC1o3AoUV11MvKLFpneE+carM=,tag:zV50SBXdlerJe9YnVQPUNg==,type:comment]
    #ENC[AES256_GCM,data:IkowRhryiu/nBfnDTyqq075ZxMbQ8H2zaK1/b11qAiZ84aDM7pLKeWWoeXl9hw==,iv:9CBqaU0lJIdDnloXuTAdxATzL3hIfLutgl4P3faNl/I=,tag:0wHWfPmCgvT0y3D/gCL8bw==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:019/gdDqlHx7eRdFUpjZtc6pe0skhrolYxVCXbwAQUFcSD4akjXd2UO0X9qjRqXHp+9hVG4X4RP4Md50OHB8tKGCrITHSOhAqg0fni+ZXMPr1puDuGyQHvqS/sTOTC61MRGxGH1w0KvYNxkYgWNkRtAxKIFQnadXHN2c3+lFJagMzh2rh+f5M7kUkXQ=,iv:AfcqwOZshtBeH2v1ZEuxzEt630/JyfQlnKK4gyeI3OE=,tag:VHnVC6Q53svdUIp2p+be6w==,type:str]
    #ENC[AES256_GCM,data:xEsoWphzNtsBIo8YunTByASq/+DU,iv:cSNxKHGct5IY0pf4xMktO25/KvDXgC6SihAipgrgQ+Y=,tag:22RzlFS2yuJOHdSVVmXdQQ==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:SdKc4zWZDsK2t/XvvNCv1zEf1Cc=,iv:ZyzpgEfF3Uo1v1FjxqkUaG8LnbiJHWSKwLysrC8xUHw=,tag:6A5d6B32iTHOJm752E9Ixw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1LFR1C4kSSS9TlsUgGWyfury4v2KV8j+vsxU3cANGkS73LXUxdDD4w==,iv:sI6AVavMmhUierka73JFMGa45PNJXlTfuKf/DhWfOFg=,tag:yrWEht8K/x56KKOHK0+yAg==,type:str]
    #ENC[AES256_GCM,data:L23SnJrbc8mumtPLbkAgagduJfCiYKkw+v0smGzduny1ZHJZ,iv:71l48JwGUbmeLFt5fjS9L8d3vDrx1Rh/WaRoE5xJdN0=,tag:xOyklZlRhmJlFzJJ+yP+pw==,type:comment]
    key: ENC[AES256_GCM,data:/794hZPmaw==,iv:h9nDSFQKHv9j53ref4jKz2AUSDbGpj7seOYpPtAEM74=,tag:bgNTGlHsg93Sm5wqhYY2Uw==,type:str]
    secret: ENC[AES256_GCM,data:1MttEfzGFT2IoGFqGqxM/w5sdeq5354GNBKlw4GMODeRPmHMzA==,iv:c6sWLV1Id63pji71wEEGO4uymBl7IjqETHaB2u+lYyA=,tag:40S3Sal8vMnTYvZp6WQuYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWXJ4UXFhSnZTSFh4cUtw
            MzgyZ3VJb3pzVGowdUZtbmF3ampwYXRGMzBnCnk2RmpOcXMxeXBjQWFJbm9meWZQ
            dGVBQk9nMjVPcEc3NzZ4ZUVyQzc0THcKLS0tIHhBT2krMkhJVlhBVTRJbTBOd0V6
            ZVF3VlV3blZZUmhReXdYWW12WHZLMFEKKQGOH0800al6iZTtg47f6tSr/SW1CKsl
            DWSeUARkfhE5WpM2/UlBJF5I/j+gQ4DhV7z62GHyLJkJ3GgnFRxE2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:51:22Z"
    mac: ENC[AES256_GCM,data:yX1NAmRGl7WL4ByRxjDaRK9WIvSnnBiZTTSt7h+EJnAf9kgtpMOrSVj2cHfBHfo9W4wG3QJFzijVVcn560scTvbBvxslDryzGUzbAHq1ysBW43MyBO42nfYMMWEJc/xvMKA/0jPZEAmBERQ2j1jVZKnF+JOoG1f3cCzmRo7js6Y=,iv:rcxzrt0rE41di7xzWy/x64UrFj7kFFtCkCjbFlPWxm8=,tag:tLlTdDsDRenL9DWvRtxj9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
