apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bP1WyPwTqRhes8bC8zDrXDXE,iv:ImOqoXk2JGrAHBIp/cq+dFNhtkhQeLyPQa7rbk4lYoY=,tag:E6mULdtLY0K5wimhVRipwg==,type:comment]
    username: ENC[AES256_GCM,data:vTyopXk=,iv:U3lpfn0X+1EX01qOHNM50FFrxmdo6ICie4JkfgS8vRw=,tag:eKeJ0R7wkjaws45+KfDFVA==,type:str]
    password: ENC[AES256_GCM,data:sCj0qMCAM9tC2Q==,iv:MN/MjPvYUMb2PrxXxGxPfhmlWw+0MUeyChYR+7ZVRzQ=,tag:gxijJLqSa0tXJS7aOQcvJw==,type:str]
    email: ENC[AES256_GCM,data:u7duuCXDOh1vsNQJVfW9,iv:p8quEFl0kRJc+oGnvBlqMEiEz9RwzZtfF4RuQFxtxME=,tag:9WbroQI4llDDYepxhc3uvA==,type:str]
    #ENC[AES256_GCM,data:Gb9ddbwc485V6Jq9ul5jgMlQwdxLAjQ=,iv:OzwSVnaDdbyc+ne6Wemr7pNAiny52I7lTuzRsg5Vlrk=,tag:+6eB6eejqWlMuaGc2Z5LZw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:iC19/eHhkg==,iv:rr0s2JgqDS/2Z1JMYkocHO3BYXf+gFr5nJjx24gp3uE=,tag:82gv5DLmtwVLcZy1HZaAjA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:zD3XRL2R0w==,iv:mGKDLE9hqBlkn1mCtd3RsF3GI4dFDj+Fvf2xav8zeoM=,tag:fpAI7N3/wV+ILbAHvZJRDA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ape7Hiah15ymNAy9gcJAczsTOg==,iv:UnnZ1iNq+uI+Hn98wLKk7Da2+BXS+P2ASLet9o/cpso=,tag:JLM3olosGNaLLiWENCzDvA==,type:str]
    #ENC[AES256_GCM,data:cSYcH1g3xqgoVAO8U8WaktG+smpTwlblqqcE44rKR+Y=,iv:BAt1ypFvXc1VzIo1hgv8woJzn8NJS1ui9Bbm9RfK+cs=,tag:mFFnbp48c3gg5OOVs7YN3g==,type:comment]
    #ENC[AES256_GCM,data:wVkyvFXQTn42+1E3GzOuXkNb7dId2761mRM1lsh9KYiRn18sfWNONi2sCuXmSzoi8YoB3Q==,iv:KxZZ1NtrjVLnt8s/jeaKb5/OUFO+Da87IJ13K34Jq7g=,tag:1FMrk0SdILirlHjXiUCoyQ==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:WmtVCyU8iSRCy4q906hk0mcZv6JjvOtr0zyVdg8FUf2Hq1p6A+YW5+uRhib7TcJaRChd6Fx1f/2Rn2Si9q6A0d9Ev7lgM+lMWbhoDQ01SLtoJOdTUaUjmw==,iv:kiWyTE9yXxIOtkbu0FU3LoT2QSrPm7z2cmHS1pSZmeU=,tag:+pODNgbpESw5ZNYBy7ZTOQ==,type:str]
    #ENC[AES256_GCM,data:Jw/GQi2kp9nQ//ERD4iBOosErz6FXnWy0zVjafBtie8rcdeS1R4F7dqAJ96U5yf7NpQMaF+l,iv:4L0ZkY9pmwXJNNszmdjdskjC1X9WFlNdCA39LrUy8yU=,tag:TgINMj6ViaO85t3y2v30Ag==,type:comment]
    #ENC[AES256_GCM,data:ZSVo5oXf3Oi1cf1ns6JLXnJtCmHuvJK4hsv+19BFPon0tCef1C60oTHiBy5n+Q==,iv:8mPtADL/mnP7NR3T+FVLn0W+KKddWcE8X+qg1VsAubU=,tag:scx1ZwasAY9hKLrkYJXpLg==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:PalgegYKcNjOnDJGlHBYzFmkG3X+/JSZq24VYYuwSRuj5mtc92KLL4CQZrPIo7q9g2REpVyzUObDjvXypOA6JKacJXSgfxSRYCHfsaOJVTUcc/ppsR65XeUe+ifO8Cmc86gQ1vcjihhjtw8TMvc0X/zQWkON4cZlUGfAvjv6PslI+LCtft+NF6lE3D0=,iv:y1w51+Y47P/qAvdcg8frKi3NkarTlSXK3aYzJzaDRwA=,tag:0t4v1tvV+2A4vxoIBr0mRg==,type:str]
    #ENC[AES256_GCM,data:SpZ8RGebtmw/+Nps6u7JNWn+zNBD,iv:7kibzapnSLLpA8xQcdiZ97B6voFfqtc+BOnNDa00A7g=,tag:bG2eC99WOrhkkCtnzTUFZw==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:zYJKVBCsijFaT2ZXYCOrH3zlSOA=,iv:37MjyI1FfBaSpjaDfLMW/Z2COgPCRfrq+9RNNTIlR4E=,tag:3PdzU6g6PjE3aIcPHirqyg==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kXcBX5kVuqtnlz/EotDIcR1jkGRP8lUXXEMzvEdYeQfmyhxY7Q4D0A==,iv:F5Jo+7b3orGX385io+LMQgRynn4mgVcdXW0yGiUlyDs=,tag:cVqP+9S8hA5iUy2spkGAgQ==,type:str]
    #ENC[AES256_GCM,data:DlozcR+grwWEQAM9YsaWyHnxobu4ExlPua2tDrUpGgA2WHfh,iv:oU5mSytzVoGpI3VkAphc67AUejTEx5H01UZkOAg4TBg=,tag:v4UW+3+yO3DyNe6PNEUIuQ==,type:comment]
    oauth-secret: ENC[AES256_GCM,data:/YHWhiZZ0YmxPgSLh/9zw2Bse66XHgXXUzVRF8gWp7vk3iZT8w==,iv:QVYmhkf5AlPMczPCmVcltMabxJ+2An6f7mO2G2Ao+To=,tag:EQrX+h69DiS7+sit243O8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOExyS0tNMmhpdGhLUU1h
            Yk9nZ3llZlBQZG4zYWFpWW5CYlpmck9iTDJVCkd1MWxyOTRnZmZlZG9uVTRsbm9u
            VVdaNnNQNzZSTXIvOUkzSXZwdkFXMGMKLS0tIGZtNnNXQUJYMU1iL3gxRkpZQ01V
            ZnJSeU55VE0rLzNpRFJHR216Mk1lVlUKqpiUWDnYhQyviuoW6Q3worJ/P+WLr+LQ
            Z6YUKDi8e0MHekewUrxlYdwErWvPLPnMJcvzWel0T3vkfldkR+1Axg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T19:26:36Z"
    mac: ENC[AES256_GCM,data:4BNhq6FSmBC8HS2RED5O44w8UbnBOm/jn3oIJfyf1tyLQCdtlZWjNXzdPdYeNNivJY4FN9dTFly2tKphnI2n9ale5Go1Hs/Xudz9RVl5Ml9yox48iOuPQlzrVA2qcwUcJufIpH2yuTD33K2hUlYPjiy5UEpAjJEwmhKHzUUY434=,iv:g6nZYw44OWzYnVu7gPf9aYa/lujxddZgw/oXDeAZsf8=,tag:rVxbQEBgOLRX1vQS5uSxFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
