apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CsOWN5Age1qmMpKt3iMXX8sW,iv:sasRJcpVeFn6oF4sI5cSkMmHkUN2hmMjn0tM6rUOgn4=,tag:81Y7yzW7ySfbkRiB+or2ag==,type:comment]
    username: ENC[AES256_GCM,data:uf4Da56D9A==,iv:7zN4RcpTLglU+OgeUqne+6ObSxWzDDpuLAz63R9/6Vg=,tag:1/YDxRavtpjQkHHiDCRx7g==,type:str]
    password: ENC[AES256_GCM,data:M6aXE/TWyXmx2A==,iv:zqQV0mvGzfjTBO9p9buaU0DMC/Dl+ltw9L9Y8ajBs/w=,tag:rZmXy7yhufTvig62q0KSHw==,type:str]
    email: ENC[AES256_GCM,data:bHyaov0YHZF4OVvHkTyC,iv:A5kEnmZFSPTJAHtbVDLV1b3h7U/l0ZWTktOxgteZixY=,tag:8f8wYk1lkvPbqOFF5McxMA==,type:str]
    #ENC[AES256_GCM,data:azmQ5Htsz5uJsYkzRWs+KcEuy6oiEbE=,iv:0ScVywtcmKxvQ8rH8ljwgKF/nq05hBnJtSMXEa6vFyk=,tag:IgTEsUH/UDir7bVRR8Pf3Q==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:bpn0RnNmcw==,iv:saAZcSPMnMREj2ctZhHZCMlvWfeShGXeU6dt7ySKzoA=,tag:ljhxYlKzmYjEYG3De49B4A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gFBuC5ZLeA==,iv:+UHFT6Weo9Yly3hq4hHMP4GJNXJluvQS5ZNhnJOM034=,tag:SLx2ZOB1Ue8a05gpbVRdWA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YJm80SxxsYHSPQzDLTaRmNQrjQ==,iv:OOwzTPkZpjog2P73tC+o2MdZWS0f/qkBTWNntPeJ3Wg=,tag:Hq/WszZV/FIlNZSSW/+Z7g==,type:str]
    #ENC[AES256_GCM,data:yrzpb5L3Xr8g3rTcPsDAOfN2/2eEyg3VBFSWgzdETBo=,iv:ZaDzgNEVqo1lQXJVIFswY7PYkZJ7HCMWQUuv4WS8qAU=,tag:slgbkJKbiYSrLEUptoJHJw==,type:comment]
    #ENC[AES256_GCM,data:p3EkDpT7BfvYbVxH+nhNzjGD8HhT5m7wNPsSUqS6Ti2gTqPqL743mvUhmBWNJYH7R+5/Ew==,iv:iDLltvWfCRgsAizaqqJov8HPgvYLeVuZ7/lsAoJXZ4E=,tag:wB4A85w29K/Ba+cmbPZc8w==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:DgBTdqljkg/NHc+NKbGi2O15TNsJO8TpIOm87L0pHj9CN8hSbHIZXRx+MV7hNVgu1ZSQYem1SvLk/3rfQSYxeRpW6F/di5z10wtMcSJp04NPlvKxRaHiHg==,iv:yLNLHjcPQ541wtLOqbmXMT8eMMP5/vC/fMzPNkBvTn8=,tag:EYVnamHCeV9u6J7Jn2+RsA==,type:str]
    #ENC[AES256_GCM,data:NX1wifWoxo8nWS04WWmcniruPnGOk5oU5gl1J2TAW9CIFTfqSY4nf8/f+khZluA9qq3Zs5ap,iv:6WhwcXH2HjKtTrGVpAsxjfCRDinZaO7QyO1J74llf8A=,tag:X3IJ9aOQ/f32p7th6ATxXg==,type:comment]
    #ENC[AES256_GCM,data:F68Nc/kP6SMPkEswkxfIgEH5Kqq+ct+qQRWmKTq8bDVZsBF8n/BM9WUXwHt/fg==,iv:hNQFpPWRNaGE6LnsVJT4hIzw2URZxG+X80KibOJDk90=,tag:4/DY9KLji0dgj34UEXS1IA==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:TVFt90TWLOaAZPA7Mn0IFctBGIVk2mamN0ZZhEIdgttKpo6fAXx0nHylksTG9GF6tbU9n+3wWvS9uzg/P4NMfQKv8oMeI737DgJ1wOBwQXoNjLPGbD/OiTe8sJDvWMgHYy7vNMPrRAzfzVTjysnkBwaJDG4eOV1BjQ5vnsyp7eHcViBwtwXMAPivcho=,iv:Zw3Tf03O6c6qYXYP8p5xK1Px13jHOEAJIZ42AoYuBks=,tag:ApGCgI5BZkfTxasjHXpEuw==,type:str]
    #ENC[AES256_GCM,data:vd+zLzeCnOkbnnZ1rMS8tKkMs1os,iv:NA6tU+Pvzb5fxVBBBrhT0vsDluL1y3ro7JkDzCFYPAw=,tag:n5ME3rXvNQ9YkLyyAVUd8g==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:CDdpWIWSf8WjZGDvjxFZyU4oGp4=,iv:jeLHr43A+FX2P91PFsRmfjV4tpMnW1cl+udzzYuNMVo=,tag:mNwtQSejHJN4dpRGzex9Ng==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Er+MxSwh0vY2p5k7kmYB1RrzOGgnCnkR7223snrdHkIehCSIQjZjCg==,iv:O4IQjR8MgcrfmmMJhgqGnBysDBrK/mw3E1YZ3EFK+P0=,tag:LPibJJXVxLAy1QHGSf1S/w==,type:str]
    #ENC[AES256_GCM,data:wnjLWKIYt6Cnw2eEiVLPHtUGrjfojzbqn7Ot9zg6Dfa78QII,iv:NRs4LtWqbVxaTAhUPsYOEDHclfWW3HDU9v4XEdFq+14=,tag:zzgk8Krqk90Qb+FHrinE3Q==,type:comment]
    key: ENC[AES256_GCM,data:wj1QrqQxnQ==,iv:jsMhYt9yop/YtRv868ROzVtb/qBMpLxMSmps1c6Yqj0=,tag:myC6uPWL4J3Q5fx0QdosXQ==,type:str]
    secret: ENC[AES256_GCM,data:VO1hsM0F1BDG4y0sFM05RNKJp3vxmE1WJt4rc79vWgIOiOSflg==,iv:YFcqYg2/KApd/LFRnrWDpWn3e3HUzd+iaI6FyZykVsA=,tag:dSDs364hvc1KwLxMpwyP4g==,type:str]
data:
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:pLezaCXMCxgOShFiHxmzdNUcK4Y=,iv:1G8e61t72N3aV7JDoA8XjNpxW01+7SEvu6G3izWBbqI=,tag:AW1ci6iW031cfufzM68yTA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+tts3s1St5GAaAO1ffk3cifB3nBEbQSpm2bgiLCI+X9qAyW4L1Dc2w==,iv:Z5fUJRGhSZwdUrd+4zNs8fSwxjtpJ9A3FcV/m0/Sobg=,tag:9TPuwSXErfO0a5ux5TkBJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobXZFZk9CMUFGVWFTTFZL
            SnBLcmdOeFg0WGV1aG5jQ3gxSlFoY2x4UW0wCnpWL3NMTnI2aXhQR29yOGFING94
            bFBYeklJQnl5K1k0bmU5Rk1zb0FQa0UKLS0tIGRuS3NFdnMzZHRIWkZHcm5YaHJQ
            Wnk2aFRWeVVtQUpOaXlSSmV1Nmc4TU0KNgEJZ97GyX+HvJYZpLCyASCdvZYruNsq
            V6Un8PiweySMBeCkXZr5f6EBaGS7qKQDiFgelj6t7Zs2cZdf5T89bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T21:57:19Z"
    mac: ENC[AES256_GCM,data:p5QWKcB+o8DVNpOJCSyY4hPidC6S3EQEEKRXL1n1ggPS3HUsHDiSh2qSJ7IKf/TKCKNHb1Y694prsY1Va5pttuD3SzE+sMbK/R/iGZOecV1ZdavWrMPvZJIa7JIGeZmmof7ZCWSVs6mY2QeRElxLa9OWJoLyvWxfjWlDJOU5T04=,iv:8oaNFvcjxfNy+Ha9wnkTkYJgjFk4TMcYhbhWseA4HdU=,tag:egunTj4a1l1bk439lsYYTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
