apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    # Admin Credentials
    username: lenaxia
    password: AngelaAvery11!
    email: mike@kao.family
    # Database Configuration
    POSTGRES_DB: forgejo
    POSTGRES_USER: forgejo
    POSTGRES_PASSWORD: VOPpeVPgIm0RaHAsgbS
    # Security Keys (GENERATE THESE!)
    # Generate with: openssl rand -base64 64 | tr -d '\n'
    SECRET_KEY: 6b4ifoBgeX7KzOL6Z2/zmdMKGBJ0K2AAEsSP6Mgo3oQyZHkVc6D43mD12VW4HjjZtK3XABzrI0ic1REqyZvivw==
    # Generate with: forgejo generate secret INTERNAL_TOKEN
    # Or use: openssl rand -base64 105 | tr -d '\n'
    INTERNAL_TOKEN: Nr3s6s10aSKzhjnVRRM2rXXXOtDKM6/dxpJ/5nLyHcMtUpk0NVz4q6I81JmMdzqWCVgQuQ9uXNIx5f1yXECfXULmVoriBL1ta5Ym4n/rPad+D5jGj8OdyEdF+nuacC2Jen1pLBRoCjwx
    # MinIO/S3 Credentials
    MINIO_ACCESS_KEY_ID: soLUlUx1QnRcQnntb31G
    MINIO_SECRET_ACCESS_KEY: OK59i0KSrQP0gqipQ7upB5iJeLGpHTF5j1wXvX2N
    # OAuth Secret (from Authelia config)
    key: forgejo
    secret: 6bc15d4197adf8700b850a4694d7089b27b9070119ae46035bc1a76f289e51ea
data:
    MINIO_ACCESS_KEY_ID: soLUlUx1QnRcQnntb31G
    MINIO_SECRET_ACCESS_KEY: OK59i0KSrQP0gqipQ7upB5iJeLGpHTF5j1wXvX2N
