apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vW0A/CyHiAoPpJW0L8jQMb5B,iv:s+8s4PjHp4FBhLX3S/TlGbOwCA3ByjvhlheS/u04IUY=,tag:XmxHK7sTNtI8L6tiQTjoOg==,type:comment]
    username: ENC[AES256_GCM,data:o7ePeiP6xQ==,iv:4yTyPoPvjUglpsnw2SLv9qHTgsxTZQCC+srq5zokWYE=,tag:LGk4RvawMCpJ1vupH97uYg==,type:str]
    password: ENC[AES256_GCM,data:/DPFunBCYWQdRBo9Cpg=,iv:LlxBX+bIFS3vpXQh1IFQVdUHZJqVyoScu6kvjjjHBDk=,tag:bZQGBdj2r4wJEao6YmZ6Rg==,type:str]
    email: ENC[AES256_GCM,data:f+iv7bLd65UgZ32fSvt5,iv:Evtaeti/2yoc0DrbjiiF4MqW/9pRXKHUGg2pMJMdxn0=,tag:9906I+sNIgpzuhOvn1+Hxg==,type:str]
    #ENC[AES256_GCM,data:3+EKs1X8nHLAmsyKgKR9pFTGBZZy5wk=,iv:vYIdpAAl/IwfHQ9t4VVleOoyMk71HDqNITZEDP87ZDY=,tag:s4JzEeEtMcPNyWQVffjU9w==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:6ZHs6raUAA==,iv:LeBveyBpythaiTdEFIssvjlg6mrApRUgMOPmVw8Tlhk=,tag:Ne81e7xnukjxP455T54rBg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:bpLSUtyViQ==,iv:A/zI/HBYiWFl1AvWHYYTb2NaGaPRlvsRZ7+x9Zckags=,tag:+9vtuZnX9FbYh7plILzmzg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Glo0gPvwxnBskpNCbQIWBKdi7Q==,iv:HqBSaFSnsQGMh68NFR4W9tUy5NCS2lMOVryy/8+WMmk=,tag:a/MBUxD+4YVg2hFM2epBeQ==,type:str]
    #ENC[AES256_GCM,data:vfKsfauoQTLZM677lHITOozpQFXg/wwlBthLYA/q5N4=,iv:kmMOZApqvwT5BCU8MW4bNWOLZch+ClwPpJOuABIt1Is=,tag:wF3RG8hFLOohrzOuIcwVmA==,type:comment]
    #ENC[AES256_GCM,data:e/ET239ffWXL/yQK4qAy0SywAyOcUTVTGvTRgZqP7Jw15AuXEspA2CWV08MiJ7BF7E2ZwQ==,iv:WeLMuefz51enCvzctaNBC5UY1hejxn24x/x4egRVO5E=,tag:3eTt+GU3dt+7Qhza+AK5fA==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:qjPrLQs3KnLImoQdNMRsqJwttCMX6lgD6bB9PXfnPVeAUMomE2IucDrU9JRRSbU9HD82GqXxINOQ+5JxipDi7h7qOpziciB8lB8Qa354TtKNqPM7nHzQbw==,iv:qoG5MkSkqXQ13hXT1Z8ubGrjiaseZgAK8ppfGkatMKg=,tag:+RUXVtogJgZOdAgJOYJGTw==,type:str]
    #ENC[AES256_GCM,data:aZyeDa7kfHWHF4+l3MM/SfPwxT2wAyoPYp3Gc8UCNTV2V4qxBSDaNBp7j4yOxX36hVxgfNRh,iv:SdPfxds/kxEwJc3e8Y816U8LjZxjc/L0JGlt5v2MMqY=,tag:hUrCyzTKG9tqndsWvEcAJQ==,type:comment]
    #ENC[AES256_GCM,data:6OewWHkcJnMIw5BEsRiQjNR+CjLPIHsssnHRDlTBB77nzGQMXBuvhendwPnpMA==,iv:ACB4SxtTC0uzQBFBAFJn4D3alVAN41gaWLbYdZFjV/U=,tag:pb8pC35M9rjKRdKQajbZvg==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:OemLohNcHvm+5RV0XKOA0HHgevbntkVV4KG5AjxQrceNQ0GfnUFhbvQSjR3k81jdZGZSL8ARYq23vLP+IGe7AWS6C83MeDblOTwYS/JTniT5SbTE7FWOT1Ig/RjxE29UEM5CD4znpB0B+VfsUCCuAAGDo9Meox/T64YGvLsemIcAbhjszGbYwKXUcz8=,iv:NsXAYpDNv64+jdi+41GlVtbw2sWP4a7kuHSi/BCfRZw=,tag:SKrfN8PfeNL/B74K2VVzeA==,type:str]
    #ENC[AES256_GCM,data:hdny3WmKDAh3lwwWB29yrjPfNGs8,iv:AQ43XSDzp9Kl9cRK3vUAmDPGj1GPcB3EGVYUOgOIwxE=,tag:iyAOz7dy7IrGAT2KHdHdiQ==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:6Vlx06QkIdmp1PR0123596/FVGA=,iv:/k505yd2zHlfJ2EZS3ladu46zBf/zUeWPrrUV3gx//c=,tag:PnIq1B92Q8IjoLTiJUiWGQ==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1eLOcAtHzBx+bEr/XT0F0bC5SIRAV1Y/F5qM+T5y37tHY/+6SUn8SA==,iv:PYCdJGE+Rh8gP2/btpd+j5j6JGEwu3hBoR2411DaHXg=,tag:vcBvMIEJPIaTqGHK5wmbVQ==,type:str]
    #ENC[AES256_GCM,data:JUTpYRwHzO8lORYtvEd+gdR/S6ty/RM/L/LryqTsKduF9C7r,iv:avu7RL7BZZnDUU1onJgJOuUwjdSpUrJaRRZ/MFFSlP8=,tag:+7fwdLz2h/k/DDieyTYWNw==,type:comment]
    key: ENC[AES256_GCM,data:bbU67q9dTw==,iv:4BqCPE5xmw+Yi6YJMYCMLF41b7SxYgWjvMcGpb4f5UA=,tag:2w46A2xlygkOGSf7W8U1lw==,type:str]
    secret: ENC[AES256_GCM,data:eXNspZWyYjhJXDg5EK/ZwX1r0QuknFk3e4JaeTJCkY0ZF9IvPw==,iv:6Olu3UixilI3Jx8soUHzfyeyKCVGbg9XmxNSqng8u0g=,tag:gjNaSMJm5V22KfeDvuSjsg==,type:str]
data:
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:/X8CE/sGx+UYpSWFukGnOzAyCCc=,iv:8TAMRrJ7uTdw3DXNkJESLZT7eFZTXNLVx4VvP/0FPVw=,tag:9zL4KtogRoqSDy6kKSGwNw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OvHNNoAguULzVwZjqAvBBN/8JZCq6smvHgxicWlsgxnlxLDa3Cax5g==,iv:cfGgQ009XDEUF5BWki0wKDaZU+gnYNhOYd63WM1Qr90=,tag:2MeSue3Aozuc5tDN3WQ2kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd3FVREx0V0pvZmhCSTFa
            YkNGelNZYXIxbXN0Y0xLU0VCcmc2dDNpb1VzCk4ybkQ1ZlhhRHplV2xMemZ6WlNX
            NDdHd1hnc3JiamtjM0NiT0kwWHROdzAKLS0tIHlNQWZIdDJvVGh6cFdKSC9jdGdU
            YXZPK2tvNlBCTGIzc2tvY1ViRXVNNncKi5KdJi4STJ/ekgZPuK/z9aS5R8UedDFX
            hXozO2EeTqXzQzkdm7xHlsrNVsk67WoruPwuBvJe3CjHkkXanv0+XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:06:41Z"
    mac: ENC[AES256_GCM,data:7zDk8l0M/5i90RZ3jDBdkJNiP4YMcAOq1u+EJCsObxcD1EANcofXoM3+9cUztzzJt30CFXvaUTudD7QfNKgmdt4wuzlu4Zv3FHWJzbcw13rtwo9p0bf5lX3rXFKLH76kTVilZPBJI7Xsfdj4ZEaGb4pClrpNLeNkyKLAH0bWIYk=,iv:Ctvl9E+1FPISf5ZxEHJ3PNnMcQxocqgSkgydFW7GtuI=,tag:Awz3YL6t8qLK+GDkB3YIqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
