apiVersion: v1
kind: Secret
metadata:
    name: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:79oQ/Ees+V1FjTZUqjmDqKcpyr58eJzp256LHmcEkgwVTg==,iv:fCE+GlA4DAsDSe4TXCe3RCRx5rg3JU7bet3/SlIZSpo=,tag:1izvaOaO20QzhIcQ56eDdQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:E9S+OHErDQ==,iv:4Sk0P1+noLkrqfiyAI33wnpG9Kecqiq9jsoUo1JXns4=,tag:2DixUL2rcpVUlrULLPW90w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:E1BeC99nmypstoINVdSnn4apOl+0FTjS/Q5kqDZvhBc1PcnantlXBA==,iv:EccahLFLj450FbufSGpCBuactvRoGSMKvpR9aQXLgB8=,tag:AdF62Et9fzNCsR+UPRtqzA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:76x4jj2Vlw==,iv:+SjJj68iq5G3eKNebEYk4bszHSahVMEJlEVWgRWSHgk=,tag:X9EViu+Hv1Gc2q71jQXV4Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sjlRdZVnHiZi1lXwnTNMSFxWbyLGchh29OSomeq+xZ4NoH7mZqtcHMLXOQw=,iv:5zynvSS2wRpLgpwm1IWAZwGVHwAlE1g4qBTkA5iWzDc=,tag:bsIYC5NIas6Bx9ryV4FO1Q==,type:str]
    #ENC[AES256_GCM,data:wN1H5CXWgNkPZWtE1iiUwCBmni9udewAMmnsmKFspuic,iv:M2+47cqfNuij09iW8GSXMtKAfCylCKkYUYuBpNypkZA=,tag:vrT3zjYT7bM63a1MoutwlA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/FGavXItmaGahbRMd1g6PxIGw5I=,iv:MN3p2l2qHc2+diTJbyuCET0SbLTRD8W6UIuyj4QX/r4=,tag:NJUm7qK294dkkKNNJjQQVg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IlZMU8CvRAQa+VEGfL0YD59c6ro6ZEoFsfxC59Jwpz6Eg1JU9Iaimg==,iv:1rWe4NbwTjkLzKY9uo6m9+gIm8JVj3pH6VM3PmAsB2A=,tag:Pgg8YmCSe8Zn7Gg3NNe+Xg==,type:str]
    #ENC[AES256_GCM,data:ram+6olK1xlbqxhGaDqtE3NJb6/rvzUX,iv:xHrErBoHWMGPKHhr4ZItNcsHYehxpSDOK/k4R45ngDg=,tag:t/SGfpmB/IDalk1E26C+sQ==,type:comment]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:yN0qRycPoagv4HDi+Vb5gnRy2XAKhtDYfYoYqRn4WTnRFRigRg3ud7YjOBA=,iv:EHEfFjb9zb6N74STOwRfIFXNXbBQI7LlZC2+BXL5DNw=,tag:fibmKVKZwQqfMXscsyKKeg==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:P5TzaxtisoF1IqYGkCeXuYsdXfKIYG7mOHEIhI8LPekhWK7p6pfbc54HeWc=,iv:jTwJQ6fzSd+K4VfepI9/gokd6wQGktP/kfCmehJQ9b4=,tag:Mhv9UQy+lRMwFPDgLIsDxA==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:3AupC7bKnLz5hXz8pvsvaM28tl5RG5LORNMDwDOXofUW00PDmZdSoasqtx8=,iv:yI6ogOg8i03DK+7oJWAiUDWpoSf79LZcTj8N74cVPG4=,tag:qBv+bylRS4l8NxmYP8RtzQ==,type:str]
    #ENC[AES256_GCM,data:DTucj0PUQJG5zOBsVqvUA1h9N0DxwlGfnTaxq/4Dp1sMRAGaxOys6DXxMJ3y11+C7dWFnV/A9l2MlRhG,iv:ej8QrWTYKdxEpvXh7rvqvz5Y8Z3HUjNT2BLngRmb4mA=,tag:Sxawa9s7SWxHhBSOej9m+A==,type:comment]
    key: ENC[AES256_GCM,data:UCLxAbinhg==,iv:980Oc8C/bKG0y9BtokrAYqVm4UC49+99jOYaq9IiDfE=,tag:nTxBPsKW2sGOr1KncClTsg==,type:str]
    secret: ENC[AES256_GCM,data:lIZGCGztfTWTpVbaxLCjGCjPZjZ5TmrekDJHJ2jMt7XYypSubj+dXbm6+7+4hn2+1LOsdNR/QWo4axe+QtYo1Q==,iv:SfKBSPX3TSGBNyRtYL+QiGySuTRtCON681y8PpTqfFk=,tag:LprdWYHsJiSIGEYTR1e+lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNVpyOWRLUUVJSmtBcDFU
            VnRhL2VFeEZHbU1DZC9mOFZGNFh5bHk0enpzCjJ2aFZPa0RrMmYwSzlrSlN3MGlq
            dW9LV01WTWlFcGlNYkVwVUtjVzRlVUEKLS0tIGkvWjJVTngyUm9zdEtLN3BFY3Uw
            UVdYZ1NrSFNGb3FlTU5nK29hL3JWcmcKHErx+Fyvefuf8zrvYHgMbFacQsUd7NFY
            rpEkYkl4g8o3Cl1wkCMcZkY1PBbGQ+n7Tpnqto/kVi1Xra1H8plYKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:30:23Z"
    mac: ENC[AES256_GCM,data:qQL4bNi9Z517CCSeQIH0eFjBsEcC98QWgMIBCoo/GokQ3mGiKHvNyDQr2u7AXXjpWM6Z5Jv6f6fPg84FR1PYihnDmY4UY+t5OCivIYP53vemlOtorzXWe/+T3Lgv4qrFJCxUzC5xOx4vsshw8zjp4pv7VPlkZS2fzUekb0taXLk=,iv:d8ucSLjw76igwxWuH8591kIa9jEE6w+z469gd0ldrvc=,tag:IIUuDgAVwkC70w6zKzbieQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rrvgEjq8FwH3MNT7/2kc0NUPxMDZp6c=,iv:Z52b5o1tyfGe8v09693QiuKQ60Yy48LVhDL7lrZBu9U=,tag:7VxlkkORphWGQ1LAdGJJvw==,type:comment]
    username: ENC[AES256_GCM,data:aTvf/WI=,iv:NzE09ohCv/Jgy++1ND9inTaGaVOg44JPDl3Du60b2hw=,tag:4LYL/uBOMtKfdcZKedQI0A==,type:str]
    password: ENC[AES256_GCM,data:3BDEDMOTEv25aQ==,iv:OCDNPDi0sEwv8tSxrPB6pSM/jPAut7SEcNPgLHZpNtg=,tag:BdcJndy8G1PzScoBBUPpBg==,type:str]
    email: ENC[AES256_GCM,data:KYNBfZDM/SCdmsOUJt9oowu2bJkVvzQA0jI=,iv:lkhAhNdEDB6P/FgZJLb1yoHJTlGchXgW6eaD3wLE7Vs=,tag:qcg60Ul/HYXLRwUBRHI+9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNVpyOWRLUUVJSmtBcDFU
            VnRhL2VFeEZHbU1DZC9mOFZGNFh5bHk0enpzCjJ2aFZPa0RrMmYwSzlrSlN3MGlq
            dW9LV01WTWlFcGlNYkVwVUtjVzRlVUEKLS0tIGkvWjJVTngyUm9zdEtLN3BFY3Uw
            UVdYZ1NrSFNGb3FlTU5nK29hL3JWcmcKHErx+Fyvefuf8zrvYHgMbFacQsUd7NFY
            rpEkYkl4g8o3Cl1wkCMcZkY1PBbGQ+n7Tpnqto/kVi1Xra1H8plYKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:30:23Z"
    mac: ENC[AES256_GCM,data:qQL4bNi9Z517CCSeQIH0eFjBsEcC98QWgMIBCoo/GokQ3mGiKHvNyDQr2u7AXXjpWM6Z5Jv6f6fPg84FR1PYihnDmY4UY+t5OCivIYP53vemlOtorzXWe/+T3Lgv4qrFJCxUzC5xOx4vsshw8zjp4pv7VPlkZS2fzUekb0taXLk=,iv:d8ucSLjw76igwxWuH8591kIa9jEE6w+z469gd0ldrvc=,tag:IIUuDgAVwkC70w6zKzbieQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
