apiVersion: v1
kind: Secret
metadata:
    name: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CgCBLvf/0OPNDdtZaueqrX7cXrwR46tUhZgHX7rSjtsONA==,iv:UlafKEv2KgKwsv3513Q7n0kRtvnUDLnzdC08wHb0ttM=,tag:n5/fqBVul2a1O/EREELLKQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:rVlFAYSd9w==,iv:rYZKE3PJFvS93OHZI/+PVZ5sXZ6/F8da6oO1gzTqLQw=,tag:JhrrhM9cVZCMMwV3pL1CCQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8L2yf45I+VJVByl0BnLANHedrm2oSM8uNmMc9dmj8lhctcO8DM0=,iv:4a+s8G6xMRr8gZ83BFIoQfP/LuyrQTT3FkwNZqhXvY8=,tag:QmWgy81CnQi9fnCbDLMXVw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:1fwmRoXGwQ==,iv:bhhbaA3lpkBSWKLwRQ2xAj6f1ViZB9+LygVq/8yl3D4=,tag:7TFi+t7ge1SR8+N2cerGsw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8hFHhj9l1w5efLrWpbyxGFtHsDzrkgjpi8sB8e2tZeiq3WrCSTskt7mt7RY=,iv:d0BUk8pxWz0+t6aCrZw0idZZPnkqjxjHoQ2ru/Ueq70=,tag:A6KcESm/MX9FCFRQpglC1Q==,type:str]
    #ENC[AES256_GCM,data:WtOL34Ej2qIvcPWfS2tFQHkBsILmwMIvG1tVeZ5fLxWF,iv:4Vb2X03qGS7uDZHbhmzR6y60Gq6dzBodKn9NAhBf8GY=,tag:GUt9jgfsUNTX1qUc0rKHUQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lkRYK0xmmlVbMA9M+1tAPXzDAhU=,iv:Qbek82uvqvuQDb54vsSc0jdop8rnWFFGsr/zf+6xsDA=,tag:nA4TsSwqaT/z+9IA77jvIg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D0a1yFEy01dWTTJ+krc0+oY0uzYjRTO9zb0fyqvKJpOzFJ9bcfbmCA==,iv:6vQGqZTqjOACeVWTeyaM11mbggE7lMR5HSd31ZUU0FE=,tag:mmu2kwq0q9GpvIVWWs8Crw==,type:str]
    #ENC[AES256_GCM,data:zuSehOOpvDOx94WAe0X85UlgbUbYxzJALgRWuKCmuQ==,iv:IDtBn26bRfvOUymdd61RPHzuNzS8cAe9BmT984lM8ww=,tag:zQbqUKC64Q4fNkUdM6bcxg==,type:comment]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:1a1VhuZ9hHvs4X5yeUMUDlSTHcsnaT6Tv8eyV5CVTRORvwOYtp3skYIxQrw=,iv:cU87kUrBQPNfpxMBCDooW+pMMXSSSN3duChMw7J2qp0=,tag:+qpxlRSjIXUh/UM7vs+Zlw==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:IhFSfFI23UWptjEd5VzQKdBH3+3Wos/KbMFy+xPFBq6k2j0sBYXZ10tSHys=,iv:GTZ5CpyMOfwBiwr9jZa1vqiCOcwnyN/9rJinZ9RFXOc=,tag:NfNVU10U1rytI4Wke5PUgg==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:0bmkKcw4LySwK9dlpwhMqs+9eRE2nCn7HikglGz7tHbeGUkdic8vRqFwfH8=,iv:uZL+SyKmnFBWzVHbU8J/wl6RBZ7HgE7vv0IbTML7Kwg=,tag:vtE+Ur/kWG1hJLzK/0O+Uw==,type:str]
    #ENC[AES256_GCM,data:e7hO2RJAwh6xcx29HnhKeskfnY2LT2MP0IsuD1zg6XrM1Gbae7nIoo729WVhHMbB1KJYLdQzfPnk,iv:ruWLfw/lTqUS0TeSw34PKUmBnDLmJNIYcUnMFnDKWb4=,tag:HL/yY2HHVCjxrV/E91tDKQ==,type:comment]
    FORGEJO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MhSWzGPNIELCe0MKg0Ip9Qad0xM1iqwZPmHBAPnWMSfwzgs8ig==,iv:1aPzsWSNJ1MctiW90jMKculcdmyCAw0AYW6nvZqlwrc=,tag:dT1TtRMtxDcrbPo3axu4kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nm1xVUdFcExnOEgzUXp2
            c2FpdytTYlFUdzdBM3UzbmFpQWNsTjFGSEdRCjl2Rk0wa0ZQTFdXdnR0YitNZFhC
            bGo0VlBOUEZnK0g4SWNLRE1VZDJJKzAKLS0tIFZnNnYzVkwwY0FPT2VEQm1NQkJp
            Z0NzalJkMmVySHdhcjJCNWFHL0FJUFkKirS5LAxB9IUIJLPGkrEL6PuoOpo/YXR1
            V4egHXLkHXkZZFldDPEeiJUL7jEqxytuXbkBGHuGpNxPTg70J9AgJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T07:06:37Z"
    mac: ENC[AES256_GCM,data:czhlKOOIXyqYckNHCtEU/Wiw2aftVuPWOoOjs+/h2tuLzA4Fzma9ZRw/Y7DM5mHBGa04UpCmoEl1tFJF/WQRV4Mz0ImUbea2ZlhqfyTsp8kFshimbbHM+Gke70J+OvM3nY62IPCt/2eCKygW+fkH+e7hJy2p1q6GtmhkVx+GkSw=,iv:5auJrfbYZQOKrPCxaQ95ZPP5zXF1h1r1+HptOWnaK80=,tag:/4sInhSv2+iYt2lHgdw1jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
