apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lkfLoYaDQStNpOXgDRvpf8rC,iv:+6cGcTGhKEnIHXbHAflpK9KUgyGwGXfdRBmrdgFBwqE=,tag:BBBPJrwZsZm7LRSjhXy1EA==,type:comment]
    username: ENC[AES256_GCM,data:cwxV/D0NFg==,iv:l1X0c3x3L0kxdzYnhe3G2sq3mTdqV/atlUc3tpLLlqo=,tag:F7PXo/4VxzTHDYJtrNMzqw==,type:str]
    password: ENC[AES256_GCM,data:bxeWBtndq6gf/FtEp3s=,iv:wQXyvqCGUAgxVyiW9SQ/PLA/5ds9tAHixNP6xHJcXYc=,tag:f5TZCQTBre4XSNhoP15fFg==,type:str]
    email: ENC[AES256_GCM,data:7/O0yBu3JTd3KGTPju7p,iv:qyK3Q6nxqY/n4QzlLp2tBY5nF+tuOq9aPzO+Khm0BbM=,tag:TFZdKJjjqMoGHxUA8jObIA==,type:str]
    #ENC[AES256_GCM,data:rd6ZW5dxruvO0J1HwBu5mhso2JpyT2s=,iv:Pi0Bt3DJH1QS5t38qQG6FzXY4frwexy7Y2WypMA4K+Q=,tag:QuXTWhkXDd3ew6Sywwle4w==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:sNOD2pfTiQ==,iv:1fMTKsWhOJrnM3VWYErE5bwFpCJmDFdseO8CV+IaBHY=,tag:uwfCNP+xCL1RkYf3+eFX+w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:swrUny1RGw==,iv:4eU4sVjooQpIGZU8beNK07tyK/i3QeNAHhO64emPOL4=,tag:2HIkjYF26LWZD/xhKmu8RQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IQd2g6yYvexiE4VrbUHbZtAImw==,iv:uVzFhtjEy4aoDXPDPvOq3nymIa4VO1VRWWib05xhwI0=,tag:yGxTFMhfEXQ7dxMXLQk7XQ==,type:str]
    #ENC[AES256_GCM,data:fsC+QSc2iHvjPD7rwn5gV1AJ0etgeyrfyyxV6Lv5fFo=,iv:O8Y6NZw7/uFGQlrt62apFjrZ1FmEnCH6p9955MlaNHA=,tag:RFDf8w0qzpH7nqP6rsm62A==,type:comment]
    #ENC[AES256_GCM,data:FmA2eOkXLFR8M4HQZWvlbgQgAYIBLl5BgyzTd8ljX4sPSQYVor+e+ZsHCuacjBVo0In70Q==,iv:p9R+hMqbrQRc7zQsoWRI+aG0Rm4hjqmbNA6s7JIWFI4=,tag:Z8R+Y5/7yD3JXVkBv/gVKQ==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:rwlfMQwRm8Z0sbQdHM3BiC9boUFWG1Ra4PHk5cgpEy6GAw5wB1Hmtc26wzgFUc7zF4Dpe/+xGV6RfPn3wyLp0u884XSdx54lJxYdOWYK4eGNo96KZ/Ci0w==,iv:aBe8jfbUhEZ1IdebO0xql7C0Hk++9JlCK5Rx49S5nik=,tag:mqIO8UQAfIUtLqMSiegd6g==,type:str]
    #ENC[AES256_GCM,data:gPXRoZcTjTtEx67Ufh9k4KiJ4kK3NjEkOAwerKkIfsR8GbfPLaLupjM54tE7s2ZZi/bi/0hC,iv:2FILP2EXWuu1ueYO1hzJHAG3WdGoD1eKj90rnW4BiaA=,tag:J5y9FdW2Ab7oNHyorsFgLg==,type:comment]
    #ENC[AES256_GCM,data:UOhgUFWfXMbxJ2ZY+5kgdK922DOq1FhHVt4iyTr9Z0yo0efW2cLzBJL0Br6nAA==,iv:5XXs6PM0wHKLJsXlrK37rr/GXXk0MrDJiYjKnYkVfsA=,tag:xH2/wpjSwVULEHEHsLsWJg==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:R3BK19W3IC1aJk44SN5iQRD9i3NcwVcc5AAlzKktQwQ/AxhwctaGV6T9SMArgna6wzvAyb94t2vqKc7Epj4WxKAN0BZ9eygqyZVMrdm87q9IQD48TmhiGFxsGmL1viqh705OuwNoAG1Cj+Y0UqRBeqFKpxjXqxoRmnPyIXYzVfJZBnDwSiwSOtoR8K4=,iv:ziou02H/7CYGn50N3MpxrI4zpx6Am+WozVCtRqREuQo=,tag:bsT+wBnXhfO0CpIY/d37cQ==,type:str]
    #ENC[AES256_GCM,data:rpM4o6xogTsuLbR9w38ZBUzFR34t,iv:0aQvZNfFgZSRefLeW38xzGJdq1AEb1fAxgK/zcjC7GI=,tag:FD28+MEUkRxTA/bmPUEeSQ==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:jmtUrkGBzlfaneDOsMh60rEQcQs=,iv:TgJnQ10wR4SlHyhWSHe70tik1JrbLPFadc+fDXeHghE=,tag:SAjfJgObiq1dekI1EUj8iQ==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:37nl9D+GfLvCJES1CcoPj17qIvrXWLQXMGO3x1GUDYlf1z9PU53R8A==,iv:FXmBnji1OBpwknsGO+PEgamdPnHR1lS+3AghrUfgnGk=,tag:NHldiDI9D2ad9+98iKKtgQ==,type:str]
    #ENC[AES256_GCM,data:IlYaCMg2O3NraVcE2b58upcl2y6z1eMaVNuVCb/B0S/cqWFT,iv:j6fuLjgrENyfr+BTOjtWvC3BE+9j3XGCXVmPAQwHWAc=,tag:bT03eB3DzNPHnPlCIEY1lQ==,type:comment]
    key: ENC[AES256_GCM,data:SV+HLR0xyg==,iv:cBuj4VNffndBO3z/U3/F1qEs+uZjnFURSGp4I7+g/xc=,tag:My39ixybv0YQ6/GJr02qFw==,type:str]
    secret: ENC[AES256_GCM,data:QGybP19lXPbpNCLECtzf//BTEOy9pRvIEGPbPmGJ3ynMmq0NhY4uWKexeVsBtSOt7QI2LAOEJV789AiIUQ5eig==,iv:V8C6tenRFDgCwIoIyblhgzt7rbRllJ9P7LwiGmiqx/E=,tag:wvbSaGJ4wjDpjc6Xt3OhLg==,type:str]
data:
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:WZuwlNTAXkRV8P2cfNcSvO8sOFo=,iv:xE93jsmaqvWlz/gb6Otyfa/GaFXixPXgaD0LrqiWGvk=,tag:Bm5GDiOIyGzWJZK9Oj7ysw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kpd2/AAx+jARwCIM5Ipl1vsYdaZYlR55GLyJGfts4gGvp7OaNwqeNg==,iv:Z65oj7ITtOYDBt/LRzOr34SXRYE34olC7UxhfCWotNU=,tag:ELAnEvfsROy8eZ8F0lmonA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdFVwV1cvK0tzWlJLSHE1
            eDBJUTRQZGxOdytlS1NxejJFbEVXNFJTTFF3CjdKVHFONXJvV2FjSHZYelc5bWRX
            UGxhMjF1aUJkdjc2MDRsRml5K2pJcncKLS0tIEVZZi8yY2dKK2xqU3NPQ0VGUWlS
            VHBJdnovTXEyeUFYQ3Y0aDBPT3lmUk0K7gOE2tAGOubR7rWhTeQCnkjVma/Abxtv
            Lw49tSrI51IlPrfQo0Eln8TIH0DLATWLPSgx7BWm7gsIG2FVyCn/+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:42:34Z"
    mac: ENC[AES256_GCM,data:xkAFL+aznvi49G27JZgILwY5wb5w/tBibnzRmS5hKhQ2xlfI6mnMSyeRpLgPo827xupPxCOOeMa8QkTHMmrLq/468QtTUgGQFaa/FkvZzQXZeNbkdZTIdFp0Ss/7uGWFrrW3Z2kT0CseMwvPUYZYEfvEw69XMcCI9EMRkuYgfZU=,iv:fwtPeLzqt94EBnJztnMF1AqKMQJJcSZBAA2u/MNxE1I=,tag:zgDhsIqkS1tIIaJmCkyZOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
