apiVersion: v1
kind: Secret
metadata:
    name: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JSQRoIIortZn4Z+baHya8FAa7kNKc7N96/aMQexbDP5+Vw==,iv:W5pjaUsP/O2C4uR1fL2RoHHnBg8Y4Oi+zb60b8UF9mQ=,tag:m6kouLD4rtggNDUKClt82Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FQquNp0gow==,iv:BBy+4YhnH7XvhykQ+a0VdGOBx2MccqDUiNVFYiRM7H4=,tag:zi75WLaLmx/ZyxiF07fAyA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ptVbaF/0+uHUwdr8IJLw+yaLr7eysVRFPjwwPsT1C4dNl0r9PBsSgA==,iv:B9RvLSDVIbRaHkJdIm9xtxwMII39KPUTKVwYvOIO1k8=,tag:rkiidi8kcIq34T2XTEaehg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:PbYeaTREuw==,iv:QY9OFo3mi0v3DfeFtFEXf0qsN2LHYjc5TlOWd8/zL0Q=,tag:eq4NfdGY/ow5r3uhc2wN4g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qIQyErRSH3M9nTcsZKsRnBSbnilItogv3l+2xSvGiz7sqLzptcYgbz3rsDs=,iv:vmTRGTuX3u6Ag71Ul+2Dw2uPbKF0ylBEKk6ehmqixr4=,tag:tmY0d7Aeok1paSKWgE3yKg==,type:str]
    #ENC[AES256_GCM,data:l+FyEJVf4gM36JVQ0IPtZeqaLtmVfiCQ0tFntv7BEZXH,iv:wKqC4B563TZfxoBNqVRzvW+ctrKNR3ID1SrCST/6u/g=,tag:BSVFve17fNM5L+IFXVfghQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7Y2tuGvC+syebxke9BlT8x97KKs=,iv:1UicrD0FUCXMm0vIwfo2+JsdxEV91wPhPSvfuac22lw=,tag:k6QDeVOHuQ9mL+DbImo4fg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:l8BWOzVmfm9PSjPBcJ0SdTodl2H0Cs5voWU4SeExJB33otlQsQlbng==,iv:z+J8QLThcGvxXla0xNGVdRamOVHcw+r2rsmW5iczEHc=,tag:HUDewmMynEL63qha+/VwUw==,type:str]
    #ENC[AES256_GCM,data:3hwpuJCs+fE8U074tlWLckhnSy9JNCMNEDNBLkCcnQ==,iv:ZTp8iD9hgnrcdj8qzjijl5YbSgpFcTgkpu/gz1mUkM0=,tag:8ZlYS4C14bMe6ZhGFMJlXw==,type:comment]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:1mAerR09cto5heVax7zz/hEmDXyMkrh2yvnQ8pSbtu0rXLhg+DPLENwZgUI=,iv:+q0zaOx+Dj5QOX1sj1c5LdYyxHsNSmQSKOBwGMYY3vU=,tag:cQKXzynurC6riWcLeYrV3w==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:ZateFVNJ0J/oD4W5P4RRoLGtK3ZC7il2JZJUGibSPNCoALGQciQcZA8ao7k=,iv:R4jEGRSs3VVAnNC1GVWNXrCG1CH/ElRecmAR9SCUraA=,tag:evuRogOLap4vNCEmyemeDg==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:0bn0oYQz1/Q11TpMKv0qKiylE+e3ulDzKP3TLp/wA9Ibd5+Rg72yQFzunKA=,iv:BPE12apwK1ZlgD50W52csvFTMqjp6nKJB7JJpfTk8so=,tag:ihzS2PC/M2OnncxUmhe87g==,type:str]
    #ENC[AES256_GCM,data:sxj9XiRe5H3+/kTdtokimQydYX/gb7dOfUwuVJrMPSXOk/kQp+LKFa/G67HapwDHLGHIU4oGml1+,iv:jWk82HpNp1yAU/7YjiobTF8KzQs0b1VmVPwKf57eTjQ=,tag:Y+XR0gOWlpMim+4e+MSsEQ==,type:comment]
    FORGEJO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:H7QVbdbnuWhe+4OXh82jB2Um3mlfTmKxWAuTDJQchr3qslTy/Q==,iv:wMB0JkNvixEdkz+jVWlNFYKA7s8Wqmb5F+MvS81GoMA=,tag:rv/wwdQPj66p8KStqlZwWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MkIydGpwWURUS3ljN2gx
            Ym9IRWd2NHFuUWQ5QlZPQXVqTkR0K1VyRDFvCktIOExjZEtHdG1TaDJtcHpKME02
            MU01b3RqSllsQUJGcWhkbGl5QWJsakEKLS0tIE5TNGxXMVZzcHdSWDA5QnhMQnBy
            em1LQy85MDRMMzFzZmVvcUZ6cGY4NmsKm8HI4M+CaGdEtb23sW9uYtWGaihlVpey
            tyIiSGCI6ZwcQNDoEN+6wh0z20eyUre6Sf97g8gpQN5l6Bl8C+Z+gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T07:41:10Z"
    mac: ENC[AES256_GCM,data:OF8htgY501jKVXJ5llO1QAAx0cmsbNf2G0MFri/Raj5+jYiJlp/FZmQKLhFNLTdDse6YiS4i4gy2FFdfoOWTWynklNGZ5S0E9yzJovP+SVOtdsokRlE18pNw4EQuwAn8JzPP4YI0WrdTaauGJKZNltthUysPMCmXnCPnpOEW55U=,iv:8wadJMrFy9hm1BAJpW0F4028UuIAyl3jvaOqH6L9fGs=,tag:y7N5RuuqJ1MQE1h+gStTvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
