apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CKvuyetvwuAEP18PrpFEvTkg,iv:iZdsdTYpC6RTOKIXMZxUralFa2Nhxq11WKov6TFQLFM=,tag:LVbkqSSDr9TXaiGHPdZccw==,type:comment]
    username: ENC[AES256_GCM,data:qscXP4y1mg==,iv:bCgLAwOYQwWYoX9DrmOSeW191l6gvc1RRLaGVVBn4hc=,tag:lLcrWcdAlsniGnUgiDp1Vg==,type:str]
    password: ENC[AES256_GCM,data:6cGbmBbwbBWl2Q==,iv:XwQSV3aMdg3u2jFL2zcPdYaEFN4Q05avkiNOND1Sw8A=,tag:peIWQlme21oTzJIK/NDd/A==,type:str]
    email: ENC[AES256_GCM,data:NHLBFc7aZAr+GXBZLWMy,iv:0kKgZgDOSBJJM6Ux3nK1pnbi8ZEabMFSBu4QkUbDCNs=,tag:nblycnKYP3sKJyL3HYvsRA==,type:str]
    #ENC[AES256_GCM,data:xaKpJVneBfveNPUdMC8S7VgV4nKZffc=,iv:Vp3ULg3Dujz0cQoY/d9KyU03F8ngjK3PvW8a2pd2qUI=,tag:NR+rsFBtaNXickZ2zOiM/g==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:eW8/Fhd2bQ==,iv:pgEAU2gBKk4mPF2JWdx10pnObEA17fEKIesrORRjeuY=,tag:+w6gEMyp3+14IoYA7TA+6A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+TaAbJMWWQ==,iv:ca/w/KOdJFAtcy6V0HsYnNKWP5GYAUtUXu+7W05t0xo=,tag:Y7Qs9OAkqLKs+dMpOhpAHg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tJ4ZgvWnGauuKml0ougxPwv6lA==,iv:Pm/81gZTqkRms9hl6M5cNjQ0sviMUQX2DaiNZ2NBQPg=,tag:3kaqUl+bhpam56rKKLM3FQ==,type:str]
    #ENC[AES256_GCM,data:sfVjsAUrNG3+27DPFacAQ6IBMQXewU1VoGDn09oQ4Mo=,iv:z0M+38a6mn204mqI+SinWWTNutXucrMmRg+Tdzy3Kzo=,tag:Aan/U5bvO96Zs4wQdI/ALA==,type:comment]
    #ENC[AES256_GCM,data:VT69L3uzvM6Ol0yPEnJs/T2RE61Er8tIGTSx2FXk4S14+AJ51Hjs6aASG3znCKgX81x2Lg==,iv:Acrd7OHtreu5GaefAZI/uY8NoTkpreUdUBSRvPKn3oI=,tag:DMSJSPQC5a4YVACMUAQUZQ==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:QAldCBx4Hj2eMq1DI6Hn7GQgj7AkHtrECvE4w4ZlPzfb7LTKxpVT95QVRQH/HCzDt2x3e+Zo5IjmizP/GBZ+6jiptXo92PVtwIrv5hPaB9aPcJ1plxNmaA==,iv:RIJIlFPNTJTY69EXC9HhgiWEhIKht4irS+E25VlziaI=,tag:lZzbw/2MbRhI0y3xHXBEhQ==,type:str]
    #ENC[AES256_GCM,data:hCLuyZ5osJVAgqf+TAlwgPltf0F5QFlQkh4Df/UIEdf3MGIbB5nJQUAgwR34+QJo/1gRmodm,iv:GZK/vhxV3SwbKV733OyZiw89UM2BEnk6fqQWAft4qKc=,tag:D3JlsA8lH9eMaU5qZmmNLw==,type:comment]
    #ENC[AES256_GCM,data:b4w2X3r3WFBlMeYt3qVx5plEOO0Ca+vymTDP5jW+AIYQmTyKvvk+nFM4pU34yw==,iv:7tvH6W3PpjflvxFIO5rhemXnVqxui07zvFXB4pf59+0=,tag:kWaeNill9SYVHrCVTQkFLA==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:9PHmiIbdwe4Omm3eDKbExbNK7ljmjDeOK8W3UweMOkuL8hASIaLQHBIAyxLUdhUn0gAlf3OPrQFTTIBBBWMWVXQgfb7A3YOeRgHe8bD6zFePxcDBH8pjDofRqvPXSzil+6rNtEzY/i99a1Ue8Uw87LFThJ0OKrHenPuDU7EyYPx7DQh/9EaGfhGtIvc=,iv:pJ1aZlMl9nlDi3iP2J6eKkiET6FDb/nk5KNYKQuY2O0=,tag:HxKLG/Tpx97Dc6iuhmgkWw==,type:str]
    #ENC[AES256_GCM,data:sQfPS5YE3H2idq0zI5/fFd1LVF52,iv:iiMSqJKVqqs3Uut9jYX4dhouSSyyEzZB2/a63lNaAM8=,tag:p/DJ5xVUDkCXN/0C1kd/aA==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:celZsh+Cr/U8nDV9NOAbjFBXck8=,iv:V347ke+8VIJSl4emM7xfOcnuBVzhElsaq9b6VzbQwVk=,tag:rVHZWsmKnyPat1yFJpTSiw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eBrx1utlSJPSioKY3JTW6D0Rn+e28lzdSkW1jbj4Er4bh61nECDsgg==,iv:ziYnOmfcTFRAIVQs6BurWjspogoqnfwmavbVB79ArnE=,tag:TA1vsMNmFt9U7tlEPzL63Q==,type:str]
    #ENC[AES256_GCM,data:87Qdx5MUds1+yJO/+Q3rjSptMc/otqCP5QGFVb+CVJnGzSq2,iv:cijzOqXeQYWa258m9ERbsCQq7qg8CGDJ/5qM8tBiD+Q=,tag:LJ4B8XezoJc+Ilk03W2uUA==,type:comment]
    key: ENC[AES256_GCM,data:651lV2IfJQ==,iv:CDDBxzhCsF4p68TrWzVzw88tkzgA9rYfMXBzURrjb9U=,tag:SbWBzXWGXgqrkohdO/etGQ==,type:str]
    secret: ENC[AES256_GCM,data:eOBPGryOR/L4MJKwIGqsh+rqYhnN8mH2HjknipqSGZbkUxidAA==,iv:PmXPV4ugg9uTJQFfsN+ULDvqOKK4hra6EXCQ/4iDN9I=,tag:kAEP7e1Hkco48YkAF2wDKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WXJuVVdOREpPZFZBOHdq
            cVQ4RmZkMzFJcGo2MWlVT0VXeDVlaStNWFRvCjFVKzAvbldTeTQ5dUpOVmF2Uk5a
            SHZ1ZjJ5RDl6amhKSW1NT1NMS2sxbjAKLS0tIGZNcEZySjVIcWZ1OWhLTHgxLzBm
            YUlmS1RCTWtudzVsWHM2azJVRmJDOGsK9h11YJJR2VGaIO/N+u7dtgmPc7WVP8Nz
            K4WaPCDIu25J/r36bbUlZy8H2HV+CvbcRcIpQFk3nzTd+J/Bn2PV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:57:16Z"
    mac: ENC[AES256_GCM,data:uTAdXgVc3TW5SAbSKi7NumtGqPY15zNWdssuoLxDuzQj/KgnZmyAgkEFHbFuNWYnEaCyoRbdgnFrMJfDa+mpjHHiDjWmHoc4DE7JflNoCsxXfAc0UgivJY5CIB1rFwbJAPVWNIo6UaWrMLmuswY+YauqFHvaB91F2IU4kHUlXuU=,iv:YQh2CVoEQYvr0sJnm0uCoMgPHxo3N68cLMueY2vR9oE=,tag:+JoyHBATSwVglJ+I7iqaLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
