apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:sgk9sFUmnuX43TNVvZDXfIl3,iv:psUEAE9JhPRG0glJ/ujcavrdJr1gPwSZEk6Al3jyGEs=,tag:Etshf8zilpXgHJuJPxHDsQ==,type:comment]
    username: ENC[AES256_GCM,data:Ew/lKcCK1g==,iv:Zdy4Qss4/Prz5UUun15tstoLRQe9nApeX64X9huiZHc=,tag:uXK7Mic78nx354a7yJKSMQ==,type:str]
    password: ENC[AES256_GCM,data:ZhOVNeE3W1MLu3Ehf6A=,iv:pVOp2wGTlK6tUE64dQUWvf0rC7/Hd+HqVU25pVzCxVw=,tag:Fcz8Y8hPrUTRakn627Tk9Q==,type:str]
    email: ENC[AES256_GCM,data:BwYuP5ihVTYzUd/i1x8e,iv:8OWzMOR5VSRS05olUZzhuKnok2uqpSlyCmLj6dKjBXM=,tag:gWXTj5QRm1uEeAcQEMQZeg==,type:str]
    #ENC[AES256_GCM,data:ZwfFtyGGX6OloElMTxCd8my/n4c+D98=,iv:DpOoT/G9HHbyixDnrRptouC/ChMrSJ9TIIu/HJvh2NM=,tag:NSxdg5WTsQoy3G2Pufb2Lg==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:xzX/NJZ/FA==,iv:QtWifIV4mxdtnSsUdZTLxhPfmpmcf9XyTfZbcgRIotk=,tag:B/E7xX0sGoNmrG96H1gl0Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rGEIWX7HRA==,iv:n995Smu5RQdvjV3VB9URIWWlUtZziHNy1tWQSOQpoBk=,tag:zeIcJYIdbGy/gHSac6/I1w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Y9jhc+F59h2PB9HhZsUdLR+u0w==,iv:8ZWWzf0eEJyfAfwQvhy63oCpRPu2cbhtb9/coNQuRi0=,tag:roPaB1qdXxuf1s7HTEX7bA==,type:str]
    #ENC[AES256_GCM,data:B5VlKEWuPl6dZAn8Cd9HbcBEnL+SGxynFVf8ChPWcHM=,iv:nHs2kd4q4Ff8q5o8TjP3I8lr3NbPU3TG7z04UirqAzQ=,tag:XSFLKrCNfXojRdsnFM8/Tg==,type:comment]
    #ENC[AES256_GCM,data:Du75EQrRm0obHDOKki9yvt27jZtWsCNTbMC745pvzmYBxcxS/VBZbFV/+Ty9EObMDpxGCg==,iv:A7oC+9upMxNcIVQgnt9h2MPe0/VgjLMvHVOTO/eL+ZE=,tag:TsXPjkFZadageM0DyLBhgw==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:+HVtRnE2dWpa/zp6QlfW3HdvvYoRr0TAlA6GAVbpLv44lf+1b5T232aVLjurNFknHnBEOB3Z2V9Ju3WfvrOQ9It3CMPA1CZAty8tD/Kpaz8JQT8Qo1uJaA==,iv:6RVWoQyR7f0IXdfIZ9qMYgAg+J5W03mPHyWIThi7Qyo=,tag:Y1GMtbA/qvzHibRHoFzZIw==,type:str]
    #ENC[AES256_GCM,data:ofprDpP0I8TheQnKdeAYri8E9PtCJB5KPabH/pahoJ8YK9w8qkAqUKbe35fVT8FAWzj5zua2,iv:JksKF6SQk5nbvj4pQKRU0zP1QK59bYRQGxZBHm3Oxtw=,tag:dlDxToAxflhGqMmeb5ugCA==,type:comment]
    #ENC[AES256_GCM,data:r/tGHttzBzYQT6Xxg0AiGwGcDiYluo5kepAhXcp6DsevN3TAY9hDS7P+k0xr/Q==,iv:oM3UpFW/rLKwD4YNYLwUIfQnwt2U9Q033lkOvg8Z7mM=,tag:zqMvzDNaxZDevwMfyqcMfQ==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:CJh/jT08g7LX2D3pidg8uddibghPhuKff7sGlBbgVoUZG9jY67lBFhp5CY5n4FeE6TjVpJ7Uzpt6FShuzT41+wEdotmcRpNNOf/PsVZV1tMxYhm7uhzNo1F16uZQdBaFYse9wtraQWDZFuTepFKpglHJikCn8nsmJIAQ3E2iQp+OgPV+vnlP9vkqY1E=,iv:esia+Qo/JuYAvjgh1prCSehNjq5hlccaoEaX+U2/a04=,tag:g8izFFuJ5J+oHgv6tNNbFA==,type:str]
    #ENC[AES256_GCM,data:QnCl4whCI3yqa8Fmu3zWd75RfoAq,iv:+R5BzdCFxeYec6m/ydMuD9oOeJTtlQbDAU7Ag4F99s8=,tag:wJ8hgaElVBb9danerv/D7A==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:kM+p6o4Q+aSgpuYUa5gb5f9BVY8=,iv:DpzpE8N14WMdzbF2qyJoufZ9hVYYVIWDddJeFbgIS24=,tag:yyu8kPcdFyWtRXWy5Aw0lw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vyk4C9LZUkv4jjwZYbz3ua6k6eaQWsldwVQjxAcpIX6tOlBG3rHKsQ==,iv:kJKfkRoLxnZP9l2AV3qyHQp5Aq0CKLVvgBZiJkA5160=,tag:ZrTDTg0HUCqKitGIJl6Irg==,type:str]
    #ENC[AES256_GCM,data:MEzUTsxOyolktvnAmkWLXWRlumAT2wWvEnxlLuR830NBxJbK,iv:zPMmAH4Su0NITwZ6qc/EroxrevoNROWICi7RK5f2+hg=,tag:6O92yAEjqY6D4drACtR8sA==,type:comment]
    key: ENC[AES256_GCM,data:CGFXi82TYQ==,iv:W9v5S7a77iXTexr3rNbaKd2MZ6eBUQ1bU/MYIZ+Ezv0=,tag:ce/bYI/9QQkMrLiKqt+ZkQ==,type:str]
    secret: ENC[AES256_GCM,data:LiXnFLKtT/aqKssSSavdc9dAVWXZG6pSGqnqnI7iOEyM5LvEQQ==,iv:tztRjxURsj8iD3dSwH1Y2mqSaAV+uf9KU7LGWlrDIw4=,tag:gPW6HG4mEnBKRh9zKV+FRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTEpvdy9oSEtDUDgvYXpG
            TE1GT2hJbWlFaTFWbzZTS2NRRStlRUZnU2tzCmNlWnFhTnkzSXp2dFJIZFJDQmR2
            QVdrazAreWdLNVkvNEx6ZFRuRHNyMGsKLS0tIEluNXRmeWdDTWV4M0VSN0VRMnNl
            d0M1UVhVTHlPeDNYU29WNG8zTWtqN3MKPlFMZ9iR9tD2VD3sLxpFBNeDLNHBKESQ
            isF3yP2VGUHzmBCRwSsmJnLermuxRbTDVsOenNWMQMUoiMXvCRmyPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:49:05Z"
    mac: ENC[AES256_GCM,data:kP2qGQYYWl8elm8dCx+9woOsiUXLD/FPZjs5Mh60tgdYg7R97L34/vsPEtof6fItkidnmiKKYv2++laYlDfxoA2z0nB5L6KDcxzVwkFGnot5j+o0l40+VRimSPIqmnEQ4/Y6WaaGJU2t3MosZInqRJdtkDWTyIn/vnpUNn9WtEQ=,iv:U0fMgAOobNqvijYRq3fiWxHa8rxYZma86dAimxQPBnM=,tag:SsGiR0kq+eFOXEvvKA847g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
