apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:tNkCr8yrMHpCra0nZ0oEZbq5,iv:Fl5IT/os8FpX2AHYVS3R62292HUDlm80U/CFt1OkCSI=,tag:6GzI4YNwiRgrA+n3PCsVBg==,type:comment]
    username: ENC[AES256_GCM,data:eV/Mu6Gc4Q==,iv:gfPBmjCqjEeaRICaRGcchTSnE84jI9ehDfB4X9QGNd4=,tag:fbn8I4CaNMeakdRGU8/ZGA==,type:str]
    password: ENC[AES256_GCM,data:rRB0jUo5wlV6TwP1CrY=,iv:POpix8wivO2avhzrEX56BBqodFF5JyMBQ7tjf0YMyTE=,tag:lkAUaxu0AnKkNboamwyPUg==,type:str]
    email: ENC[AES256_GCM,data:e3lweK1d8CJ7VwEe5P/S,iv:TCr67TcnCMqqf84lDkAlgeGoNqY2mkokpkXI1C9v6ow=,tag:N2WqUiGAviiypkP6qXa1Kg==,type:str]
    #ENC[AES256_GCM,data:JeR1Hvp+rYt1DnjFptarzOt9oRw1ebE=,iv:N2CqaGidxT5YvP/NN9KkUqu1Icqz0N3I5McpV0wivWA=,tag:oWHsFqqYi7fT5WTffOrfJQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:aAofCn4qcA==,iv:hHOBlwSYiwYzHlC7C2Wo3QmkNUuvENYseYshtfleSAs=,tag:IDidPQWo3xI+t8iUafk/Vg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:VPTL3tTKWg==,iv:/KpKYH/M1uWkpU5nnV13Y3LV9ZA+JVp0vrgbuw9Fge8=,tag:xkKgOrIEgcxQ+UAxUwnJ9w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K8lTdXpWwFF8JFBiLHaFHGH06g==,iv:VIvDLaRjfXnxwsyDlrfKPhNaVuaj5taGjgElyNUsHaE=,tag:ftLyySo31juD8iysTzKKvg==,type:str]
    #ENC[AES256_GCM,data:z+i9WZJ/CMxciUgnVwt2KA8VNC4AXz2rbu3TG5IM4PA=,iv:LQ6PGsGbM0d+kUEPNU/W105gHpBxgSK7dQNrqohMzM4=,tag:lHfgZycAPAs/QaMDy5c9wA==,type:comment]
    #ENC[AES256_GCM,data:PqrmFN2RDBy64vbA0vCRSenlbK++D9D6AutgAR3X/XGVBAEnDpf4FXleyoqGIpJ23+1mRA==,iv:ru778cqd6VQ/xDxKNHHtm6zDkkfb3HyG5cGswwImifY=,tag:TjDNoWJ6ZBYn/Vz3V6Nu/A==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:jwl4/NLkhkv/xxEGQIt2+yjPkK2dO0rTZs0Mzde32UmDVFgCCaPEmrFatmZSgAwyx+q78O75b7Ng1gsfY479N+qvjws75Yr2+YiUivt97mAf1yXACMDSUA==,iv:wWZiysQhZXXBELYvBjIaLyDFnRDILcL++gFs2HctayA=,tag:eH0w+meXxJL112dPt9/yTw==,type:str]
    #ENC[AES256_GCM,data:F6YFseXUk1RD42u5ytCvZGQenQwHSBO3gt7ntTP5dBmkN7vMsNUO5ebWOEdBvASvfrHWggiZ,iv:St6f/qZCXLZZdAbZrVSq/H6ejs5PdTXZ731Hu3XkIRM=,tag:qycm+qMqDhEVHeEsQ/bfPg==,type:comment]
    #ENC[AES256_GCM,data:3Fs0gVeGPKBJ2cLuQIyNAKbwP813gCHghPHY7RMq+yHPfFbDnbHxpt1mDZ3ZVA==,iv:mlFSW+ObS760wA1OOplu7uR84+KokD5J2ALiOahsNS8=,tag:ruq0SHhjB73htAfhaobXJQ==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:VXFFPZ/Cz3mrh1UOxr8WTIALCUIWLU7f0Y/iqh+6VmJq3n+GBauDU3ZzTL8FF0WTu2L0ZFZwCsHEiUHH/o0X35f1sM4ww0Hy1+MJT4FJ7GvcJorkEIUb4B6v50fRfkr7zJRLOLZBZrKLW2ySFOpbC7si/N3uIO2N7a2kxOF4RWZ+ExDrsKETAOGrQrI=,iv:GEFgDd/XdGFOpQrUWBFTFXkrHfbfdG4BWZFBTAYzgGk=,tag:1tcZ7amV9fWHj+b4SHKScw==,type:str]
    #ENC[AES256_GCM,data:7RRS78A03I/rbDa9irD+u/MLfMMV,iv:xMZqLl2aBNGgAh7D+7WmqBRwvqy8AZsshEhUAqCxtOY=,tag:+mCOCFFfLJGTQazOXTUVCQ==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:zDqWUhjn77JiiNJ57DaM9Tm0VzE=,iv:U6tDD/bkcEYnSxpoFVt6ymp8OcsE8YegpQVw2MO7328=,tag:0o1odcYbmEpO8e7FmOZ7FQ==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FQBcwXgW6mFQqUBjdlwKXC5gmyXVKm+vAEotAiVxENxRfjSqV57SoQ==,iv:6JmoDxn4Hv1V78j9BeZieHucb2xwS3FbizMtpurfntA=,tag:i+HdUTyp4gANyPH+kMahoA==,type:str]
    #ENC[AES256_GCM,data:TsvctHrqHd0khcdKJX18qCvQijQ8bewJfpq+Y+LVp4tPAy8a,iv:+paj/nrBwl4pmA3Oz4P2647wW9SGRxO51WfgK2p4RSA=,tag:DZlsMEDWheUtCFFO8FP+KQ==,type:comment]
    key: ENC[AES256_GCM,data:v6IwcMRfbg==,iv:2zTFdCcmJR6euUcMiOwGFEIpproDyYfjR57/oVAwOz8=,tag:pH1Eg+yiBZjgREeMPP+ozg==,type:str]
    secret: ENC[AES256_GCM,data:tvJqPBXmRv0XEHsK5//GbD/t/NhNvesWsf/Ea/vxdMGad/r2dw==,iv:msGV4eUrGG63JzfoLTEaJntYuYeRGu82XfVtSpVo61k=,tag:U6K+Qc4H9a8AZJouw7Ax/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SHNCbXlqcTR5aWdyZC9E
            YTYrVXpRd1ZJVGZCaFIzb1VvM0JFN0dvdWs4CjVGODdZNFpTZmJWcmZyWmJ0VjNL
            czBXb2lUbmZHQ0xoRnRoTE05eE5HeGcKLS0tIFQzNjRQMDJIRFNvM2FBeWVKZ1NH
            RGJwdGpMdy92bUJTaVoreXd2eHozcjAKuU3qKVsg3ExTMT9Ma2BWj+RWw+AZpdu3
            ITpKTHB45Ak8O1HhipZ5CHf3EQX1/4QZrVbRqy2JJiX7okH91ptoJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:47:16Z"
    mac: ENC[AES256_GCM,data:dcs1Usp+bmPINHfvUgMSWDZydnGK/hOhIIG50Q75ZzYvxrqYzgg4iEEGdYcuvMAQf/GKY21eBDOGkdusvtk1bsL3J0xVrZkHkmrNg2SODGwp/xfPmsVIoSuuAvM7bLWEYTlqWQb1yuIrMcyoKl4Rzt1n3uU2zGJ/qvs5NAdMRd0=,iv:SNgCYQxZwKAyenNx9sJzQoTr5TITh5DQD7qajqHf/KU=,tag:eTDHDqdsPBbAJhOT0eWCfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
