apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: utilities
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KupS/BbS/hqQzyE4RDvp+Hh2,iv:6zEwEUk+RyzvKBTP9BTKVGYXtVYknMOB92otK4Mmh8w=,tag:8cJglZEsa6Y4r0g25oDNiA==,type:comment]
    username: ENC[AES256_GCM,data:xmovfEJPTg==,iv:ysOPkzPSMQtDhUFDi33xs/FpHNInFchAdfqL8EuXqyc=,tag:3xqg72ngo1P7B6V2Hnfumg==,type:str]
    password: ENC[AES256_GCM,data:Z+uAoMXB6mu79Jaqb5w=,iv:l9CUnpqG4taOi78XWiIWuyDg2NSFHNyWRt5OHZyssbk=,tag:SYZMY+Kog5SUK4cJgpAfSQ==,type:str]
    email: ENC[AES256_GCM,data:kA1R2AqVmpmTRH0xeuBJ,iv:Ie5ZtkLdQXEoBYaAdLYxnKwURvnJ8IzOmskMa4CdTX8=,tag:HUns2h89z7y0xfl/q+7SAA==,type:str]
    #ENC[AES256_GCM,data:5xfdCmw1Mj5wv8CB14tjOXHV8kosrc0=,iv:vcgvGuFs1zgCMSTbgcdxQiM877gzgy8LAK0y29KzS30=,tag:KAOEecJWJzOSyvQOOeOCOQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:bERttJHlCQ==,iv:8zVQ8fVJC1kEYE6eVDLiWIkD9cteCNUk2pQsmjqeBf4=,tag:HTSuGLTC77lx3rXN2W+Pfw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:5+hlOf4zdg==,iv:FP0mM0xXYTigdmeBIF+dFK2rE7L72EPD9WxzCUY+l18=,tag:IvP8rUYUw18MzvuDEhr/4A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BOjLQELmDJeD04hTSnvnG/I1kg==,iv:8MQlnRNwtiPR+nYtw91CNSYN/3OhkjJYLdv9j7WcSpE=,tag:f04SJDZwjvlSVEeff3SefQ==,type:str]
    #ENC[AES256_GCM,data:GzKahxy8e6W4CVRYTX65qLQFGHiigFpNQ1JyUHV6WLI=,iv:3hoKU+8Cadj5e86HwLCrbuAjM9JEhRsgOUj5lNj2iIk=,tag:BgSXNPd5JOi0kBdiWJ4z9g==,type:comment]
    #ENC[AES256_GCM,data:nmTsaB8xfXH9S0zr2nGCxdIm/ppZU6gvD+1IH1cavmYVyKB5SlDxzEj+uC7ulu3KrcOPdA==,iv:PAxDWLzBG0BCiygGazHxq0Mt0X3SHD4SHdM2XEwXXSg=,tag:BXGrFc7e657XxYXrigOj8g==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:HMp+ZXlJ6ghFX7YgEcKWln9lPKp1WktSlBVWc4M9C4PrwUWs0egNOnSBqzLCr1QSvwToBNjy0wFpMiCvM6XTun1/xdk0Ft7VRvwu3VUww4XKrePHgkQXGA==,iv:RLHBIiP5EiTmwew7rdnBDLcpzg19dDGXhxbNZF34e2k=,tag:yxGejpwdWkqMVpz3BuqLcg==,type:str]
    #ENC[AES256_GCM,data:YqtxLDnJ28sOZe2ov+AUQuVsDr31Xb6d9VMcwOKzCCTXpBFQ9b/ITdWvKiKAJHImOI5er6Z4,iv:PVYbuw2g5ypRqiTPi60fI9PBu0P+NS15hqcV5R86lZU=,tag:nf1tQ6rCoJJGEN7EhkL3xQ==,type:comment]
    #ENC[AES256_GCM,data:FH6Bmdkkkp7Tjvbf8h2tSpZCcMTvCIg/iREUb7fvEKzHGmwKNz3nWph73VbZyg==,iv:AF12WPUUGGNn+GC8DSnWGpSS4WmyzP1mtA7bWWXpS9U=,tag:zxzVT2mTT0hWWpQPezX+cA==,type:comment]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:/+4o1/JmluyMjSiPld0qZbmrNt8CkuSF26z4GkdOHMLZNfW3CIO/U6dv7rpOfbBVwQ5rvu7Dkqy0vRc92l7My5utRCllP63Qv7Fgc3N0RRQ/DhXwuoCrStQ2qpBUQfmNoU1vwcZScvqwyt4O0TOyDCtb8J/gJjGqvfcG2sJ1gVWY3jomFra7X0tWcQE=,iv:yzqcXVq7fC04yPgJe6t3C5bQeVj6qqoQ98/Tt/+jGxg=,tag:2KtwGX2X5qQ7U6JN0/uLsQ==,type:str]
    #ENC[AES256_GCM,data:t6tVnIK+D44L0MGs/9w1QAuftbbo,iv:+5dL1n/UUozeG3qEQxkQ+uOUyl7f77NWUWEocfCJMUY=,tag:6fgu2KqkUmu7DqhGFYGSpw==,type:comment]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:JVY6SXD+PNC5w+vMnd+TPwHmC48=,iv:6ndbwvKrxJGBd+6u0z8JEmJNCwWeGwgV5TFbT1/R2ow=,tag:n1ifLziKwH6qxG1NGH0nGA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oRMsQMRUaUEmCnw/VROpLX5D8Z7ri7HWp1+DfG9/bjU9jDplsALIsQ==,iv:Pxv+3AS5gfKlo/Hg6cb67lP7HEkH8xEVpiu9JskEwWY=,tag:DzpPO5w8q0PN+UZnOAU7cw==,type:str]
    #ENC[AES256_GCM,data:xaEIMuA0XUkwnZDBl0oZgpHlyOCKXPb9bV0XeQ5B+4W36ydP,iv:heD/adY74ZFctlpK8g9kuS+hgm9HIVpuNi/ywPCqteM=,tag:+DtcIhlIqv+jpVDzjVN2hg==,type:comment]
    key: ENC[AES256_GCM,data:pY7D2rgRYA==,iv:vMCnroOta39gneA1OWGmbsUwC0ZdO39HCR8swvBR4Bs=,tag:fC4iy9JtZrKDqpHuMGxs/Q==,type:str]
    secret: ENC[AES256_GCM,data:tItEx1yFxS3xvgONzHIBC4Xzo++uplkSsnPldAYY17S7EacEWw==,iv:bJGq+PFlaLzh9tDgHdRNr5x75uA4MoxLxxnjsiZnsm4=,tag:mGKwVH1NRJtwP7DE+6ZjjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeEcxd29IVkhIMGtHZ0JP
            L2xKdU8wM0VBMzBuNzlPTlA4MGVLTEFnOTNjCnFGUGZ3Wm5BMURSbHp2dWhtU2pi
            UUJsaSswUzFxQlo4NFk3UTU4R1daSEkKLS0tIFd6ZGRVM3Urb0FyeS8rRml3UXAy
            Vk9uZlpBeXc5bXVPVmlMYlRuU0dlSEkKDI37vJY3tG3tHNxdxASvO9HlmqNdfJfp
            58ZkKZL5Tq0VAJ7DWWhmtd1mrtU50B9NWeJXjB0jq3YcPjaNg742dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T02:32:16Z"
    mac: ENC[AES256_GCM,data:+vkwcGYMd3AtjiMFOFAtK6/r/O2XWH0ZZGhenFIacu03ZwaLDsl/ctNfHovlXj6h2TZjWZwB+y/nHYtDpCY0eQ/qTqYI3hlN63k/ea0Z2VQHzTiTsSAIdxgBNVcvKEb/k09v91xiZTScEsU0jcbh58Gca5wtp/RujnxjXJA3p/A=,iv:2rKiX4GnYb3EvQbvB44W1pO8s+AWONtC9bWxq4YcZO8=,tag:iKH6qCTuf4YUl6/upy4Zlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
