apiVersion: v1
kind: Secret
metadata:
    name: phpmyadmin
stringData:
    PMA_SECRET: ENC[AES256_GCM,data:WhPn+pamm3nETkl7LOb0Oezg9kOWGIkAHp36jF7Cysr8I7cxRuXV1qDeU/CpnAhJNbtMIneTz/YqQYrPpM4yfQ==,iv:5In80C+uurFhljIEaXJZ+7tuMn5VuvN5lln7j3pSoWY=,tag:p9kGKbgx+DV28a/ld2Di7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ3UxZWR1c2NNeXdUVGlR
            TkFhakZCaUFJd2dva01WK2hJSk9LUUg3eUQ4CjNNcy9iRDFmcUJBWk5WdHhoV1g1
            ZEt2Y29DN0pPMHczSldjK2ZCOXdrMzgKLS0tIE9ENis0T2QzOHlqTmpFaTBsanJM
            ZGwrOFRZYjVoZnI3OTdJdHR0czlFY1UKaECCYd9NoOZ6te1B837bS2Dk3yMlgEhg
            9HmSLEY+6B3lvux9MGiU77Lnu36h8GZHnbszOnkPOIktaL3RNXAkbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T00:03:08Z"
    mac: ENC[AES256_GCM,data:ajvfXpP87fgRrnuMdNlYNk6DfVrKraYJTHrTbs6IsqSFJ1DuDA/iGDUQeIAEj0Kheio2yhqq+k1XQdiIswEaYAp2fUiKsqWzgZ+BqdhFx6c/BkW/TpCMYPAnfnaxtPeWwT498tcSOYoOLv7vqxrfeCA6qW7w9bZvOycB2MX9+gk=,iv:Nn84Pg7yk/HAVv8vGhprfDfviGvDh6lKMFWbPqfCsCg=,tag:3oovmUWBeMCPX7E2aHQFuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
