# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: subgen
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:UA89vxLM1yqNupf7ykxizBr3Hh0=,iv:S4G6Jk7+AjrDBxRpm6VjaQj0vKwZDSuSS65tJkLAc3E=,tag:yScaU2XrOpEJP5eTOPJGrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdGx6Yy9mYXBTbzhhSnJa
            bUExTkNyMzNPdkF1eGs0WlJQd1QzTGg2MnhFCm1qckJ3aXJvOStIdUtEdkxrbStG
            bTVuMCtjSjNyM0VXczR6bW90NU4xK2MKLS0tIExCWUpSOUx2OUIzQ2htZzdRUWxs
            WGpZUEVBbThKVzUyZTUvYzB2QjVPdzgKdsx9L+bNcdTwvgfvH9f//NmW6P33l9KT
            79ZWu4OAjAkQ9HQXkktSXksDaqM150aeGJEcBUEHv46XvEgQOyC8ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T05:35:19Z"
    mac: ENC[AES256_GCM,data:W+KJLuUsEErDUu2OGSlEGeGMRt66hhuSdkvFTFi8QmWgIv+86ZgbRTPcRFiNRErGRCc9Pghp9sKuE8PyD04pY6y1f5Ujvqi8EMDri3596aM7RTPW7fJVrVJcNzQsXI6LABd49EvvwAn9+Hvdfxyp5ik9dnNvKc/YsZVQ9aXiVdE=,iv:FCoRH4QR9BcDuTnEwl/ZY4YbFGP6t8alvJiMsoE8p7Q=,tag:8pXIChlD5BJSk3qgV8IntA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
