---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ragnarok-grant
  namespace: databases
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "ragnarok"
  table: "*"
  username: ragnarok
  retryInterval: 5s
  grantOption: true