---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - mariadb.yaml
  - database.yaml
  - user.yaml
  - grant.yaml
  #- backup.yaml  # Temporarily disabled due to S3 variable substitution issue
  - secret.sops.yaml
