---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-operator
  namespace: databases
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-operator-secret
    key: root-password
  
  image: mariadb:11.4.4
  
  port: 3306

  replicas: 1

  storage:
    size: 5Gi
    storageClassName: longhorn
    resizeInUseVolumes: true
    waitForVolumeResize: true

  service:
    type: LoadBalancer
    loadBalancerIP: ${SVC_MARIADB_ADDR}
    metadata:
      labels:
        cilium.io/l2-ip-pool: reserved

  connection:
    secretName: mariadb-operator-connection
    secretTemplate:
      key: dsn

  primaryService:
    type: ClusterIP

  primaryConnection:
    secretName: mariadb-operator-primary-connection
    secretTemplate:
      key: dsn

  updateStrategy:
    type: RollingUpdate
  
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    max_connections=300
    
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi
  
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  
  metrics:
    enabled: true
    exporter:
      image: prom/mysqld-exporter:v0.15.1
      port: 9104
