apiVersion: v1
kind: Secret
metadata:
    name: mariadb-operator-secret
    namespace: databases
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:By+qlDTR1Ss=,iv:7N5VPj2cMsDkcI9qYzf7o2CUT1jnImUlfjrGE8XbfyU=,tag:5Ai2k5ySF2GBhBlstsA1UQ==,type:str]
    user-password: ENC[AES256_GCM,data:y/trsUZ1+YOszgvhtnI5tL4=,iv:CkTMm7rWH3iydAbZzvyHiTVgMSnOFuKrgRVqgrOsoUk=,tag:k7EfBb9ln4NrV4cpz6sugg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRjNOSWdjZ0J5YUoza3JT
            NnJYYTRjVnhTUHp5VFNKdUJ2ZXg0NTZkOWg4CjRhSUVUOW9WVmxFQ3dGVGZaL2dj
            dVpKU296cWMvNkVhUWVWVmkwS2h4T1UKLS0tIENmMThTdTVwZG93T3psVHpueWFn
            Sm5hMHhXanlkcEhaQ1Izb0FIczUydWcKWOsF6GAMci54VIMD0LL6kYAMoC0r/iuM
            nFBUhvK0WXF8lTdgDdJZ2efquMzd74mozXbUw4D6shPYeNj2F1l23Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T07:08:20Z"
    mac: ENC[AES256_GCM,data:2zyp3CsiCkvpM7lJksqod2TocLDQsw3D03ExEXDerBq1U10UmgtU1Mnl7I1tGNi6jkhhY+aKrA5kwl4B62Nl+uJkNbo49LQ/uVWxK4m3P18Dh3mKwirdKXjF5a4iQP4asYdi3S3isVIJ0zQnqM+c+EBV78G22sN2GNW8z0aujhE=,iv:ZPuK17y8RleWexdBD63G75v1EujQEkceajkL5kX671M=,tag:ZVCPnoXNtQmLWhU/HsUtAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-operator-s3-secret
    namespace: databases
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:HBUk0bDzlII=,iv:34fg2GGE8cktwJBynejaB7UV72ROBx1EQUvEGmoJ+RQ=,tag:N0O2azKN+8pGtK6J8ep6Ug==,type:str]
    secret-access-key: ENC[AES256_GCM,data:qzdGoTwdX4E=,iv:wjlo9Cg7H5yWBSiJ7xUFfXZWEogysJP0muHgufTdX7U=,tag:c2rXPGqVrhnureZXWDZuKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRjNOSWdjZ0J5YUoza3JT
            NnJYYTRjVnhTUHp5VFNKdUJ2ZXg0NTZkOWg4CjRhSUVUOW9WVmxFQ3dGVGZaL2dj
            dVpKU296cWMvNkVhUWVWVmkwS2h4T1UKLS0tIENmMThTdTVwZG93T3psVHpueWFn
            Sm5hMHhXanlkcEhaQ1Izb0FIczUydWcKWOsF6GAMci54VIMD0LL6kYAMoC0r/iuM
            nFBUhvK0WXF8lTdgDdJZ2efquMzd74mozXbUw4D6shPYeNj2F1l23Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T07:08:20Z"
    mac: ENC[AES256_GCM,data:2zyp3CsiCkvpM7lJksqod2TocLDQsw3D03ExEXDerBq1U10UmgtU1Mnl7I1tGNi6jkhhY+aKrA5kwl4B62Nl+uJkNbo49LQ/uVWxK4m3P18Dh3mKwirdKXjF5a4iQP4asYdi3S3isVIJ0zQnqM+c+EBV78G22sN2GNW8z0aujhE=,iv:ZPuK17y8RleWexdBD63G75v1EujQEkceajkL5kX671M=,tag:ZVCPnoXNtQmLWhU/HsUtAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
