---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ragnarok
  namespace: databases
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb-operator-secret
    key: user-password
  maxUserConnections: 100
  retryInterval: 5s