apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app hajimari-external
  app.kubernetes.io/instance: *app
resources:
  - ../base
patches:
  - path: helm-release.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: hajimari-external
      version: v2
