kind: Secret
apiVersion: v1
metadata:
    name: authelia
    namespace: networking
type: Opaque
stringData:
    identity_providers.oidc.issuer_private_key: |
        -----BEGIN RSA PRIVATE KEY-----
    identity_validation.reset_password.jwt.hmac.key: v9Acrv1ToJpj4OEbHaxYzzA00yuuYcA0CDPp8ECRLsw=
        MIIJKwIBAAKCAgEA2dJQF7I6/rNo/MRVxRxH0Y8V71vDPsPyCAy1/9vn5vU4FR8C
        XEXcYsvnY4dqfcaQwEKA7DgmXyCP6FMqe3gDWkLNFOAoMgA/Ks5VVDqO7c2+/P6i
        Hnz8KkxB8Fa7iEXpK4cTwmZgbSbjzOe79KFY27hhNxFebaqtoLDNZdiWI1U7byBs
        gHh5zQ2AKg5ScGBaMtKhYSSKcHh5r8Ls9YYbKCWc0vgCu4wQHyM0EUDXJvdQfgCI
        gwaTD64pIE0qWwI3Jty5QIJLyX/okpViptR3T6YKwrFmZ192d0O4QoIbr+UK4mTI
        KbDsXOia7evzsOIwntWcLJXbBcqDI3J97T5+jEV7qVHVNodTtFHl7ssclU49tsMn
        X6x3otMRBo/0qAapRN9NX7qanFCLQ0K4KHTsYT8UM6lzGTjZDMtENAo9xdNrxD4t
        rSgoG/j9RclYunMl1sxgKV2bp0DQ5kGv4undTJOooZKEHNC2rcv+RwTDyYCEJ8ZH
        2ssixMZvJXDi1XZchyhUMVmGgx3NFVzIIfmaK4s+PoBkQN3TXmWKLxUPPm1MYvKe
        SCyo3vzOYHmv8x6yx8zQqtWgeGSfoqwAkJc1GiKYDjSSrZwcmR9ow4WfLxR0swgS
        f50/IwtHXxGTjhn/iI/dvcjD4ApxaI87Amp7dFYjU1eGDfqvCyE4xduAaaUCAwEA
        AQKCAgEA0K2eMbV8s3qqQE7QZPB9FZThTNk6qi0K+Q9EZYUGHMwdGI8GseP0CWqT
        mVSofyr2jlqoLKZ2jHgjpk3Wy0bk31pUI4XEvHJkEdxu/yzCtayBJtvD8TWIV/WK
        zngpXZqskhjsozd1ddzmLO5tsSXKfWWdLSaksqfrg6Eehk4DOIJ1WDdV+5ZwCjS+
        7oueCy8j+sCz/t8FCk9BNVOntGjwJ3wxTCRyab77yvjs7wKRnTEemjhkkDKCPWl6
        2QlUZLAwqjiX+edaOAckhxo60t2GGHZYpMFT/AEG+6eTJZSEdfUWgmJPKTHon/Hw
        S7PbWUC5l9HJtyUyGdAz5ofPgLR4gqExPc+Lq22b732YHu/nmvgXIbydvlFVFY3L
        YxpVAO97cTV5ncXM1sILgEwJq0KiR5XbOfDL55n7eMz5QeLOMiuC5epGJn2nSInj
        sNwUcAiuIDJ5LFbvviFw4TfSUDoKJLHT3W7Vkt4UbdG+ycwkZhF5dXAb9qLQgUHR
        cu7jDxtqueLAm1eGXhPO2ubBn3MBmYvORMp8ed7ZZMkS2Pb+UthhB+H3mvQq+7T5
        FXrMZFWhZhjCci8j17c+PEkMeY95sKWVEpNTeMhw7zoxGo5BxrRrkNcspjWbQbUW
        Hu+GUdcB6E1PrSlQ6OF0Czdz1zWrf4KoKlgzEq1/UHTBuq49jFkCggEBAPdzoAvc
        rGsCjWLLUVRnlZReiVEB+UuLc88n8o4ePEVJLn464QYtOJzA6qC9w0gBVIC0cY9M
        JI9to9y/O6G1aXSLVQbykzG1V0FjB91m8r874M/IrLDdauVoZJOUfVPB5d5gA1TH
        FzGAxzTk4gVSrrMeG/PjyMxPZvjp/5XM9is2a9J8/+2P3J/iMIN2puF8wXOWpOaV
        8DFII4/UwLrzSwg3TuP7rDS6Vz23lR+YtEN4fVefhh8ynmobYxh70q8/w8Y8KCaX
        KQlic1rEOogH+dwjdlUVmHXD23o4d/x4R8bJAmO1t5H5EamNTYYCZv12q7s6gnAW
        +XeeyqgcPinTJDMCggEBAOFYpjtB+gMa9bCVZeOxMf4mijTZda45KQayDgoCFYaY
        R021rFlULlnLVOATf4nPXzQI4QhkU4R9o/xyh3MLMMsNaOx37JD9GHYFh66EoRHK
        PE9r44Vt1ZpsawozJJ/se/vcNGHiTFlR0qKP7LqO8zIP3R8pWoDx/sAgkrYYh9tp
        /1N7XN6N5ZvAciekUsyhgHJia9/ZeCMj88XhyMN8plBcnkqS/1em1bSVJCP+Py61
        UlnSmBpjnSX7M+CPlcbvV9kPwfoHHQZ76Y64++i0hSKVgMNnxcjCSQI0hSd/loug
        zHxAchSEjYGpM5uu3y9kDuGtVv+Iiysfl0u0laetoscCggEBAN/n8wjou+b0X0Tm
        3oe2VwXy6OOxGoe9/qOS7Qql1zmGd5hm5Ji3MIO+mE+shdhQw8rV+++DIY3a0qv7
        KhUv1uVK8jwgIQqYoQScfFBdSAe8QbciSQicwY4lgOR9N04jpEEstbbvk1AKy7ZT
        6SSR5VxUQUzVbytYKb/P1KIS3SjKzJOg4d9vDl5pyCYcpfJg9ZcG192CDN46/Vq3
        U1GWte0QRsVKRE9N0YUZ6ci2X16x1xEDWtQ99FPkxi0wVbqXwylL47TPkKVaPTED
        YEcYmIEWYYupx9O/zofwMrnziFcaKZxZoGpoag/2uRAqelCdIdV/oumUEFWqDIxD
        SgiEcjsCggEBANHXn1RnJ81keY2qUWsqQoeMk/6K0c8fY1jczb38GtdvTlbK6md0
        wITVl3/iKE3IUbs+2W7bHfqulNosPH2g2hr7rc0mD6EkTnb4x1R4JRVP4cGDkida
        FCLs+vBQl7ZknT/32r+b38T9MMw4ghVnsIfZxeuSsriIoNWAf54aUci8eArhQaXt
        NPdIygSoPIJZkibyB8o31GvEuuh2TGHd3XHQDYccQ7L3pOG4UCNESsnQB5OlTAam
        5FvOBI0EqFDL6F41Ekkl/p1fHirNj6cvExsVZQaRx9gfM6VeCvCxGxuC7Wh3CsSY
        er1XNruuqB6ValY0+GKUYCQUEutoikPOqVkCggEBAMq16DrluYjxO3HcXVJUbTPW
        8S9/Aewc4AAwUs+s0GQTALm1VK9j5rp9ejNRhemqfbwyLdICkxyUEOVkwclnzJLZ
        L86GC15Cn1Bqi/cN9b7RDfeemNvBCKRWhyOjWlqsvbTXaoAZAGQoY9iXqsNgBQHa
        VPcfcRL1rAWaukQDw+ZC/SRoPrBkNDuc3CEK0hABxXQDYRBSW7SFHiURqaj6xh1/
        TyygYxwJ+S+/TcmIKfNF+rrrQBD1XhVS0czGNP7a/3Lc31MOwTgdMiWk0OXCAihQ
        J+cwO6ehjlexgW+HIE7d93BSz3GeGtbopwC/4Ez4AKBij6tM7AsMaa0B2UKROCE=
        -----END RSA PRIVATE KEY-----
    oidc.jwk.RS256.pub.pem: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtRAqRFKbYaiskZf9hYju
        ZAuJdFX64NIDN+0r52N9oTh7jhas/sZPcUoa1m/9ImXVwl1uk0Hb82pcKWB+1fbR
        2uR59tOeR4oQKlidk7OImtbxDHKaIa/qJ881Ox1dwlBbjRtqRb5H+mtFkweDovIr
        OpKGqsBLQDj3dV/2cQDHrQBMgy6533dXeAq8M7DewMveR76vh/cwBMbf4KQWmcN/
        MGqNX/1oGqkQqb702NJVTAdobFKULluSVKaMtoWKja287W2phLYrDZRrK8HHSC9f
        L93RHfUwplFRDGL0kskIcG/EIbzLKJq0NTin8wIfPQz3PKbYjSynj4hXAxcAGetK
        iQIDAQAB
        -----END PUBLIC KEY-----
    oidc.jwk.RS256.pem: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC1ECpEUpthqKyR
        l/2FiO5kC4l0Vfrg0gM37SvnY32hOHuOFqz+xk9xShrWb/0iZdXCXW6TQdvzalwp
        YH7V9tHa5Hn2055HihAqWJ2Ts4ia1vEMcpohr+onzzU7HV3CUFuNG2pFvkf6a0WT
        B4Oi8is6koaqwEtAOPd1X/ZxAMetAEyDLrnfd1d4CrwzsN7Ay95Hvq+H9zAExt/g
        pBaZw38wao1f/WgaqRCpvvTY0lVMB2hsUpQuW5JUpoy2hYqNrbztbamEtisNlGsr
        wcdIL18v3dEd9TCmUVEMYvSSyQhwb8QhvMsomrQ1OKfzAh89DPc8ptiNLKePiFcD
        FwAZ60qJAgMBAAECggEBALUOwCVoMabbpA1HXqYswq5adw5VeDVe7Qb87P1KmPMh
        5zOz6zQuHHzeLK4oeInwKWxeP9eTcR4dSqG5s7vEQB/Sfz/aZ5mELxwZVyG+0yh7
        LbpT01tCbTV31/QQLpTEBHi7ZG7vk0yP/pfDWNgVsDK3GWEgP1+uV44Q8wAXVpTg
        WgFjokR0l+vBNjC9mYOKrkntPSZEM6Pv8oISfHiAzRTGOmYDMG+BoGyPs4/uSVtZ
        zqBHZvL4hpDHal5j5KpZqQWc9g6eVEM/FCimdJvfbZpqtxl8OPrfvMxe3fFX4e4H
        zN1R4yLVUp0M7ooHRzu7mBOoe2sMtkpj07N/0T8y4/0CgYEA7VNnmcRQrrF73hiz
        xmz+NzUJiAb3iJQTFOgPHcB1E13eKGS6II85mUhtxVtQfudnO29i3NJpEhBL+bqi
        6pAg1GfLq9QPUllQQdqMTlBXmCOegAMNa+Jl4rllX3/l/NhUuAMnJWplTjFuchd9
        qi6dSmK5rngmp6StaPrbcLnsK9MCgYEAw09tnBmLystXwPHsJQG2IyaVtE4LGpQD
        V9Yc19YwIx6wYfMCqNgetCJd0GqA6hoQuHNlJpcCQcrOHkmfqqxZQ/K3bxqD36+3
        zV0e557yZK0EoFwDs2jBW3zPFJQsuZvfVP2/xHObpfeqniT27T3lCIAIQRyU5iKn
        B70Bv2crArMCgYBY1xEAMcoWKyB4WnzpuaFMX1FLF3iQKwYdnGUUORhagJgKPPKj
        /5mLNN7Ks00lxFATorW6fhWRCoK2YFReREfV22kV0JNPu1lc3YgKRO8VZ7gMqZfb
        m+uR/N7i6gjZJs5H9/4udm6n3789fGexTjPZRa3GjvnBZdb4ZnfA8ghjuwKBgCHF
        ZiqLsERMjMvsCO0NMrU5QsF+jST3WuyhNTOM8Z3g/JazMk6HsCdtmdMj106jWyjJ
        qz/U9KrzqlhKWrVkP7skCNvJNexDsgBsjZ93OGp4EEi6IFmxT13GYvgn9uPRM/i6
        N6J8avlzrajSs2+qOCQUH1lC2+w/KaqI3/h8mk9JAoGASLr0fH9MqoaJxE0+gAcz
        jgQODzyIm5MpF//8Nus7bQkzXnc1/1JCTeQyW1AsKGVysCoZmWDYM0NrTFkCWL8R
        ddevqoaFmcwMCjubIMGzeyRrBDxRtud2jXXZe84VASrz0Tj8xgsp+3lD4iU1ZOFk
        8P9I5l0SMLcXG+M6PqVVUeY=
        -----END PRIVATE KEY-----
    oidc.jwk.RS256.crt: |
        -----BEGIN CERTIFICATE-----
        MIIC1DCCAbygAwIBAgIGAZMAuJlRMA0GCSqGSIb3DQEBCwUAMCsxKTAnBgNVBAMM
        IEdTUHBLJTJCS2VsYTBxNzhTN3JZeG1aT29LSzQ4JTNEMB4XDTI0MTEwNjA5MDUx
        OFoXDTI1MDkwMjA5MDUxOFowKzEpMCcGA1UEAwwgR1NQcEslMkJLZWxhMHE3OFM3
        cll4bVpPb0tLNDglM0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1
        ECpEUpthqKyRl/2FiO5kC4l0Vfrg0gM37SvnY32hOHuOFqz+xk9xShrWb/0iZdXC
        XW6TQdvzalwpYH7V9tHa5Hn2055HihAqWJ2Ts4ia1vEMcpohr+onzzU7HV3CUFuN
        G2pFvkf6a0WTB4Oi8is6koaqwEtAOPd1X/ZxAMetAEyDLrnfd1d4CrwzsN7Ay95H
        vq+H9zAExt/gpBaZw38wao1f/WgaqRCpvvTY0lVMB2hsUpQuW5JUpoy2hYqNrbzt
        bamEtisNlGsrwcdIL18v3dEd9TCmUVEMYvSSyQhwb8QhvMsomrQ1OKfzAh89DPc8
        ptiNLKePiFcDFwAZ60qJAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAIhTkfTd2uz9
        dka5iAQ9DdpmtIN+KNIShDJWi/aT9hmROhLOSrAuGyBBP3QXkXXnbs3OuJhe/VqU
        4wylxV0XIviv8YI8CdZG2J7IbimL5CRXgWInvFR7kMo2j19KR25Smki6/A9q6r5P
        I/B6knv+9aLHXCCD0PuaoeYm4OiZsZNZ5FLiE9FWBE9RkKepUWjKw/6H0HkukZdD
        ffZ2PCV3tegfgjPKG/MPEtitvf1PwConi3TOCPrgxlgFnffXuzp97oW1hrNrLMxB
        sJXv90E+4hLftfVfZLut3zUt/JHLcajQKoQWc6Xgvh17D67RCYqsALQj2sy86JoC
        0rBt/EA/sso=
        -----END CERTIFICATE-----
    JWT_SECRET: xPJGATKEOPauNAtbKRnPTL2x14W4xEY9ibD1YBX7YatOhcDo3WbMzCH4gilbekR
    SESSION_SECRET: vclg94sHHAN4LvH9iJgdnBK6E6AMwA23FzkNR91a448BGnkmX9Y3MYCrQuWNdg7
    POSTGRES_PASSWORD: authelia
    REDIS_PASSWORD: 59DpYbAdjpXWvbmj
    REDIS_SENTINEL_PASSWORD: ""
    LDAP_PASSWORD: RjN8GK92Wija7j
    STORAGE_PASSWORD: authelia
    STORAGE_ENCRYPTION_KEY: rbpPcBsTMZqxlspHF0UfuEiGEzaEqohHovdjKgvkGKdBc10dWzRjwfbByf6uX+iN6G2z4soo6s1jMfA1NdlLvg==
    SMTP_PASSWORD: ${SECRET_AWS_SMTP_PASSWORD}
    DUO_SECRET_KEY: eV6WY3i0md0rb0D1RWsngJ0xHlTqsu2DLUlMBFe8
    SECRET_FORGEJO_OAUTH_CLIENT_SECRET: 6bc15d4197adf8700b850a4694d7089b27b9070119ae46035bc1a76f289e51ea
    OIDC_HMAC_SECRET: I3MnpYlKTqtjQ4E41nahdopKKFBTU5DLl2TuNYEH8mP5FCLpXZifv0K5ludgmxjT
    OIDC_ISSUER_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKwIBAAKCAgEA2dJQF7I6/rNo/MRVxRxH0Y8V71vDPsPyCAy1/9vn5vU4FR8C
        XEXcYsvnY4dqfcaQwEKA7DgmXyCP6FMqe3gDWkLNFOAoMgA/Ks5VVDqO7c2+/P6i
        Hnz8KkxB8Fa7iEXpK4cTwmZgbSbjzOe79KFY27hhNxFebaqtoLDNZdiWI1U7byBs
        gHh5zQ2AKg5ScGBaMtKhYSSKcHh5r8Ls9YYbKCWc0vgCu4wQHyM0EUDXJvdQfgCI
        gwaTD64pIE0qWwI3Jty5QIJLyX/okpViptR3T6YKwrFmZ192d0O4QoIbr+UK4mTI
        KbDsXOia7evzsOIwntWcLJXbBcqDI3J97T5+jEV7qVHVNodTtFHl7ssclU49tsMn
        X6x3otMRBo/0qAapRN9NX7qanFCLQ0K4KHTsYT8UM6lzGTjZDMtENAo9xdNrxD4t
        rSgoG/j9RclYunMl1sxgKV2bp0DQ5kGv4undTJOooZKEHNC2rcv+RwTDyYCEJ8ZH
        2ssixMZvJXDi1XZchyhUMVmGgx3NFVzIIfmaK4s+PoBkQN3TXmWKLxUPPm1MYvKe
        SCyo3vzOYHmv8x6yx8zQqtWgeGSfoqwAkJc1GiKYDjSSrZwcmR9ow4WfLxR0swgS
        f50/IwtHXxGTjhn/iI/dvcjD4ApxaI87Amp7dFYjU1eGDfqvCyE4xduAaaUCAwEA
        AQKCAgEA0K2eMbV8s3qqQE7QZPB9FZThTNk6qi0K+Q9EZYUGHMwdGI8GseP0CWqT
        mVSofyr2jlqoLKZ2jHgjpk3Wy0bk31pUI4XEvHJkEdxu/yzCtayBJtvD8TWIV/WK
        zngpXZqskhjsozd1ddzmLO5tsSXKfWWdLSaksqfrg6Eehk4DOIJ1WDdV+5ZwCjS+
        7oueCy8j+sCz/t8FCk9BNVOntGjwJ3wxTCRyab77yvjs7wKRnTEemjhkkDKCPWl6
        2QlUZLAwqjiX+edaOAckhxo60t2GGHZYpMFT/AEG+6eTJZSEdfUWgmJPKTHon/Hw
        S7PbWUC5l9HJtyUyGdAz5ofPgLR4gqExPc+Lq22b732YHu/nmvgXIbydvlFVFY3L
        YxpVAO97cTV5ncXM1sILgEwJq0KiR5XbOfDL55n7eMz5QeLOMiuC5epGJn2nSInj
        sNwUcAiuIDJ5LFbvviFw4TfSUDoKJLHT3W7Vkt4UbdG+ycwkZhF5dXAb9qLQgUHR
        cu7jDxtqueLAm1eGXhPO2ubBn3MBmYvORMp8ed7ZZMkS2Pb+UthhB+H3mvQq+7T5
        FXrMZFWhZhjCci8j17c+PEkMeY95sKWVEpNTeMhw7zoxGo5BxrRrkNcspjWbQbUW
        Hu+GUdcB6E1PrSlQ6OF0Czdz1zWrf4KoKlgzEq1/UHTBuq49jFkCggEBAPdzoAvc
        rGsCjWLLUVRnlZReiVEB+UuLc88n8o4ePEVJLn464QYtOJzA6qC9w0gBVIC0cY9M
        JI9to9y/O6G1aXSLVQbykzG1V0FjB91m8r874M/IrLDdauVoZJOUfVPB5d5gA1TH
        FzGAxzTk4gVSrrMeG/PjyMxPZvjp/5XM9is2a9J8/+2P3J/iMIN2puF8wXOWpOaV
        8DFII4/UwLrzSwg3TuP7rDS6Vz23lR+YtEN4fVefhh8ynmobYxh70q8/w8Y8KCaX
        KQlic1rEOogH+dwjdlUVmHXD23o4d/x4R8bJAmO1t5H5EamNTYYCZv12q7s6gnAW
        +XeeyqgcPinTJDMCggEBAOFYpjtB+gMa9bCVZeOxMf4mijTZda45KQayDgoCFYaY
        R021rFlULlnLVOATf4nPXzQI4QhkU4R9o/xyh3MLMMsNaOx37JD9GHYFh66EoRHK
        PE9r44Vt1ZpsawozJJ/se/vcNGHiTFlR0qKP7LqO8zIP3R8pWoDx/sAgkrYYh9tp
        /1N7XN6N5ZvAciekUsyhgHJia9/ZeCMj88XhyMN8plBcnkqS/1em1bSVJCP+Py61
        UlnSmBpjnSX7M+CPlcbvV9kPwfoHHQZ76Y64++i0hSKVgMNnxcjCSQI0hSd/loug
        zHxAchSEjYGpM5uu3y9kDuGtVv+Iiysfl0u0laetoscCggEBAN/n8wjou+b0X0Tm
        3oe2VwXy6OOxGoe9/qOS7Qql1zmGd5hm5Ji3MIO+mE+shdhQw8rV+++DIY3a0qv7
        KhUv1uVK8jwgIQqYoQScfFBdSAe8QbciSQicwY4lgOR9N04jpEEstbbvk1AKy7ZT
        6SSR5VxUQUzVbytYKb/P1KIS3SjKzJOg4d9vDl5pyCYcpfJg9ZcG192CDN46/Vq3
        U1GWte0QRsVKRE9N0YUZ6ci2X16x1xEDWtQ99FPkxi0wVbqXwylL47TPkKVaPTED
        YEcYmIEWYYupx9O/zofwMrnziFcaKZxZoGpoag/2uRAqelCdIdV/oumUEFWqDIxD
        SgiEcjsCggEBANHXn1RnJ81keY2qUWsqQoeMk/6K0c8fY1jczb38GtdvTlbK6md0
        wITVl3/iKE3IUbs+2W7bHfqulNosPH2g2hr7rc0mD6EkTnb4x1R4JRVP4cGDkida
        FCLs+vBQl7ZknT/32r+b38T9MMw4ghVnsIfZxeuSsriIoNWAf54aUci8eArhQaXt
        NPdIygSoPIJZkibyB8o31GvEuuh2TGHd3XHQDYccQ7L3pOG4UCNESsnQB5OlTAam
        5FvOBI0EqFDL6F41Ekkl/p1fHirNj6cvExsVZQaRx9gfM6VeCvCxGxuC7Wh3CsSY
        er1XNruuqB6ValY0+GKUYCQUEutoikPOqVkCggEBAMq16DrluYjxO3HcXVJUbTPW
        8S9/Aewc4AAwUs+s0GQTALm1VK9j5rp9ejNRhemqfbwyLdICkxyUEOVkwclnzJLZ
        L86GC15Cn1Bqi/cN9b7RDfeemNvBCKRWhyOjWlqsvbTXaoAZAGQoY9iXqsNgBQHa
        VPcfcRL1rAWaukQDw+ZC/SRoPrBkNDuc3CEK0hABxXQDYRBSW7SFHiURqaj6xh1/
        TyygYxwJ+S+/TcmIKfNF+rrrQBD1XhVS0czGNP7a/3Lc31MOwTgdMiWk0OXCAihQ
        J+cwO6ehjlexgW+HIE7d93BSz3GeGtbopwC/4Ez4AKBij6tM7AsMaa0B2UKROCE=
        -----END RSA PRIVATE KEY-----
