
    ##
    ## Redis Provider
    ##
    ## Important: Kubernetes (or HA) users must read https://www.authelia.com/overview/authorization/statelessness/
    ##
    ## The redis connection details
    redis:
      enabled: true
      enabledSecret: false
      host: redis.databases.svc.cluster.local
      port: 6379

      ## Optional username to be used with authentication.
      # username: authelia
      username: ""

      ## This is the Redis DB Index https://redis.io/commands/select (sometimes referred to as database number, DB, etc).
      database_index: 0

      ## The maximum number of concurrent active connections to Redis.
      maximum_active_connections: 8

      ## The target number of idle connections to have open ready for work. Useful when opening connections is slow.
      minimum_idle_connections: 0

      ## The Redis TLS configuration. If defined will require a TLS connection to the Redis instance(s).
      tls:
        enabled: false

        ## The server subject name to check the servers certificate against during the validation process.
        ## This option is not required if the certificate has a SAN which matches the host option.
        server_name: ""

        ## Skip verifying the server certificate entirely. In preference to setting this we strongly recommend you add the
        ## certificate or the certificate of the authority signing the certificate to the certificates directory which is
        ## defined by the `certificates_directory` option at the top of the configuration.
        ## It's important to note the public key should be added to the directory, not the private key.
        ## This option is strongly discouraged but may be useful in some self-signed situations where validation is not
        ## important to the administrator.
        skip_verify: false

        ## Minimum TLS version for the connection.
        minimum_version: TLS1.2

        ## Maximum TLS version for the connection.
        maximum_version: TLS1.3

      ## The Redis HA configuration options.
      ## This provides specific options to Redis Sentinel, sentinel_name must be defined (Master Name).
      high_availability:
        enabled: false
        enabledSecret: false
        ## Sentinel Name / Master Name
        sentinel_name: mysentinel

        ## The Redis Sentinel-specific username. If supplied, authentication will be done via Redis 6+ ACL-based
        ## authentication. If left blank, authentication to sentinels will be done via `requirepass`.
        username: ""

        ## The additional nodes to pre-seed the redis provider with (for sentinel).
        ## If the host in the above section is defined, it will be combined with this list to connect to sentinel.
        ## For high availability to be used you must have either defined; the host above or at least one node below.
        nodes: []
        # nodes:
        #   - host: sentinel-0.databases.svc.cluster.local
        #     port: 26379
        #   - host: sentinel-1.databases.svc.cluster.local
        #     port: 26379

        ## Choose the host with the lowest latency.
        route_by_latency: false

        ## Choose the host randomly.
        route_randomly: false

