---
# Automatically inject NFS repository mount into all VolSync backup jobs
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-nfs
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [batch]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [jobs]
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: object.metadata.name.startsWith("volsync-")
    - name: has-volsync-created-by-labels
      expression: object.metadata.?labels["app.kubernetes.io/created-by"].orValue("") == "volsync"
    - name: repository-volume-does-not-exist
      expression: |
        !has(object.spec.template.spec.volumes) ||
        !object.spec.template.spec.volumes.exists(item, item.name == "repository")
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          [
            JSONPatch{
              op: "add", path: "/spec/template/spec/containers/0/volumeMounts/-",
              value: Object.spec.template.spec.containers.volumeMounts{
                name: "repository",
                mountPath: "/repository"
              }
            },
            JSONPatch{
              op: "add", path: "/spec/template/spec/volumes/-",
              value: Object.spec.template.spec.volumes{
                name: "repository",
                nfs: Object.spec.template.spec.volumes.nfs{
                  server: "192.168.0.120",
                  path: "/volume1/backups/kopia"
                }
              }
            }
          ]
---
# Add random jitter to prevent thundering herd
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-jitter
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [batch]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [jobs]
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: object.metadata.name.startsWith("volsync-src-")
    - name: has-volsync-created-by-labels
      expression: object.metadata.?labels["app.kubernetes.io/created-by"].orValue("") == "volsync"
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          [
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers",
              value: []
            },
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers/-",
              value: Object.spec.template.spec.initContainers{
                name: "jitter",
                image: "cgr.dev/chainguard/busybox:latest",
                imagePullPolicy: "IfNotPresent",
                command: ["sh", "-c", "sleep $(shuf -i 0-30 -n 1)"]
              }
            }
          ]
