apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:63zjPXeS8Tsm,iv:AGoD0NDXqdU9MbWTwqfxcb0DOe3VvUdRkOCnBTA1MkM=,tag:xF0NIniEIiLgb2dmDc6S9Q==,type:str]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:Ykxru/mOD9OiR/ZXkGznpB5mmm+cDJTcz/kplHZsa4WIlO+7m7sP2Q==,iv:P6sxSfUzjmFBB5s9fxUM9y2VjZ0VC/Zwx6O8nTyWiBU=,tag:ACgKrgwXbpYFPaxIoIDjyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY1UraUxldXZ1YmNuQVJP
            WVdWYUNKOHpZTS9WTVJ1T0JMUFh4ZFdmbldBCnlUMjJhaFMzalY0bFRtMzBYM3h6
            eXQ3WTFCQmtoRjRFTll3RU5ueVVuMHMKLS0tIElGb0xyMkJlKzh4dTN2OWdUQ0xS
            dmRWYXhyVGhQdUFMQmtIRExTVEN1VkUKodkYuJXfRkGbVfgTWwfg2E+ztHObU26z
            wtwgCJ4acmOSAZmWf9fkqaplbx+LKkmzHrWAbBoeMJG3Kjikcwc4Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:03:52Z"
    mac: ENC[AES256_GCM,data:ZXLkHCxDGn32n52mbsODkiaaDSeJf2ppWLx3O57L0uEpBIuBkDCruqh7YGtt175CVzYRteNxcsA9nSviTnv14GoxUFmd+qKO3i1WiQX4ghjQx5O2xKPo1tUQIcClSMjSBi/GnV/uPrAyN2RLZOUElKJcn4MplZMReunhQCB1ZQU=,iv:lSGNlp8Iivrj70Ir3nIDGEorlCDZE1Z3KJp6mAsTG74=,tag:w0vwXpvbAr5p/9HthvPL/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:45Iw6npVdYOFN2xB4Ks0BW8Kv8EDVN7QHfd5+Qe1Te1eR57yge0n6f6jdz5ZHS3A75GTJKdFN4IDpIC2Gwp/z+th9Q2/bvsTtIRhvY3Uq+t3ucTF2EqOIUFVEN1IMTuTSCkpx3+uJb2zMozX0J43z4DqABC3CfZ5ZjHqZr3VZ2W+yTmgHRZrFUAAl+PLgzxtgCaHERiIvTuPl30AkS1B6Pj7wLuP+ChQetZtenAs+lqXPBPkseyM3knutFiqecqKXLjlKSTVbAUfQJUaD7oBHpNU3b8rZWYdKOpUVciSIk40figN5oUUpcc6H9boK8M8Z8PTJONIx4kT5mrgPIOt5u+cy+WWc+utqkRq96jSuK1qjpb87+QcDnk0MREZv7doGVb0GpsDYkY+wjjnP060ZnMm45cxgCjdOnFZ+FUuLiu1D8o66m14NaM2pHMkidsm0e7fQRI02VAA5Tp/nsvhKBfoTF18StT/K0N6UlZYpAS/WQk/eDEaPVLZWeq8/c5qebLnaODwtFrtuioNGrQnIwxiqg/o1WFAvC4Iq5ohlrDtOJLvO8QlI80DO0gtOULoQ9GP4qd2QFjBn2XeqShdxCDCCqfScsqj9nkdCdiFEotXDzUkK7VbTE9QOKov8b21jt/t/0s4aUhMNXkQvn1c0sT6pOSo4nfvAe1gen+dpO7R,iv:MMfsstfvYXJiLB16d9RWxi87iPaj4Oigi9yTA/UCU18=,tag:zTz0Kh0toc4tHkYNbJO/tQ==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:DdkojWaf5rYkz3eU7w6Y9rrmCqOCKc9gF4zXPoBDbwxylAOZlKhi8EyZReVv4p4HGP6pDhU+NjDAJdj3iVHahi9XINiWdvMVYZAe72MVfHQFZxVNRkx21Ka59oVGm0JklY8qqGp6nSN1he64I1q5mlgW/X7xcGyAomQ1FHqM6ZGCpFSG/y28vNfLngLI1Arr89mkItNNx3I6CDcmESy7RyKuq66ChQzsDmTvs6pvE9ckJzkSlg==,iv:4O/8es+Stt4/gOTI+xgNo8D8rivXjJ5Iw409Cj+mjlw=,tag:5wSpwFUvjdFlHZLy9Coccw==,type:str]
    known_hosts: ENC[AES256_GCM,data:coHOyR02A4Uc19bS0Ps9rhce2KbXijTSUQtbos3848vAqitg1DRubrg4bb9CoJtIGX/4rxdP1CV9wSel19eE1WyPQWbG5s6R+Gmtku3gQYBM2NDocYpmK21rq9wKY4kCvZZVEEgAFk91r8uLBBaSeZyFea1/X/aQTCTYNIat4AEmyj0QbMzsLhmbeKq6SKK6qK2g5VWQVV8l/eCMFaHY2NCax/wVbzI36Th8W1O3Gi8p7MDQb89gnCPSql5u6hLlHMejckkcdDYkYQvT7vZ0aL/Urf6wL2MNbb60e28tBS3UQ1mnVTgNN6dE1TiK31N6mweM6QZzSP43T9jxIKxyuTbawX5+tqHiUtP8YM8JNTHv93Nf/qxaDkLOsnQTyb78yzjreWb7qzSQaFm21lH52tT0wwzrM6RNeMM0maqtFIUw7fZYY5vkt/wLV0eJJWJuRDf13HeFmEFATGXsFYWGNRvKlhZvibqn8XXEMq+YL4Mz8lXrq03Q8tFrfP0yD5hngGJ5QWI+sVxX1QKt2QB85sAW2ZehLiWEOb7/HD8vdZNgaXHLFWNEkczX,iv:mDPVP+Sptbrh9fHkqlXct1KWRJO6wq+tvgQ8WkFWkvs=,tag:W1QSa002N/ej/JI+tEdruw==,type:str]
    authorized_keys: ENC[AES256_GCM,data:88HEZg6AMxCywgBE8ICsOEO/pwpSSaYX42TITsogBb+9fLFhoPezcEWgVgJtfMXb5vLHT09NQ2e8c3n1mpoqDEl0PXunTPKuzMVhvi8OnYpQIQKh+buknGdpNJmvfBJ5/6qcaIFUr1IQ5Y/35uPaF7pDEPsvptNVSXO3FSUarQscme2L8mPlwGgjucnWIuFWyFCsQ40yOHBXrnnpFmqVyPrB3xmKAp5cCK5EJPKiuB9wGV9u5Q8YAxxYohJ4chyRLV5GPO4Xpi9dIl35gHGG1MkwRkjdk4dC0OFccOEIsvG9emdyOxYvaTQErfZx0NzaOxFVgBEFB1ue5KPR2L0hkCzMajErFnvyl2vM6N1Y6n9oT3mvw7eC/rsSMD8idGpT46t7fcyWcmtDsQ6/p+ohW1RllYEL/eSRilM3X0SOfb9SmQcxeUN2FAJRmycw6udEjiW4w8uyY7tj5shWf/TnfrB+DWFaNfqJ3/pkb8CsOjicV5HtMgpwQx3vLYqGtGf8bXgP2TqFERCx68RRdlUpPgk8TIAf9wgYqvP8iO4Z0wkT4OLWgvS04j8xylS+4BjwJ94DMQTZwCw8ITO39Dff07bBaB9n+xOybuV04JqslkHbq11C54UzUbhBVYogZ+8NBbsfjvn7w6dRGoLinqCByZRYdqoNkwVuhBx9AUewBKIp8T1OjECh+81Na56fJUF6vUyhdiHFweib3fApm7dUq6JfHJLJsDpZej8ONGmbJmMuerpofZ/Rg6nz,iv:mBI720KqxpZARAgNuxOEZGjDwyY7J2DQAmix4zjI05M=,tag:dOciL/sWpmB4Rut3a9oN2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY1UraUxldXZ1YmNuQVJP
            WVdWYUNKOHpZTS9WTVJ1T0JMUFh4ZFdmbldBCnlUMjJhaFMzalY0bFRtMzBYM3h6
            eXQ3WTFCQmtoRjRFTll3RU5ueVVuMHMKLS0tIElGb0xyMkJlKzh4dTN2OWdUQ0xS
            dmRWYXhyVGhQdUFMQmtIRExTVEN1VkUKodkYuJXfRkGbVfgTWwfg2E+ztHObU26z
            wtwgCJ4acmOSAZmWf9fkqaplbx+LKkmzHrWAbBoeMJG3Kjikcwc4Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:03:52Z"
    mac: ENC[AES256_GCM,data:ZXLkHCxDGn32n52mbsODkiaaDSeJf2ppWLx3O57L0uEpBIuBkDCruqh7YGtt175CVzYRteNxcsA9nSviTnv14GoxUFmd+qKO3i1WiQX4ghjQx5O2xKPo1tUQIcClSMjSBi/GnV/uPrAyN2RLZOUElKJcn4MplZMReunhQCB1ZQU=,iv:lSGNlp8Iivrj70Ir3nIDGEorlCDZE1Z3KJp6mAsTG74=,tag:w0vwXpvbAr5p/9HthvPL/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
