apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:z3IcdxJYgqGI,iv:E/ZR5y97Asz97DI/61Wj8mhrodHeKjF0TX5od22O68M=,tag:AKZN7LhjmSttxYdEdokBiQ==,type:str]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:ZRMIRS4swSe5n3YoYZO4bjTWqpqsthqU+YZDsIIYECTVXxh7AQ+9Vg==,iv:ln9yC7333hijO0G32WYir6jHlZ5ZfI/H8Kah2sPi7ek=,tag:+SJLLNgbj7qEBQLjJpDi1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S1RWblkzWmJiVlFuMzdT
            YmxyTVo1Nm80MUtnekRmRDNHWERweWxEZ1JBClZONDZ6MDU0Nko0T3htTjFVME5x
            YzJBT1R3U1NCK2FUWWVmVDdEUXpYUEEKLS0tIFdCWXJGL1RRWTJNR0pPTEplS1Zw
            REoraHh1N0pPNVc1bUp4cGFDUUNNZW8K+uRy9IgZ5d5V4QxVxQrel905iSTv/xUt
            tDmLLe7eJN1sY0fGJrBe67ut2xVdu0HzqTZZLfqdgApvAO23TohJmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:46:08Z"
    mac: ENC[AES256_GCM,data:1K8VUGpYICKNoa7WQG0PdF6sbGXcPr0mv1lJ+k9YaGRMFEY4d7T5/7oPQUQVCd4py/RHJ0bkyv1ak7IVY8ZAYwyRld0h2w+8Lkkg/Um4HSv2PSa2IhvanxSOlOSfiyene9ZNlL2t9fOahrPDXc4mEYwGG0FA7ZKVTsZvCEQ34c8=,iv:f8xKli8faOeOKJWldmscqeIYMxqGHlSjEguTdsw/PmE=,tag:Xba2EkGna9kV/H8NlzKUYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:UY0z5RTEK60Dw9f9YbT4p5IVuEe+2HyuKk7LeiReIEIVBUKQoayp/vUUfRzXhsQtavM/fipJRPUXz5cv34GB2SPC+GRvuVr40v3tzKkW2aiYtoXJXfAQIK3bRf9h+MOjd2Ce4FJs4UzS0xIm3lmf7F3/+GkI0NIw7GGkP+e4VQStLAqhb0Y8hhkRagZ5IFa4HvreuEQpbMBc2inw2ATcOuYQR+lvHzvleDIsq0xGxdiv2JmRjEM9OqmLdlLPPH16FjvKgSfMC1MCy+zHh0Mxl4eli+SmsO87BzNcnDaJupuplheHecy35wDtUxbOmAzt3mBKBB4qbR6Ek9f3m0KZMTtj3TP1i9/NLeD+s27H8TK3jjkL5Y8r7Ftgu2jEVl8zx8KS+iZ2wL5wOdjkLOc434zrsSJCaCNYDx7BHJiLoDABK1Z9IOLtzk+V8Zp5gGpioZRo8fYu7Y5W7uWmLzsYSvtmT7MvgcyziWkBW6CMjd8v8Y6mJDZYF2RETIHB8gyPm9m7XJJDp5YatxZDExrwnbr2/XyDe3JvrakzTPEtV3wgCkcPb5tsEEQgMtv9khFFTuUpOHmMS1wA/NkkcowQCAFUmc8gVWHG6Vxagpq6DVEYycngbxyDCLRDAWIaDV7PNLbLFYKzDSy2cBrMnnFzJoKGIxnJA8f9GvRfMff+kQOb,iv:mc1z/Nf9LyfG8KTrsnskYr+SEK9uFA2TBeVsLaPBLYQ=,tag:sy4VdOUre4oDKnoBYTLjsQ==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:lJcNc7Z2ohug++lsJH5lsa+Yd4A3o+44aP15bd0WUUWul6F+VYigHiIlDpK9dz3b5Lh16UKM81cCfXUx0IXBmeKa0Kdy/MkhdfwNWDaduX9BLytptBkYzfyjRs5G11Pe5lVdXyvfrqq5DcBX62+2BZt1LTZvHLUHvigsdVnnyt2F8Hjvq76hY9Sjz6wbvHpTntKDQpBrCK46WSrAAYGjNfY1qWE5Ze/Fp/SujqN/e3BZooPjnA==,iv:Pz0u0OX+KxWVHL4ofErGQ+ZvmTM5iUqR8ozj93ocij4=,tag:Y2wzc6s1lyWnpjfRWLYZew==,type:str]
    known_hosts: ENC[AES256_GCM,data:WAdparuQP3D0AimIGRuIx7BaeniNSi+JRKN5cFG6s98NoZlkHo3HfymIuQ6lT1N1g+5Fw+mrhK3MF+C8hYjHUmvJDyL6v/KtSnE3KfphckR2tNiTelKTfAeTlLf3Zk3JMTRo8if3rfB9VtLzfmgKEzbPE5XjAkIfedTMhWp35w4v830PaF0D3FIIwMFgIqKoj9kgoQjGYBb/LflbaX5/c9BoT8nDRNjmjDyedAY45tKi72xnJ9roL4mP9Vhqbo5NDqneAS8dau6njRP7ISUx7yFt1VaVc7Q6whxA39WIXjHkHKVUu+5MxPUbVaxBm55CflrftN1sgiUck3ex0CFJLV9MEPiM6q3wj6oDDrRa2Zvk50Wh28eXnFLgTCTzA88KzbJPnibn0j4mToZPUfMA+X+tW6Fbsb5Q0F4PAA4dKvPtoH3yVwjUyaBA++1uPBYIONJU/2SnP+lDYa4fZU2ynSIMcbZpOc5WkfwQL4zPhpQdLKDUaG91LWwXEw7H8CNgyPlIPP1uenC8xcIWziMzTkhAeXjm1sUYINBiZ12FxD8BY8krVbA4xWVy,iv:jZ+RpvJPHjDyKSs+yBsZepLk5ovIfMsaYVg8AM63wtU=,tag:iv5YeSVctZWpa2MnwPaclw==,type:str]
    authorized_keys: ENC[AES256_GCM,data:n/W5oAMZjW6ZcwDhFvZuNjD0mkKl0DT8OLFi9fpZX5kLv5jkkXAcEqcTY7K3e/Qnksqx3oT5F2WXmUiDiRMN8PN+9v2zJkWi5QjjHHu/23nqwdX9WIxw8Q4Ya0XiF8zpVqdedAtnPQgQMmZZyUcGkvfj+n9sw23krOGdfNA++YEtAgzAePZXqDMeboCwRJR2cEj1ewMGwdy86qw+eEeYmiJxZwV6SsI1CUmAgQzSCkFWBTK6RyskanrinbJS+GnRlfoQfwtACDDcgM09As9xPdiLfOZi2LOPb3kl+vHLCUcGgz6v5cMu51HMIhVrOKSt6s9EJHJo3L+yLveEXafQAPDN7z7oiNDmo8nnyHUvrgsETkcSbSOzESkSKeCv0HFwL/ORlnuDRQJ8XZFSYjgqYF4WByoD/jgPUh7DQQg04eooLd0ZWPEJNPLhiEmB0LHhsFxvJT81Cm9dJ0ti2eePMQiuemGT7ZzY7lNAd1HEh+9vbplbFlAoKHPf4go+VVry9MTmTWJEi3JtCLxYp3NrpejdsDJLM72XJ369c0MfOFt5LIAOpRucUC48sI3rF4h2L3wc6ogPez0GYS2mZZ6PQkf/qLn3fU0Se7MDJlKp/yc7WCTITTnifjUQ9x2VIOQv+qs4NTOwHN4MrG6VmHrNtwMw6qeH39lxUZZ0ewOds9czlsiAqNCIINbpCCsT05aMIFpKAoDKeMEbYbuikokoyShCLBueoz+0KW4nWArxFdpBhmPdSv/Y1k+d,iv:HLXJ45bFgGaq5ym8BLkmpe1V0T6ctNUTZUIW6p13zKw=,tag:4DHHee/8xgxqhUHq1unGzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S1RWblkzWmJiVlFuMzdT
            YmxyTVo1Nm80MUtnekRmRDNHWERweWxEZ1JBClZONDZ6MDU0Nko0T3htTjFVME5x
            YzJBT1R3U1NCK2FUWWVmVDdEUXpYUEEKLS0tIFdCWXJGL1RRWTJNR0pPTEplS1Zw
            REoraHh1N0pPNVc1bUp4cGFDUUNNZW8K+uRy9IgZ5d5V4QxVxQrel905iSTv/xUt
            tDmLLe7eJN1sY0fGJrBe67ut2xVdu0HzqTZZLfqdgApvAO23TohJmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:46:08Z"
    mac: ENC[AES256_GCM,data:1K8VUGpYICKNoa7WQG0PdF6sbGXcPr0mv1lJ+k9YaGRMFEY4d7T5/7oPQUQVCd4py/RHJ0bkyv1ak7IVY8ZAYwyRld0h2w+8Lkkg/Um4HSv2PSa2IhvanxSOlOSfiyene9ZNlL2t9fOahrPDXc4mEYwGG0FA7ZKVTsZvCEQ34c8=,iv:f8xKli8faOeOKJWldmscqeIYMxqGHlSjEguTdsw/PmE=,tag:Xba2EkGna9kV/H8NlzKUYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
