apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:j9TvXidCfbZL,iv:yMSL3/8ex+O3NfVOBKvCBQxF0xsp9/fNw/zmi1AztZ8=,tag:ecwNX5h2PeB+O4P1XW/xwg==,type:str]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:b3niFsUtK3SEPu5pZaSvwSr6aIfVAP/K9+7LlanUoKWBXkDYMRTVNA==,iv:vPs8p1xivMFMJ2QcNziSl5Pil16b56TVMzGsUfCdt+A=,tag:pnRPga9UWlbFjdT3BhovCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUUJlMmdudVUyZjArSXBF
            clNuKzZxcjZoQlcydWxYMkNZcVVYWUtuaVd3CmhtMXhwbE5HT0hiMDdiREYwWGFG
            YzlmaE5DWVVqSng1bnoxUm9oaWVCVjgKLS0tIFhhZEoyTkx5VWpZajVpWFhUUW9t
            ZGR3QnQ3L2JzY2kzMjAzK0d6WHFuZUkKDbMoQncV4WGBIVfpXH2K+lY6vhwhJrdW
            IES8kfN+6aw9RU/9Puq2J59LRWG35X2nvpuucOXhjPVODODHlvHjIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:46:17Z"
    mac: ENC[AES256_GCM,data:S5jJvHX0TqOtm2jvyepSvVXtY4huVH63MSGeqruYjVR4+7a1ZdoVIOg+tJjk1gsUzCVtz7yawkO+x3A77ZRVmLSxxVRzknxUoZVoPBLGGSNZ693s7kn03oW8NUuj2+0ioZGvHPdqHoiew899H4CyM3Gl/AuNFoZ32Alr1YO+BtU=,iv:MN0mQitiDKAgokFmTkAsRbwpLVDYz0RSH4cfIyCf3Dg=,tag:f8ntqwubOGJB15VaGSq59w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:Hkbj3ePvYwWpdC5Pfgx7H6cjJRGOuOFVbgMMIz9mOB9qsTFvVAAf0VRhrwoAz3SOnZ8Zk+Qzsibil1EAZOkk26tt6vGjb8MrIA8PooytrBtU5h50CXaYO9BBE0lqpN5Tfvf37FUehlA11rXmTYFqr4Eu0AloHDCTdgJX++VxpSBjap/NJ+izIXE85OE+iWEpydW1RoulUJS4lpPgrxV5oLDHU+f2qVLdE8DJCr7EUtL1AgBdvn1mLnIHxVHnZAtfErgDZNOBt+lTTUN4ENsXZ5F2FXmkA03RS6PnCoWCEXhsnsapw7Yb9Hnp404fhAsaeKiXxSde2iVQ72LqShMpnEm3iJiVM7n/KCBDsAU79MN2lyg7l9PWLtaCqt7MN3ctLTQxekzFowvv4LbyB6GNgkX/eqbBfKkrnEITPAciVqI9MaR8ioEZYAGBc9ORbO7/H38+Jrg6jxxgFY/ZrA5jfaLsPC60OrMJuzR/tmCAmhazmva88OGmzF/sdqSfMwWPdFJ9DUBiP1wVjaajUjifL8bjL29OxMXAdr6cprDKZiXzDL71Lm6HUxYcF5+IDrMmTXH3uAds/qlymj3I/uHYf18A9FvstYeULLfSjPwz8/gQJr9Cz3uHD6ZvFZ89RBSjCQ8yqhQBHHIGTjRmQOsqU0UjW8Z1A8QTCGORY0TE4qVy,iv:ISjQf+ZwW9pr8ssBfVTu8Plab6NdW7VxVsLm1+Hgf8M=,tag:+GJUiRmhf00C+0Lf+rneRQ==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:4MozrJfpXdKfmlt3k5Qpw6yfCD2UVSVJqjbEvz7GXuHGqzViHoh85F3AxDNrFWdPDlWEDeQ2BTOLpYdRXO6h2LIm5LiR5OdOUdEaAE2pV2quJjarUcqxdMF/zqxvJu/B+6jq7NA9qwTF0wtjERpMVLoQFU/3TGYVNy8BjOYL/MCqs8YTkS0Kck1UwO8Xy5cypQqMbOwdzQiO1UlyQF5Y5mAa/hvsSFcL9Gqmt10TUWugmTpQQg==,iv:aU3r2QCml0xiMhoh9/R6qWDkBcnsdqOouzZ7HcpoG24=,tag:HStZjUOnyBdba3wDeNmYrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:TTa9KazaT5wjjWUMYllNi4IcDVRdruQH/EedGQ5YAYyPOXzPDNF1mCiTKPztCQMAt7qRpDucAERIuqNEz5NK/0QpCk8OKCNIz1H9QEB+bJAK8JNopoHdtieessobqy2bYDgSJMV0EkM2Vb0vsSdbp4QYMhIsCbdz6BGWUhOOtD5CDimTTlO4HzQ4VEIpj/I9N9YsvgAKxzyOkOJAhVfXE884uxqKoDRPlFX6wbr3XMc8BfAWVjpiTbkgxNr2u5gn+OpAyOQPOlTf2rsV7zqUIuZGhxKt6NEHcjhB/VdNTi9AFW2FjQRBp0Jssxwdigydq+CYufX4ZJEQcr2AL+AkkVpn5nZadoWTSqKTpekj08SVu8plgedgi6cZGg9Oyw/ntjaNMtGUiLx4n9s3V8SELkVb/uolK555GXPk9BDoSJWCamqOzEb5r3niKq8Avqz0Rtot429WiR9y3jzHiv+eYc+SptRdhKHMJ4ffnxsgDWHBnOYX3ZkMXZauqxbUq6q+qqDHU4q8oJIfI6dhOlAWAeNGt7SCOlt/dhKVxyNcA1DKQYTJysjWfbXU,iv:LbCzhmrCc8Pwxj3t/cd9bX16tgbp8idXo4NExn/JCfI=,tag:z7xo6fweo+hkm1Vf8AdMSA==,type:str]
    authorized_keys: ENC[AES256_GCM,data:U/qwYqs4HAT97wMdPdOP6sCvkaqe/Ob/kVjP0Q86YJzIMAOWlEItFYNtFHNrg/zQsgioDVr4nfLxMM8LA4IFMk7BDvSfED0qv2ucyZK36JQUaGL93PibgmbQo48wrPZ8LvfmFqv61uFKunLwiJ7L/sWE0wiCDtLQzpGYtj/kzmT7Yr4vDWfMpTKlwY8hEmZVLZJWUR5eKHJVw43Z3XehbcQm7IWTAdnQ0qxgon/krv9b9eHiEmZoq66zPWcpMPwCc/ld6Yb8y6Kc0L4DYJc4tiQMVx4HdO28FIoUpDS0bRkTUSMYb1n9vSwHza3rQtVu+07QAfChNgkXhuMi/hbpMek26t8+chUDM1sdjbcuqvBj+XFT8lvzjEleSA24V9I2hV6Cct4DEJ10iwIA9cYioNzqLESayvASi3utwasfImslW9DI6rQUqpmNGJkiM7K0fv0cY5jqTsFUxsyq0Aj0k7H/F04oCmgP530qBvHpnAVXocp77BnvwoqUpzQXbhUhIyh+rO7DNPtCamqYCZyh51uBF7CisD1EM847OEYSMyA5+K44zrUhkhuo5uNA2TOrKBJVCgyptbrM5o7r6ck0cdkl4B+ropNhp0QzCyTidnJuhL43+WY5KFboLM95sUBba7d7Ku6hCDID6PY9ChMQdslkQ00KBJQLqcAliTdhshxTHL06n8iZQW6GcSbNlezPGsDqMJZkC1V/HXLWBf6mI8Ptx+PG6Xbwjt0J2wKSOM1y2c0TBExbxzkz,iv:RpH5PJlsQiw/BbfwMFoBHl2kj7+w+r7bRbK4KhKtDVY=,tag:piXBneZTMFb1p3azYm5TVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUUJlMmdudVUyZjArSXBF
            clNuKzZxcjZoQlcydWxYMkNZcVVYWUtuaVd3CmhtMXhwbE5HT0hiMDdiREYwWGFG
            YzlmaE5DWVVqSng1bnoxUm9oaWVCVjgKLS0tIFhhZEoyTkx5VWpZajVpWFhUUW9t
            ZGR3QnQ3L2JzY2kzMjAzK0d6WHFuZUkKDbMoQncV4WGBIVfpXH2K+lY6vhwhJrdW
            IES8kfN+6aw9RU/9Puq2J59LRWG35X2nvpuucOXhjPVODODHlvHjIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:46:17Z"
    mac: ENC[AES256_GCM,data:S5jJvHX0TqOtm2jvyepSvVXtY4huVH63MSGeqruYjVR4+7a1ZdoVIOg+tJjk1gsUzCVtz7yawkO+x3A77ZRVmLSxxVRzknxUoZVoPBLGGSNZ693s7kn03oW8NUuj2+0ioZGvHPdqHoiew899H4CyM3Gl/AuNFoZ32Alr1YO+BtU=,iv:MN0mQitiDKAgokFmTkAsRbwpLVDYz0RSH4cfIyCf3Dg=,tag:f8ntqwubOGJB15VaGSq59w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
