apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:1669lphviLd1,iv:fB/n4eqfaVMBbfQhVsZNBqBYf+s5kfhpPGqdr7Ou71s=,tag:wu8fHVDMGe5o0geGHQeuZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWG1ydDhtcVZZUzRRdFVF
            UTJ6TUYzeGljNnBSTndzaUZ1VndmSmxDMEFzCm1ORCt6UHB3a0ZUWTlqMnpxdGh1
            ZXdOMDUvQ2FxdWxjUll6YUMwa1htRGMKLS0tIGErenhjaDFqKy9DMWIrVUd5ZnJV
            WVBxTnZLbEllSmt3ZlVOSHJidjNrUzAKvb98ZU7LUlgFyb8f1cBNMocbSX1tSmAu
            axlmS6tu5d2QYmSyslQZvX0uM9ir/+OyuXShMjUfSb2picV6MFdO3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:22:06Z"
    mac: ENC[AES256_GCM,data:GzerhNR8Nbm1WaHASrSSEoMGkfK0U/dIaC8F5zAkAm45k1dDQ7qsUt3eQiofUgXQFtn9km7wySkZtXwX/42GcZEwjG9RSWxKMAFi6XJxYWEQXjCHmN4TGSyYwNI7vLHeaNpzHellUMXIvCMd3oOn7+xhf6RfxxiCku9EN28PEG8=,iv:Y2pYaMFbCHQE9B3VDPjbn207oi21fHfBBSdC+qwQOGU=,tag:Bu/Z18HJfS3smuVL23MJVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:oMkxv/yZM3egnNfD3SC0KdZ2Aq96D8EEORKjNZPzvuKk0mVBJkgDtloTorkOjlqzXbWT/8jyqIjGSBtOyCkef+dIjgqx9SxWtYcT2f2WY4p/OebeNvBbWicLyp4dc7m/9jJgKamNt6v6uuz5RdEvfuTzHvqAGCuIxrfo9OF4M1qhQPGtqNwfCuriY49QIGSHGHQ7nOKcoKCpEuYOG8hDxMcYuQczEctV7F6rhQPyD52pjb9Djj30AM9LO/jrq58goYTto/SdmuonunP4dsVzZgNnTKl2JQHxfRC0jGdqrKUqMPlyNRON8hK5ICyfuMC5Rjf0nRMQCeiq7Mn0lupNDSRq7JjxYCp5SS6q7XhgJcKLlrwAkRh9KQdiKW4pVPCvhPE/WHlpZH5klExZoSAxDs7nhzWbdp9Jzvfgcc6olYhyu44aPtyfbLjzwUGm/6jIFSCVI9eq/N54QmLp+X5mcbdeOFfL7N04LPR/3doyx/OH41b0/1Ku39gtPSPg46gQziqElWrF/1i2OvO3NkTOw/1YknsF2TgQHoiBEJj2SXZPoWwVbyY+A1HqpaQIjrm2Ol/yjeo5Vvegwau9PVJ5LJ7db/IPq4AQpgTJg9yuRa9KSTUyHe0RRmJwYi2bzk69xwmfzSNLWwc6mwkv2FHOWaNRAzLhbeOhW1K0IKK/jaru,iv:SYlbCGp4QmQJvFzNDQqOvemeHU/Zb5M8zwSBUOaspDo=,tag:VrTNy3HVawLr/uXF/jp4eg==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:C9CAQaes0NyJjKoXkn6MoM5Ra3/r0Zo5cV/bZKg0DEYRBsKaiJ6TTGgGwRDa3F/HetaAkRuiTZPvhKlyw70R4koxo6BP36TrVhqRhXTEdqb8VTrGS2OzMcXvrUoBoanrimmvJDSGTOeltw7Pz0ATWTq0xCbwDowSnsQ3Ep4O7sywA/0GzzPoYBp05NIL9MAi+BMHOafHEPEpjUuci5aX8pRADKGbx2RWu276/EEF+nj8Gji3lA==,iv:dQLhlVHYqO4OhOnsHMfV9A0Upydn6XZvhK6wJHD85XY=,tag:BApNWlkRza+vaJgLfpbeKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:qeZl763DAHRNIa/c0XgYN5hCGvSgahUCgLHjC04aMdUZaHJONvnT9yjzb/Gl+x9S6BL05K8aXrHBnZ/rj569ASzYwqt7al7wvacq4G0laWaaR5zaK2wFJ6oPGksZ137lw6XrponunAGnhc/xMJUgL53nfL9vGUKMiohnGuWpwzfFYPzM4nz8ITgZ6HZdKTMecR3Y1ET2JDEEDW/lX4MKKN9QMLGb19GznDaKnpTJ2Hn4DdjfRZYU4VKom6mchFvAaurMme3nGDIovhLWh4ytijS9GEfO/SZZMjIqFnDVJI7fpWCYWcta0bB0MVi+TAWUg14HDuRVj+bfUZnZ25+0H6KOAvIVzoI2l3CP3nT44alFNmeBmkDp1KdXcR34HMwmYA2mhEnd4cYndlSqHrEKb1w4Zafp4nYJLEzf4WHGek+z7aevBxRd92jSr1rTa/Sk4R9IUjJwmyy5S+AVxkjqpsfk1+hb3CI0AKbJvT69g/HcgUODRl7/Yg+fSLO6ANr7kIx6Y/1F/7JRfSWNevPiaZ/P4e1DQP0ja46PMCCADcHuqlktzt4se3LL,iv:X+N/4mVesmKMgNsDcnhY0Z3ixZPKNK3R2e5cYHB5vj0=,tag:45w0DVasDwWT9ODMsfGRcQ==,type:str]
    authorized_keys: ENC[AES256_GCM,data:guQnqkx6w7uJNtiYaaNQ4jNMW1WwlB0woA0uyoOOtySg+4FRWBN3aYTmWiXKcRkhoN1Dubr0dWzInNyNZ/LRwSr0XEyJLS5NBnbfe71STO8L4dR6NeGNE+t6gXhP5rxg3V6d9HCojcY9wJZI4agk4fnNUwyYLo6GwEvHfP/SstgviKhnbWr7wI80Wp0ZDsA97y8v4SiqAASo52k0XSp7icicYfmmciOLp3J44ZM8soQLLh56sXv7veDnNpgHmEmbPUF39lQTkTlk+Dd6RTJFJHyloMVeZDoK1WEKhCLgvgmDm3GKxceln8tDL8DF8BK3POss7+ardkdl9xXxxfVK1e+HvtiM+Rao/JSsR0O2O+2k2Aveg54tuajb7b/ebdkSGZ58ZWvOG9sB0mc5wRfngAMT6QBPYPNDFFQXNRi6MDZb82iAUcOgfDaZ2KzJucC6pd6ggWwBImo7njKptcdBkgqX8ffA/GFrogcuG6zf8jeajObu9nHp3emKQ1MNcde3iBYsvcgdI/Nr89pOeXQ5uKrMQboni6v5TebJ6rypOU6afFq2+2W3pUSnzc4msiqspAcoLFqNVJt58EnOUz4HEzGOsv5Mql+Zl3/crs1ubcUmIa+rOVAagLzocW/XAOvliuvwMW+Mnm6PBQ/zZlkdlWat/U0UGdXKLd0/9sM5jpXVeyZJqDp14Iq7A+hGcoZ7bAWWy4ICqTBVQid1kqrJn5W6pRDuIz7BWB8ziU029iZDyWM89r1Zh9H8,iv:iSsey2Xh9z78geSxgwdYEfdeu6nJViGqW+zmNY5MR00=,tag:rtRGGFfHDKfSTI7Ep9sM/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWG1ydDhtcVZZUzRRdFVF
            UTJ6TUYzeGljNnBSTndzaUZ1VndmSmxDMEFzCm1ORCt6UHB3a0ZUWTlqMnpxdGh1
            ZXdOMDUvQ2FxdWxjUll6YUMwa1htRGMKLS0tIGErenhjaDFqKy9DMWIrVUd5ZnJV
            WVBxTnZLbEllSmt3ZlVOSHJidjNrUzAKvb98ZU7LUlgFyb8f1cBNMocbSX1tSmAu
            axlmS6tu5d2QYmSyslQZvX0uM9ir/+OyuXShMjUfSb2picV6MFdO3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:22:06Z"
    mac: ENC[AES256_GCM,data:GzerhNR8Nbm1WaHASrSSEoMGkfK0U/dIaC8F5zAkAm45k1dDQ7qsUt3eQiofUgXQFtn9km7wySkZtXwX/42GcZEwjG9RSWxKMAFi6XJxYWEQXjCHmN4TGSyYwNI7vLHeaNpzHellUMXIvCMd3oOn7+xhf6RfxxiCku9EN28PEG8=,iv:Y2pYaMFbCHQE9B3VDPjbn207oi21fHfBBSdC+qwQOGU=,tag:Bu/Z18HJfS3smuVL23MJVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
