apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:3OEnqIPOuM53,iv:DQJyiaeg0hdL3CpTcCfX4d48yLk9Oq1yekPp9U8n/vk=,tag:NDinyYeoztr8OJPHMITa1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dXZCN01UdDYxQjY4Nmd2
            TnVKYUhJM1oveDNvc29KOTdBOUYzSVMxVTJjCnlxS01uU2FQUTQvbjBDVkxHWGZ1
            RkVFKy9pQks2RWpIZWh1QnBjQXdGQWMKLS0tIHVLa1F5VitrTVo2STlTMmgvSHJp
            K3hYLzl5dE1wLzA4Z3RGbGFOcGhVYUkKhPCInT6XN6JrPy5rEJ0S6fyQ8OcYxlto
            SEnRS/9JPmTTPTRfwYeZWCWW67AYtPznepd8+B3WvKN/sRTkBF8SNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:09:26Z"
    mac: ENC[AES256_GCM,data:DxBJsfDZeTQ8zaOWFUUp6Xbxs0TycLfiH7Hmtyt3r0j0i5pV6VFbzxjsyUZyjOPvA7W9C/UxAKThk2SdIDQ0Aj0eoOQm/8pDeEkn0jDJ+Dc50K+qMOdPFftMnSg9AGG83TUdlG2iv8Ia26wCBoNG5nStH7EQqVA6UaF/RueIfLo=,iv:C6kFxIw/a7W5L9bRCZmkCkfz5r+HxBe78zu4ODODmHo=,tag:qmkGKbjXeomMhoUN4lmHSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    id_ecdsa: ENC[AES256_GCM,data:q826bfeoZ7uIJ+qk2AADU3/5QPtRGSnWo5IxzK3Tp7fqjitO2gscFzjRmLKdVpM7385X57F4hzT4p+Xd/D87e4Tt/bhNRbS6thdPMNrvpOUjQVZmFhTskzQnrjfHthnlwHs/XJ1+SQ6gSaLSZPcQrqUmDOQ80LPqRKC25nbXHgayvp4egr7OWLW2FRs6mz0tXAV3twPYekZtVklJHPIGObr5NBLLt4By34QlgS9DwMAr0KURQs+uNCeHvhxc0FaR2RMtCX1V8FeUdK+OcB3qGjSvvws8EVAZDGXn+55TdnjgMpYuAwLr3SgXqMr0jPggS3H+2gGZJ79Ik6r4zYmF7sO6/5mDj02TfXO+oaU4nQgsvypWE8L8DDleCFiRsCZvzFPrSJr/TaC25TP05hcLnTpeBQWvFvqhUsvMwgQBShf8m6PZ1yqzCJ+yY1ZEFgEkvAQAZATME0IMQY8Dehd+yESkZ0Kel9TvhxMYVM8PbLKdNsOEA2112IpiWnsNrgO8nqjSRri9zuQ6O6m+NEnQgRTDRpn2UQV4Wuzcpm3uPWTIGh7c1v8mwuhDWUZV97Da8NBjrr0SQafIO1EL25fYuhr7XjiusYrypLKHkwgCRogh6S7VkYkKaC2rJO6TcmkrECUGHAokekcyN5MO/HAIakiNdv3deIhKrrYE9RTqLG61,iv:vXrGqr1teg9kfr5s5tSDtjYYKGgr6+zidhWbjSwvTAM=,tag:CtIpwCCdt06qaC8CeXj0sQ==,type:str]
    id_ecdsa.pub: ENC[AES256_GCM,data:7b77BU1Rbw0eZBfRioZ/p5kyWyp5GFxUWLowUHOviiYuM00fBvDhL8NQodPmdolYJ7jYsJ+Z4GTZT+MqEMD7dy2+ROe11GO3E08YhC1CAqhZ3CfYvoydmoXtIwWGU2Oqvmzvutg5CH4aoE+DP0sPleztgGzFDJLJTCJ2i+Grm6xUML5AVkyHbvaOVkvSWmxsZ9Oqhq9PUMtEnJ6RHCCAvnzbEOXEs38nJ09MfxGC6gthfsNWOA==,iv:z0+A/DttuPLnoiVIEG1qgnQPf4GFmZnROVLZt4wGv9k=,tag:h/Oo9H6HHgrrTBdIc29nKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dXZCN01UdDYxQjY4Nmd2
            TnVKYUhJM1oveDNvc29KOTdBOUYzSVMxVTJjCnlxS01uU2FQUTQvbjBDVkxHWGZ1
            RkVFKy9pQks2RWpIZWh1QnBjQXdGQWMKLS0tIHVLa1F5VitrTVo2STlTMmgvSHJp
            K3hYLzl5dE1wLzA4Z3RGbGFOcGhVYUkKhPCInT6XN6JrPy5rEJ0S6fyQ8OcYxlto
            SEnRS/9JPmTTPTRfwYeZWCWW67AYtPznepd8+B3WvKN/sRTkBF8SNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:09:26Z"
    mac: ENC[AES256_GCM,data:DxBJsfDZeTQ8zaOWFUUp6Xbxs0TycLfiH7Hmtyt3r0j0i5pV6VFbzxjsyUZyjOPvA7W9C/UxAKThk2SdIDQ0Aj0eoOQm/8pDeEkn0jDJ+Dc50K+qMOdPFftMnSg9AGG83TUdlG2iv8Ia26wCBoNG5nStH7EQqVA6UaF/RueIfLo=,iv:C6kFxIw/a7W5L9bRCZmkCkfz5r+HxBe78zu4ODODmHo=,tag:qmkGKbjXeomMhoUN4lmHSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
