apiVersion: v1
kind: Secret
metadata:
    name: vscode
stringData:
    SUDO_PASSWORD: ENC[AES256_GCM,data:zgxXcdthN+0l,iv:iu3Z/n8YWBbl6o0spfRUr8z8a4DLPySzgoccgRPOjdA=,tag:Tikmpcmg0W2f9VYFEXZy5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdlNraUV5TzFoMGVVV3cw
            UnN2VkU1UkNZbFRqdGZwMWN5SUZMQTFZeGpjCit6dTduSWY1TTM2WTdaN3k2MWw2
            M1ZVeGg5NHJJaG04VlJOM0VtMHl6MjgKLS0tIFdFMmRoMjhNbDJPR3ZMWGRoc1VI
            dzhZL0FJeVJ4QXhlNzJUbUxVVUQ1UUkKZG4kWTneMTEDGEh8TKlXdQV41QyaAMBD
            I2E514OH7NyBbNi69jz1cKDJLorJET0eXs3bx5pw1PclY92I+Cy7Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:13:22Z"
    mac: ENC[AES256_GCM,data:RChaBUJJ8H26H+009qN98DvXHhh0Rswm/AJFVniiefQ86IDfihCAl7C2SJn51yQM56Yckvr6PJT4RIFDqbvLVJXCvVeaefOOJbUWNsM3wYZNE70nXY4d6dvPoSJ97ILQ4B8yJqU4N23c83fAa/DxyzCvG8lACBY/3Zi11+x1Tpk=,iv:Kjoctq1fZyZ5+Uy8dvi1m1+azj84i+v0VYyfjxZkQLE=,tag:162HMx34OLLP5XZy+HVuJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
    name: vscode-ssh
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:l0mX8VEtrphlA8hkGHv1blE/OIGcc7uZeCdszZm5vNM4STITlDCfTo1vbCYJcuFOw3XwmiFK/y38r88n64RLA6gRqSKMWfsbOrgpLNagDBlyIx7F41zJfj70FjrlFW4euMrJ4OLry8PiqvoNOCq6o+d1arWdFnLdK5+SB+rNA7dsgse2R8yfoHzS4d8splgNGhQxjR2y00Box95LTuC4X04qniAkJI3zcOofORuCs6z1uHCKqFv8fugqGnVjnHrwp4RcNkP8iKL476zol6adW78Y4ZpMX6wvhn1oYmVsNzzfCcsxppReLUSIH5zQhTtOEishhmvgOpjrFy75axMbCqFXSSnBN35ojSh6Gpm93JYnLTL1J4CSJN/nAoMCQth3wdlYcdcYPo9F8cnORyOFol3B7iU+2yHWRKN0UoNC4Ns7oM8zyipchfSCBzgrUgoNcYBuDTmkl78yGbNi+dtyTWVcwQzg9fu8XWWBc7+GqHPQkH3KJwe4d0hGzNVqczhd6ERFD8F0lqAbBU7gY31v2GbgXuxHhlZJPFWa216k/M0p7quLdAPfQPhYNHiUww0zHmdcLVD/uwCV2OaMFZ2sPjPnBbiivBjC0H+TgM3tbZIXHkrCp56JrKm0OzFxevoxPNlFwbdp9QMpZ1rQBCuwhZrHNvvrnHTw/EZe7XJ9xnTj,iv:eHDctm2S84/V5ovV0wT/dJlJ5b8omCFp30zd20IncpI=,tag:owopOmt1cCf9dhj5eBAKhw==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:Hqw9LRCPiPKWskLKOigNQzR1hndSQOKqgOqRYQgRgk36PDmpiOMttG6evyVsTf7SKoVIdgBC7GA0aDu4dXFZSmi1EFDqbnYSEYxl7dWWr04NsExDCdcJdrt52d9piwSul6rBtSs/vb6uyrp7ENFBoUz+Hl39WPGBl8LWRa6sAV1zq5uw8o5K/Fy7LWKMEHIzSxOPIpYShlaFxoHVxU1Y8h+s6JTArQ+esiq1QRr3Vd7k9q9LIQ==,iv:90jxRSk0nULNIDHE72jRvLS/1KUlG4vf22o/SPCK0IY=,tag:DTjkuNuliawjqmF+6IJeVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdlNraUV5TzFoMGVVV3cw
            UnN2VkU1UkNZbFRqdGZwMWN5SUZMQTFZeGpjCit6dTduSWY1TTM2WTdaN3k2MWw2
            M1ZVeGg5NHJJaG04VlJOM0VtMHl6MjgKLS0tIFdFMmRoMjhNbDJPR3ZMWGRoc1VI
            dzhZL0FJeVJ4QXhlNzJUbUxVVUQ1UUkKZG4kWTneMTEDGEh8TKlXdQV41QyaAMBD
            I2E514OH7NyBbNi69jz1cKDJLorJET0eXs3bx5pw1PclY92I+Cy7Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:13:22Z"
    mac: ENC[AES256_GCM,data:RChaBUJJ8H26H+009qN98DvXHhh0Rswm/AJFVniiefQ86IDfihCAl7C2SJn51yQM56Yckvr6PJT4RIFDqbvLVJXCvVeaefOOJbUWNsM3wYZNE70nXY4d6dvPoSJ97ILQ4B8yJqU4N23c83fAa/DxyzCvG8lACBY/3Zi11+x1Tpk=,iv:Kjoctq1fZyZ5+Uy8dvi1m1+azj84i+v0VYyfjxZkQLE=,tag:162HMx34OLLP5XZy+HVuJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
